/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIApplication.h"

#import "CLLocationManagerDelegate.h"
#import "SynchronizedDefaultsDelegate.h"
#import "UIApplicationDelegate.h"
#import "WeatherApplicationProgressDelegate.h"

@class NSString, UIWindow, WeatherController, WeatherViewController;

@interface Application : UIApplication <UIApplicationDelegate, CLLocationManagerDelegate, SynchronizedDefaultsDelegate, WeatherApplicationProgressDelegate>
{
    WeatherController *_controller;
    NSString *_testName;
    int _testIterationCount;
    UIWindow *_window;
    WeatherViewController *_viewController;
}

+ (struct CGRect)widgetContentRect;
@property(retain, nonatomic) WeatherViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (void)pptTest_liveIcons;
- (void)pptTest_openLiveMultiCityView;
- (void)pptTest_openMultiCityView;
- (void)pptTest_flipWidget;
- (_Bool)isTallDevice;
- (void)pptTest_toggleCity;
- (_Bool)showProgressIndicator;
- (void)significantTimeChange;
- (void)applicationWillEnterForeground:(id)arg1;
- (id)controller;
- (void)resetLocale;
- (void)prepareForDefaultImageSnapshotForScreen:(id)arg1;
- (void)ubiquitousDefaultsDidChange:(id)arg1;
- (void)userDefaultsDidChange:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (id)_keyValueDictionaryForURL:(id)arg1;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(id)arg2;
- (void)applicationSignificantTimeChange:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidEndResumeAnimation;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidResumeForEventsOnly;
- (void)applicationWillSuspendForEventsOnly;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)dealloc;
- (id)init;
- (void)setLocationTrackingEnabled:(_Bool)arg1;

@end

