/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol BacksideControllerDelegate
- (void)celsiusPressedFromBacksideController:(id)arg1;
- (void)donePressedFromBacksideController:(id)arg1;
- (void)addCity:(id)arg1;
- (id)cities;
@end

