/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView;

@interface HourlyForecastCell : UIView
{
    _Bool _showingDay;
    long long _conditionCode;
    UIImageView *_timeImageView;
    UIImageView *_detailImageView;
    UIImageView *_percentChanceImageView;
    UIImageView *_conditionImageView;
}

+ (struct CGSize)size;
@property(retain, nonatomic) UIImageView *conditionImageView; // @synthesize conditionImageView=_conditionImageView;
@property(retain, nonatomic) UIImageView *percentChanceImageView; // @synthesize percentChanceImageView=_percentChanceImageView;
@property(retain, nonatomic) UIImageView *detailImageView; // @synthesize detailImageView=_detailImageView;
@property(retain, nonatomic) UIImageView *timeImageView; // @synthesize timeImageView=_timeImageView;
@property(nonatomic) long long conditionCode; // @synthesize conditionCode=_conditionCode;
@property(nonatomic) _Bool showingDay; // @synthesize showingDay=_showingDay;
- (void)layoutSubviews;
- (void)setImage:(id)arg1;
- (void)setTime:(id)arg1;
- (void)setDetail:(id)arg1 bold:(_Bool)arg2;
- (void)setPrecipitation:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)clearCellContent;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

