/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface HourlyForecastImageFactory : NSObject
{
    _Bool isDay;
    NSArray *_hourlyForecasts;
    int _sunsetTime;
    int _sunriseTime;
    _Bool _isDay;
    _Bool _isHourlyDataCelsius;
}

@property(nonatomic) int sunriseTime; // @synthesize sunriseTime=_sunriseTime;
@property(nonatomic) int sunsetTime; // @synthesize sunsetTime=_sunsetTime;
@property(nonatomic) _Bool isHourlyDataCelsius; // @synthesize isHourlyDataCelsius=_isHourlyDataCelsius;
@property(retain, nonatomic) NSArray *hourlyForecasts; // @synthesize hourlyForecasts=_hourlyForecasts;
@property(nonatomic) _Bool isDay; // @synthesize isDay=_isDay;
- (id)forecastImages;
- (void)dealloc;

@end

