/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol HourlyScrollerBeltDelegate <NSObject>
- (void)didEndScrolling;
- (void)didBeginScrolling;
- (unsigned long long)observationTime;
- (unsigned long long)sunsetTime;
- (unsigned long long)sunriseTime;
- (_Bool)isDay;
- (_Bool)isCelsius;
- (id)hourlyForecasts;
- (long long)numberOfHours;
- (long long)currentCondition;
- (long long)currentHourIndex;
- (id)currentTemperature;
@end

