/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIAnimation.h"

@class TabController;

@interface WAAnimation : UIAnimation
{
    double _w0;
    double _zeta;
    double _wd;
    double _A;
    double _B;
    TabController *_tabController;
    double _animationDuration;
}

@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) TabController *tabController; // @synthesize tabController=_tabController;
- (float)progressForFraction:(float)arg1;
- (float)eval:(float)arg1;
- (void)setProgress:(float)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1;

@end

