/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "WACityPickerViewController.h"

@interface WACityPickerViewController (Internal)
- (void)_showSpinner;
- (void)_hideSpinner;
- (void)_setHideSpinnerTimer:(id)arg1;
- (void)_setLoadingData:(_Bool)arg1;
- (void)_setIsValidatingLocation:(_Bool)arg1;
- (void)_updateCompletionTablePlacehoder;
- (void)_updatePlaceholderLabel;
- (void)_hideCompletions;
- (void)_showCompletions;
- (void)_validateLocation;
- (void)_cancelValidation;
- (void)_scheduleValidation;
- (void)_searchFieldTextDidChange:(id)arg1;
@end

