/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WeatherValidatorDelegate.h"

@class NSArray, NSTimer, UILabel, UISearchBar, UITableView;

@interface WACityPickerViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, WeatherValidatorDelegate>
{
    UITableView *_completionTable;
    UILabel *_tablePlaceholderLabel;
    UISearchBar *_searchField;
    NSTimer *_validationTimer;
    NSTimer *_hideSpinnerTimer;
    NSArray *_validatedLocations;
    int _loadingCount;
    _Bool _isValidatingLocation;
    _Bool _isShowing;
    _Bool _networkReachable;
    _Bool _keyboardShowing;
    _Bool _progressShowing;
    id _delegate;
}

@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)setNetworkReachable:(_Bool)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)didFailWithError:(id)arg1;
- (void)didValidateLocation:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)cancel;
- (void)viewDidLayoutSubviews;
- (void)_setValidatedLocations:(id)arg1 updateStatus:(_Bool)arg2;
- (void)_automaticKeyboardDidHide:(id)arg1;
- (void)_automaticKeyboardWillShow:(id)arg1;
- (_Bool)isLoading;
- (void)willHide;
- (void)didShow;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

@end

