/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionViewTransitionLayout.h"

@class NSIndexPath;

@interface WACollectionViewTransitionLayout : UICollectionViewTransitionLayout
{
    NSIndexPath *_pivotIndexPath;
    unsigned long long _transitionMode;
    struct CGPoint _initialOffsetPoint;
}

@property(nonatomic) unsigned long long transitionMode; // @synthesize transitionMode=_transitionMode;
@property(nonatomic) struct CGPoint initialOffsetPoint; // @synthesize initialOffsetPoint=_initialOffsetPoint;
@property(retain, nonatomic) NSIndexPath *pivotIndexPath; // @synthesize pivotIndexPath=_pivotIndexPath;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;

@end

