/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView;

@interface WADayForecastView : UIView
{
    unsigned long long _weekdayIndex;
    _Bool _isDataCelsius;
    UIImageView *_dayNameImage;
    UIImageView *_highTempImage;
    UIImageView *_lowTempImage;
    UIImageView *_conditionImage;
    double _rightColumnWidth;
    struct CGPoint _conditionImageOffset;
}

@property(nonatomic) double rightColumnWidth; // @synthesize rightColumnWidth=_rightColumnWidth;
@property(nonatomic) struct CGPoint conditionImageOffset; // @synthesize conditionImageOffset=_conditionImageOffset;
@property(retain, nonatomic) UIImageView *conditionImage; // @synthesize conditionImage=_conditionImage;
@property(retain, nonatomic) UIImageView *lowTempImage; // @synthesize lowTempImage=_lowTempImage;
@property(retain, nonatomic) UIImageView *highTempImage; // @synthesize highTempImage=_highTempImage;
@property(retain, nonatomic) UIImageView *dayNameImage; // @synthesize dayNameImage=_dayNameImage;
@property(nonatomic, setter=setDataIsCelsius:) _Bool isDataCelsius; // @synthesize isDataCelsius=_isDataCelsius;
- (void)setDayForecast:(id)arg1;
- (double)desiredRightColumnWidth;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

