/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class CALayer, NSCache, NSNumber, WAGradientLayer, WAWeatherCondition;

@interface WADynamicWeatherBackground : UIView
{
    WAWeatherCondition *_condition;
    NSNumber *_sunHeightOverride;
    CALayer *_rootLayer;
    WAGradientLayer *_gradientLayer;
    NSCache *_backgroundCache;
    long long _graphicQuality;
    CALayer *_currentBackground;
    CALayer *_transitionBackground;
}

+ (void)endReuseRestriction;
+ (void)beginReuseRestrictionForCity:(id)arg1;
+ (void)enqueueBackground:(id)arg1;
+ (id)dequeueBackgroundForCity:(id)arg1;
+ (void)initialize;
@property(nonatomic) CALayer *transitionBackground; // @synthesize transitionBackground=_transitionBackground;
@property(nonatomic) CALayer *currentBackground; // @synthesize currentBackground=_currentBackground;
@property(nonatomic) long long graphicQuality; // @synthesize graphicQuality=_graphicQuality;
@property(retain, nonatomic) NSCache *backgroundCache; // @synthesize backgroundCache=_backgroundCache;
@property(retain, nonatomic) WAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(nonatomic) CALayer *rootLayer; // @synthesize rootLayer=_rootLayer;
@property(copy, nonatomic) NSNumber *sunHeightOverride; // @synthesize sunHeightOverride=_sunHeightOverride;
@property(retain, nonatomic) WAWeatherCondition *condition; // @synthesize condition=_condition;
- (_Bool)hasSublayer:(id)arg1;
- (void)addSublayer:(id)arg1;
- (id)springAnimationForKeyPath:(id)arg1 mass:(double)arg2 fromValue:(id)arg3 toValue:(id)arg4;
- (void)completeTransitionWithSuccess:(_Bool)arg1;
- (id)updateFromCity:(id)arg1 toCity:(id)arg2;
- (void)setCity:(id)arg1;
- (void)getTopColor:(id *)arg1 middleColor:(id *)arg2 bottomColor:(id *)arg3 gradientStopPoint:(double *)arg4 forCity:(id)arg5 date:(id)arg6;
- (id)imageLayerFromConditon:(long long)arg1 isDay:(_Bool)arg2;
- (CDStruct_9b5b21f5)mixedGradientForSunheight:(double)arg1 hourAngle:(double)arg2 condition:(long long)arg3 latitude:(float)arg4;
- (CDStruct_818bb265)mixedColorsForIndex:(long long)arg1 solarHeight:(float)arg2 condition:(long long)arg3 latitude:(float)arg4;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

