/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class WADynamicWeatherBackground, WAWeatherCityView;

@interface WAPlaceholderCell : UIView
{
    WADynamicWeatherBackground *_backgroundView;
    WAWeatherCityView *_cityView;
}

@property(retain, nonatomic) WAWeatherCityView *cityView; // @synthesize cityView=_cityView;
@property(retain, nonatomic) WADynamicWeatherBackground *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)setParallaxOffset:(double)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

