/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "WACardLayout.h"

@class NSIndexPath;

@interface WATransitionCardLayout : WACardLayout
{
    double _pivotHeight;
    NSIndexPath *_pivotIndexPath;
}

@property(retain, nonatomic) NSIndexPath *pivotIndexPath; // @synthesize pivotIndexPath=_pivotIndexPath;
- (struct CGRect)frameForItem:(long long)arg1;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;
- (void)prepareLayout;
- (void)dealloc;

@end

