/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSObject<OS_dispatch_source>, UIImageView, WADynamicWeatherBackground, WADynamicWeatherBackgroundInteractiveTransaction, WAWeatherCondition;

@interface WAWeatherConditionBackgroundView : UIView
{
    long long _activeIndex;
    WADynamicWeatherBackground *_background;
    double _scrollOffset;
    NSArray *_cities;
    WADynamicWeatherBackgroundInteractiveTransaction *_crossfadeTransaction;
    NSObject<OS_dispatch_source> *_crossfadeEffectTimer;
    UIImageView *_introductionImageView;
    WAWeatherCondition *_leftCondition;
    WAWeatherCondition *_rightCondition;
}

@property(retain, nonatomic) WAWeatherCondition *rightCondition; // @synthesize rightCondition=_rightCondition;
@property(retain, nonatomic) WAWeatherCondition *leftCondition; // @synthesize leftCondition=_leftCondition;
@property(retain, nonatomic) UIImageView *introductionImageView; // @synthesize introductionImageView=_introductionImageView;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *crossfadeEffectTimer; // @synthesize crossfadeEffectTimer=_crossfadeEffectTimer;
@property(retain, nonatomic) WADynamicWeatherBackgroundInteractiveTransaction *crossfadeTransaction; // @synthesize crossfadeTransaction=_crossfadeTransaction;
@property(retain, nonatomic) NSArray *cities; // @synthesize cities=_cities;
@property(nonatomic) double scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(readonly, nonatomic) WADynamicWeatherBackground *background; // @synthesize background=_background;
- (void)saveImageForKeyCondition;
- (void)prepareToResume;
- (void)prepareToSuspend;
- (void)useConditionView:(id)arg1 activeCityIndex:(unsigned long long)arg2;
- (id)relinquishConditionViewForCityAtIndex:(long long)arg1;
- (void)_addBackAllLayers;
- (void)_removeSideLayers;
- (void)pauseOffscreenConditions;
- (void)refreshConditions;
- (void)setScrollEnded;
- (void)updateConditionsAboutCityIndex:(long long)arg1;
- (void)setCities:(id)arg1 activeCityIndex:(long long)arg2 activeCityLiveConditionOnly:(_Bool)arg3 animationDuration:(double)arg4;
- (void)setCities:(id)arg1 activeCityIndex:(long long)arg2 animationDuration:(double)arg3;
- (void)setCities:(id)arg1 activeCityIndex:(long long)arg2;
- (void)_cityDidUpdate:(id)arg1;
- (void)dealloc;
- (void)_setCondition:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)_conditionAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) NSArray *conditions;
- (id)_conditions;
- (id)initWithFrame:(struct CGRect)arg1;

@end

