/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "WeatherView.h"

#import "HourlyScrollerBeltDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class HourlyScrollerBeltView, NSDateFormatter, NSMutableArray, UILabel, UITapGestureRecognizer, UIView, WAWeatherCardView;

@interface WAWeatherCityView : WeatherView <HourlyScrollerBeltDelegate, UIGestureRecognizerDelegate>
{
    double _panOffset;
    _Bool _isTallCell;
    _Bool _showsExpanedDetail;
    _Bool _isTallDevice;
    long long _mode;
    double _transitionProgress;
    WAWeatherCardView *_cardView;
    UIView *_cardMaskView;
    UIView *_pageView;
    UIView *_pageUpperView;
    UIView *_pageBottomView;
    UILabel *_pageCityName;
    UILabel *_pageConditionDescription;
    UILabel *_pageTemperature;
    UILabel *_pageDayName;
    UILabel *_pageDayDescription;
    UILabel *_pageHighTemperature;
    UILabel *_pageLowTemperature;
    UITapGestureRecognizer *_detailedConditionsRecognizer;
    UILabel *_humidityTitle;
    UILabel *_humidity;
    UILabel *_chanceOfRainTitle;
    UILabel *_chanceOfRain;
    UILabel *_windTitle;
    UILabel *_windDirection;
    UILabel *_wind;
    UILabel *_otherConditionIndexTitle;
    UILabel *_otherConditionIndex;
    UIView *_textTreatmentView;
    HourlyScrollerBeltView *_hourlyBelt;
    NSMutableArray *_dayForecastViews;
    long long _graphicQuality;
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) long long graphicQuality; // @synthesize graphicQuality=_graphicQuality;
@property(nonatomic) _Bool isTallDevice; // @synthesize isTallDevice=_isTallDevice;
@property(retain, nonatomic) NSMutableArray *dayForecastViews; // @synthesize dayForecastViews=_dayForecastViews;
@property(retain, nonatomic) HourlyScrollerBeltView *hourlyBelt; // @synthesize hourlyBelt=_hourlyBelt;
@property(retain, nonatomic) UIView *textTreatmentView; // @synthesize textTreatmentView=_textTreatmentView;
@property(retain, nonatomic) UILabel *otherConditionIndex; // @synthesize otherConditionIndex=_otherConditionIndex;
@property(retain, nonatomic) UILabel *otherConditionIndexTitle; // @synthesize otherConditionIndexTitle=_otherConditionIndexTitle;
@property(retain, nonatomic) UILabel *wind; // @synthesize wind=_wind;
@property(retain, nonatomic) UILabel *windDirection; // @synthesize windDirection=_windDirection;
@property(retain, nonatomic) UILabel *windTitle; // @synthesize windTitle=_windTitle;
@property(retain, nonatomic) UILabel *chanceOfRain; // @synthesize chanceOfRain=_chanceOfRain;
@property(retain, nonatomic) UILabel *chanceOfRainTitle; // @synthesize chanceOfRainTitle=_chanceOfRainTitle;
@property(retain, nonatomic) UILabel *humidity; // @synthesize humidity=_humidity;
@property(retain, nonatomic) UILabel *humidityTitle; // @synthesize humidityTitle=_humidityTitle;
@property(nonatomic) _Bool showsExpanedDetail; // @synthesize showsExpanedDetail=_showsExpanedDetail;
@property(retain, nonatomic) UITapGestureRecognizer *detailedConditionsRecognizer; // @synthesize detailedConditionsRecognizer=_detailedConditionsRecognizer;
@property(retain, nonatomic) UILabel *pageLowTemperature; // @synthesize pageLowTemperature=_pageLowTemperature;
@property(retain, nonatomic) UILabel *pageHighTemperature; // @synthesize pageHighTemperature=_pageHighTemperature;
@property(retain, nonatomic) UILabel *pageDayDescription; // @synthesize pageDayDescription=_pageDayDescription;
@property(retain, nonatomic) UILabel *pageDayName; // @synthesize pageDayName=_pageDayName;
@property(retain, nonatomic) UILabel *pageTemperature; // @synthesize pageTemperature=_pageTemperature;
@property(retain, nonatomic) UILabel *pageConditionDescription; // @synthesize pageConditionDescription=_pageConditionDescription;
@property(retain, nonatomic) UILabel *pageCityName; // @synthesize pageCityName=_pageCityName;
@property(retain, nonatomic) UIView *pageBottomView; // @synthesize pageBottomView=_pageBottomView;
@property(retain, nonatomic) UIView *pageUpperView; // @synthesize pageUpperView=_pageUpperView;
@property(retain, nonatomic) UIView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) UIView *cardMaskView; // @synthesize cardMaskView=_cardMaskView;
@property(retain, nonatomic) WAWeatherCardView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) _Bool isTallCell; // @synthesize isTallCell=_isTallCell;
@property(nonatomic) double transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (long long)currentCondition;
- (long long)currentHourIndex;
- (id)currentTemperature;
- (void)didEndScrolling;
- (void)didBeginScrolling;
- (_Bool)isDay;
- (_Bool)isCelsius;
- (id)hourlyForecasts;
- (long long)numberOfHours;
- (unsigned long long)observationTime;
- (unsigned long long)sunsetTime;
- (unsigned long long)sunriseTime;
- (void)refreshLocalization;
- (void)cityDidStartWeatherUpdate:(id)arg1;
- (_Bool)updateWeatherDisplayForCity:(id)arg1;
- (void)setPanOffset:(double)arg1;
- (void)setStaggerOffset:(double)arg1;
- (void)layoutSubviews;
- (void)prepareForResuse;
- (void)tappedCity:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)toggleExtended;
- (void)setWindWithSpeed:(double)arg1;
- (id)cardinalDirectionStringForIndex:(int)arg1;
- (_Bool)isLongStringLanguage;
- (void)_forceWeatherDescription:(id)arg1;
- (void)updateUI:(_Bool)arg1;
- (void)updateTimeUI;
- (void)showCity:(id)arg1;
- (void)cleanupTextTreatmentView;
- (id)newTextTreatmentViewForCondition:(long long)arg1;
- (void)_removePageModeViews;
- (void)_createPageModeViews;
- (void)_removeCardModeViews;
- (void)_createCardModeViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

