/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionReusableView.h"

@class UIButton, UIImageView, WATouchButton, WAUnitSelectionControl;

@interface WAWeatherCollectionFooterViewCell : UICollectionReusableView
{
    id <WAWeatherCollectionFooterViewCellDelegate> _delegate;
    WATouchButton *_addButton;
    WAUnitSelectionControl *_unitControl;
    UIButton *_theWeatherChannelButton;
    UIButton *_yahooButton;
    UIImageView *_topKeyline;
}

@property(retain, nonatomic) UIImageView *topKeyline; // @synthesize topKeyline=_topKeyline;
@property(retain, nonatomic) UIButton *yahooButton; // @synthesize yahooButton=_yahooButton;
@property(retain, nonatomic) UIButton *theWeatherChannelButton; // @synthesize theWeatherChannelButton=_theWeatherChannelButton;
@property(retain, nonatomic) WAUnitSelectionControl *unitControl; // @synthesize unitControl=_unitControl;
@property(retain, nonatomic) WATouchButton *addButton; // @synthesize addButton=_addButton;
@property(nonatomic) id <WAWeatherCollectionFooterViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_showAddSheet:(id)arg1;
- (void)_selectedSegmentChanged:(id)arg1;
- (void)_yahooLogoTapped:(id)arg1;
- (void)_twcLogoTapped:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)_updateUnitControl;
- (id)generatekeyline;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

