/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionViewCell.h"

#import "CityUpdaterDelegate.h"

@class City, NSArray, UIButton, WADynamicWeatherBackground, WAWeatherCityView;

@interface WAWeatherCollectionViewCell : UICollectionViewCell <CityUpdaterDelegate>
{
    double _buttonWidth;
    _Bool _isTallCell;
    _Bool _showingDeleteUI;
    City *_city;
    long long _mode;
    double _transitionProgress;
    UIButton *_deleteButton;
    id <WAWeatherCollectionViewCellDelegate> _delegate;
    id <WAWeatherCollectionViewCellLayoutDelegate> _layoutDelegate;
    WADynamicWeatherBackground *_background;
    NSArray *_extraViews;
    WAWeatherCityView *_cityView;
    double _deleteSliderOffset;
}

@property(nonatomic) double deleteSliderOffset; // @synthesize deleteSliderOffset=_deleteSliderOffset;
@property(readonly, nonatomic) WAWeatherCityView *cityView; // @synthesize cityView=_cityView;
@property(retain, nonatomic) NSArray *extraViews; // @synthesize extraViews=_extraViews;
@property(retain, nonatomic) WADynamicWeatherBackground *background; // @synthesize background=_background;
@property(nonatomic) id <WAWeatherCollectionViewCellLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) id <WAWeatherCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(readonly, nonatomic, getter=isShowingDeleteUI) _Bool showingDeleteUI; // @synthesize showingDeleteUI=_showingDeleteUI;
@property(nonatomic) _Bool isTallCell; // @synthesize isTallCell=_isTallCell;
@property(nonatomic) double transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(readonly, nonatomic) long long mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) City *city; // @synthesize city=_city;
- (void)setParallaxOffset:(double)arg1 isTransitionOffset:(_Bool)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)applyLayoutAttributes:(id)arg1;
- (void)useBackgroundView:(id)arg1;
- (void)delete:(id)arg1;
- (void)_layoutForShowingDeleteUI:(_Bool)arg1;
- (void)showDeleteUI:(_Bool)arg1 animated:(_Bool)arg2;
- (void)swipeByOffset:(double)arg1;
- (void)beginTracking;
- (void)refreshForUnitsChange;
- (void)setCity:(id)arg1 andMode:(long long)arg2;
- (void)cityDidStartWeatherUpdate:(id)arg1;
- (void)cityDidFinishWeatherUpdate:(id)arg1;
- (void)_updateBackgroundCondition;
- (void)prepareForReuse;
- (void)dealloc;
- (void)useCityView:(id)arg1;
- (id)relinquishCityView;
- (id)relinquishBackground;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_createCityView;
- (void)_createBackground;

@end

