/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "TabControllerDelegate.h"
#import "WeatherUpdaterDelegate.h"

@class NSTimer, TabController, UIView;

@interface WeatherController : NSObject <TabControllerDelegate, WeatherUpdaterDelegate>
{
    TabController *_tabController;
    NSTimer *_updateTimer;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)failedUpdate:(id)arg1;
- (void)refreshForLocaleChange;
- (void)resume;
- (void)suspend;
- (void)didUpdateWeather;
- (void)_startUpdateTimer;
- (void)_updateWeatherData;
- (void)saveStateToDisk;
- (void)tabControllerWillScroll:(id)arg1;
- (id)tabController;
- (void)dealloc;
- (void)_stopUpdateTimer;
- (id)init;
- (void)_reachabilityChanged:(id)arg1;
- (struct CGRect)_contentLayerRect;

@end

