/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIPanGestureRecognizer.h"

@class UITouch;

@interface WeatherPanGestureRecognizer : UIPanGestureRecognizer
{
    struct CGPoint _startPoint;
    _Bool _isTracking;
    float _maximumStartPoint;
    id <WeatherPanGestureRecognizerDelegate> _weatherPanDelegate;
    UITouch *_trackingTouch;
}

@property(nonatomic) float maximumStartPoint; // @synthesize maximumStartPoint=_maximumStartPoint;
@property(nonatomic) id <WeatherPanGestureRecognizerDelegate> weatherPanDelegate; // @synthesize weatherPanDelegate=_weatherPanDelegate;
- (void)reset;
- (_Bool)canBePreventedByGestureRecognizer:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)init;

@end

