/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CLVisit.h"

@interface CLVisit (RTExtensions)
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithOneVisit:(id)arg1;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3 arrivalDate:(id)arg4 departureDate:(id)arg5;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3 arrivalDate:(id)arg4;
- (id)initWithLocation:(id)arg1 arrivalDate:(id)arg2 departureDate:(id)arg3;
- (id)initWithLocation:(id)arg1 arrivalDate:(id)arg2;
@end

