/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "GEOMapItemStorage.h"

@interface GEOMapItemStorage (RTExtensions)
+ (id)mapItemStorageForGEOMapItem:(id)arg1 locationOfInterestType:(long long)arg2;
+ (id)mapItemStorageForPlace:(id)arg1 locationOfInterestType:(long long)arg2;
@end

