/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface RTAddressBook : NSObject
{
    void *_addressBook;
    NSArray *_meCards;
}

+ (id)entryTypeToString:(long long)arg1;
@property(retain, nonatomic) NSArray *meCards; // @synthesize meCards=_meCards;
- (void).cxx_destruct;
- (void)fetchMeCardMapItemsOfType:(long long)arg1 withHandler:(id)arg2;
- (id)getMeCardLocationsOfType:(long long)arg1;
- (id)getMeCardAddressDictionariesOfType:(long long)arg1;
- (void)dealloc;
- (id)init;

@end

