/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

@interface RTAuthorizationManager : RTNotifier
{
    _Bool _supported;
    _Bool _enabled;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool supported; // @synthesize supported=_supported;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)handleAppResetChangeNotification;
- (void)updateRoutineEnabled:(_Bool)arg1;
- (void)setRoutineEnabled:(_Bool)arg1;
- (void)fetchRoutineSupportedWithHandler:(id)arg1;
- (void)fetchBBPluginSupportedWithHandler:(id)arg1;
- (void)fetchRoutineEnabledWithHandler:(id)arg1;
- (_Bool)isCoreRoutineLocationClientEnabled;
- (_Bool)isLocationServicesEnabled;
- (void)dealloc;
- (id)init;

@end

