/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

@interface RTBatteryManager : RTNotifier
{
    unsigned int _battery;
    struct IONotificationPort *_ioNotificationPort;
    unsigned int _batteryInterestNotification;
    _Bool _monitorBatteryStatusChanges;
    long long _externalConnectedState;
}

+ (id)externalConnectedStateToString:(long long)arg1;
+ (id)sharedInstance;
@property(nonatomic) long long externalConnectedState; // @synthesize externalConnectedState=_externalConnectedState;
@property(nonatomic) _Bool monitorBatteryStatusChanges; // @synthesize monitorBatteryStatusChanges=_monitorBatteryStatusChanges;
- (void)batteryStatusChange:(unsigned int)arg1 messageType:(unsigned int)arg2 messageArgument:(void *)arg3;
- (void)updateBatteryStatus:(unsigned int)arg1;
- (void)matchedBattery:(unsigned int)arg1;
- (void)stopMonitoringBatteryStatusChanges;
- (void)startMonitoringBatteryStatusChanges;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)dealloc;
- (id)init;

@end

