/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotification.h"

@interface RTBatteryManagerChargerConnectedNotification : RTNotification
{
    _Bool _connected;
}

+ (id)notificationName;
@property(readonly, nonatomic) _Bool connected; // @synthesize connected=_connected;
- (id)initWithChargerConnected:(_Bool)arg1;

@end

