/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "BBRemoteDataProvider.h"

@class BBBulletinRequest, BBDataProviderProxy, GEOQuickETARequester, NSObject<OS_dispatch_queue>, NSString, RTPLOIETA;

@interface RTBBDataProvider : NSObject <BBRemoteDataProvider>
{
    NSObject<OS_dispatch_queue> *_queue;
    GEOQuickETARequester *_etaRequester;
    BBDataProviderProxy *_dataProviderProxy;
    BBBulletinRequest *_currentBulletinRequest;
    RTPLOIETA *_currentPLOIETA;
    id <GEOMapItem> _lastOriginGEOMapItem;
}

- (void).cxx_destruct;
- (id)sectionIcon;
- (id)defaultSectionInfo;
- (id)sortDescriptors;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (id)sectionDisplayName;
- (id)sectionIdentifier;
- (void)_coreroutine_bulletinBoardDidPresent;
- (void)_displayBulletinForLocation:(id)arg1;
- (void)_displayBulletinFromOrigin:(id)arg1 originGEOMapItem:(id)arg2 toPloi:(id)arg3;
- (void)_displayBulletinForPLOIETA:(id)arg1;
- (void)_removeCurrentBulletin;
- (void)setDataProviderProxy:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

