/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

@class BluetoothManager, NSSet;

@interface RTBluetoothManager : RTNotifier
{
    _Bool _observingConnections;
    BluetoothManager *_bluetoothManager;
    NSSet *_connectedDevices;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool observingConnections; // @synthesize observingConnections=_observingConnections;
@property(retain, nonatomic) NSSet *connectedDevices; // @synthesize connectedDevices=_connectedDevices;
@property(retain, nonatomic) BluetoothManager *bluetoothManager; // @synthesize bluetoothManager=_bluetoothManager;
- (void).cxx_destruct;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)shouldObserveConnections;
- (void)updateConnections;
- (void)dealloc;
- (id)init;

@end

