/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotification.h"

@class NSString;

@interface RTBluetoothManagerConnectionNotification : RTNotification
{
    NSString *_deviceName;
    NSString *_deviceAddress;
}

+ (id)notificationName;
@property(retain, nonatomic) NSString *deviceAddress; // @synthesize deviceAddress=_deviceAddress;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
- (void).cxx_destruct;
- (id)initWithDeviceName:(id)arg1 andDeviceAddress:(id)arg2;

@end

