/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class BBDataProviderConnection, NSObject<OS_dispatch_queue>;

@interface RTBulletinBoardManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    BBDataProviderConnection *_dataProviderConnection;
}

+ (id)sharedInstance;
@property(retain, nonatomic) BBDataProviderConnection *dataProviderConnection; // @synthesize dataProviderConnection=_dataProviderConnection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

