/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotification.h"

@interface RTDataProtectionManagerEncryptedDataAvailabilityNotification : RTNotification
{
    long long _availability;
}

+ (id)notificationName;
@property(nonatomic) long long availability; // @synthesize availability=_availability;
- (id)initWithEncryptedDataAvailability:(long long)arg1;

@end

