/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotification.h"

@interface RTDataProtectionManagerUnlockedSinceBootNotification : RTNotification
{
    _Bool _unlockedSinceBoot;
}

+ (id)notificationName;
@property(nonatomic) _Bool unlockedSinceBoot; // @synthesize unlockedSinceBoot=_unlockedSinceBoot;
- (id)initWithUnlockedSinceBoot:(_Bool)arg1;

@end

