/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "RTDaemonProtocol.h"

@class NSObject<OS_dispatch_queue>, NSString, NSXPCConnection;

@interface RTDaemonClient : NSObject <RTDaemonProtocol>
{
    _Bool _monitorVisits;
    _Bool _enabled;
    _Bool _supported;
    int _pid;
    NSXPCConnection *_xpcConnection;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_executablePath;
}

@property(nonatomic) _Bool supported; // @synthesize supported=_supported;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool monitorVisits; // @synthesize monitorVisits=_monitorVisits;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
@property(readonly, nonatomic) NSString *executablePath; // @synthesize executablePath=_executablePath;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (void).cxx_destruct;
- (void)shutdown;
- (void)onRoutineEnabled:(id)arg1;
- (void)fetchPathToDiagnosticFilesWithReply:(id)arg1;
- (void)onDeviceLocationPredictorNotification:(id)arg1;
- (void)stopMonitoringVisits;
- (void)startMonitoringVisits;
- (void)fetchPredictedLocationsOfInterestOnDate:(id)arg1 withReply:(id)arg2;
- (void)fetchLocationsOfInterestAssociatedToIdentifier:(id)arg1 withReply:(id)arg2;
- (void)fetchRoutineModeFromLocation:(id)arg1 withReply:(id)arg2;
- (void)fetchPredictedConditionsForAction:(id)arg1 withReply:(id)arg2;
- (void)clearRoutine;
- (void)setRoutineEnabled:(_Bool)arg1;
- (void)fetchBBPluginSupportedWithReply:(id)arg1;
- (void)fetchRoutineEnabledWithReply:(id)arg1;
- (void)fetchPredictedLocationsOfInterestFromStartingLocationOfInterest:(id)arg1 withReply:(id)arg2;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withReply:(id)arg4;
- (void)fetchAllLocationsOfInterestWithReply:(id)arg1;
- (void)fetchLocationsOfInterestOfType:(long long)arg1 withReply:(id)arg2;
- (void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(id)arg2 withReply:(id)arg3;
- (_Bool)hasEntitlement:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithConnection:(id)arg1 andQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

