/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotification.h"

@class CLVisit;

@interface RTDeviceLocationPredictorVisitNotification : RTNotification
{
    CLVisit *_visit;
}

+ (id)notificationName;
@property(retain, nonatomic) CLVisit *visit; // @synthesize visit=_visit;
- (void).cxx_destruct;
- (id)initWithVisit:(id)arg1;

@end

