/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

#import "RTStateModelDelegate.h"

@class NSMutableArray, NSString, RTStateModel;

@interface RTDeviceLocationPredictor : RTNotifier <RTStateModelDelegate>
{
    _Bool _monitorVisits;
    RTStateModel *_stateModel;
    NSMutableArray *_pendingStateModelInvocations;
}

+ (id)sequentialClusterIdentificationIdentifier;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *pendingStateModelInvocations; // @synthesize pendingStateModelInvocations=_pendingStateModelInvocations;
@property(nonatomic) _Bool monitorVisits; // @synthesize monitorVisits=_monitorVisits;
@property(retain, nonatomic) RTStateModel *stateModel; // @synthesize stateModel=_stateModel;
- (void).cxx_destruct;
- (void)onPurgeNotification:(id)arg1;
- (void)onLocationsOfInterestUpdated;
- (void)onVisit:(id)arg1 withError:(id)arg2;
- (void)stopMonitoringVisits;
- (void)startMonitoringVisits;
- (void)shouldMonitorVisits;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)fetchLocationOfInterestAtLocation:(id)arg1 withHandler:(id)arg2;
- (void)removeLocationOfInterest:(id)arg1;
- (void)injectLocationOfInterest:(id)arg1;
- (void)fetchPredictedLocationsOfInterestOnDate:(id)arg1 withHandler:(id)arg2;
- (void)fetchRoutineModeFromLocation:(id)arg1 withHandler:(id)arg2;
- (void)fetchPredictedLocationsOfInterestFromStartingLocationOfInterest:(id)arg1 withHandler:(id)arg2;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(id)arg4;
- (void)_fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(id)arg4;
- (void)fetchAllLocationsOfInterestWithHandler:(id)arg1;
- (void)fetchLocationsOfInterestOfType:(long long)arg1 withHandler:(id)arg2;
- (void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(id)arg2 withHandler:(id)arg3;
- (void)purge;
- (void)_purge;
- (void)sequentialClusterIdentification;
- (void)_sequentialClusterIdentification;
- (void)clear;
- (void)_clear;
- (void)onEncryptedDataAvailabilityNotification:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

