/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class EKEventStore, NSObject<OS_dispatch_queue>;

@interface RTEventManager : NSObject
{
    _Bool _accessToEventsGranted;
    EKEventStore *_eventStore;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (_Bool)reasonableDistanceBetweenEventLocation:(id)arg1 andLocation:(id)arg2;
+ (id)sharedInstance;
@property(nonatomic) _Bool accessToEventsGranted; // @synthesize accessToEventsGranted=_accessToEventsGranted;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) EKEventStore *eventStore; // @synthesize eventStore=_eventStore;
- (void).cxx_destruct;
- (void)fetchPredictedLocationsOfInterestOnDate:(id)arg1 withHandler:(id)arg2;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(id)arg4;
- (void)fetchEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 withHandler:(id)arg3;
- (void)fetchLastEventEndDateWithHandler:(id)arg1;
- (void)fetchNextFreeStartDateWithHandler:(id)arg1;
- (void)fetchCurrentlyInEventWithHandler:(id)arg1;
- (id)getEventsSortedByStartDateBetweenStartDate:(id)arg1 andEndDate:(id)arg2;
- (id)getEventsSortedByEndDateBetweenStartDate:(id)arg1 andEndDate:(id)arg2;
- (id)getEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2;
- (id)getEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 calendars:(id)arg3;
- (id)getError;
- (id)init;

@end

