/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface RTEventLocationIdentifier : NSObject <NSCopying>
{
    NSString *_name;
}

@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)toLowerCase;
- (long long)levenshteinDistanceToIdentifier:(id)arg1;
- (_Bool)isSuitableForFuzzyMatch;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithEvent:(id)arg1;
- (id)initWithName:(id)arg1;

@end

