/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class CLLocation;

@interface RTHint : NSObject
{
    CLLocation *_location;
    long long _source;
}

+ (id)hintSourceToString:(long long)arg1;
@property(nonatomic) long long source; // @synthesize source=_source;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithLocation:(id)arg1 source:(long long)arg2;

@end

