/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface RTHintManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)onNavigationNotification:(id)arg1;
- (void)onBatteryNotification:(id)arg1;
- (void)onPurgeNotification:(id)arg1;
- (void)clearHintsPredating:(id)arg1;
- (void)clearHints;
- (void)fetchIsHintNearLocation:(id)arg1 withHandler:(id)arg2;
- (void)fetchHintsNearLocation:(id)arg1 withHandler:(id)arg2;
- (void)onBluetoothNotification:(id)arg1;
- (void)submitHintFromSource:(long long)arg1;
- (void)dealloc;
- (id)init;

@end

