/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface RTLifeCycleManager : NSObject
{
    _Bool _activeTransaction;
    _Bool _exitWhenNoTransactions;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_signals;
    NSMutableDictionary *_transactions;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool exitWhenNoTransactions; // @synthesize exitWhenNoTransactions=_exitWhenNoTransactions;
@property(nonatomic) _Bool activeTransaction; // @synthesize activeTransaction=_activeTransaction;
@property(retain, nonatomic) NSMutableDictionary *transactions; // @synthesize transactions=_transactions;
@property(retain, nonatomic) NSMutableArray *signals; // @synthesize signals=_signals;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)exit;
- (void)processTransactions;
- (void)decrementTransactionsForObject:(id)arg1;
- (void)incrementTransactionsForObject:(id)arg1;
- (id)keyForObject:(id)arg1;
- (void)start;
- (id)createSourceForSignal:(int)arg1 withBlock:(id)arg2;
- (void)dealloc;
- (id)init;

@end

