/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface RTLogger : NSObject
{
}

+ (void)fetchPathToDiagnosticFilesWithHandler:(id)arg1;
+ (id)diagnosticFiles;
+ (void)flush;
+ (struct __CFString *)newFormattedLogMessage:(int)arg1:(struct __CFDate *)arg2:(struct __CFString *)arg3:(struct __CFString *)arg4:(const char *)arg5:(const char *)arg6:(unsigned long long)arg7:(const char *)arg8:(struct __CFString *)arg9;
+ (id)logFacilities;
+ (id)sharedInstance;
- (void)logHeader;
- (id)init;

@end

