/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, CLLocationManagerRoutine, NSMutableArray, NSObject<OS_dispatch_source>, NSString;

@interface RTLocationManager : RTNotifier <CLLocationManagerDelegate>
{
    int _currentCountrySupportsCoreRoutineToken;
    int _userOptedIntoGEOAddressCorrectionToken;
    _Bool _updating;
    _Bool _leechingLocations;
    _Bool _currentCountrySupportsCoreRoutine;
    _Bool _userOptedIntoGEOAddressCorrection;
    _Bool _persistingLocations;
    _Bool _enabled;
    CLLocationManager *_locationManager;
    CLLocationManagerRoutine *_locationManagerRoutine;
    CLLocation *_lastLocation;
    NSMutableArray *_persistedLocations;
    NSMutableArray *_currentLocationHandlers;
    NSMutableArray *_pendingDbInvocations;
    NSObject<OS_dispatch_source> *_stopUpdatingLocationTimer;
    NSObject<OS_dispatch_source> *_persistLocationsTimer;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool persistingLocations; // @synthesize persistingLocations=_persistingLocations;
@property(nonatomic) _Bool userOptedIntoGEOAddressCorrection; // @synthesize userOptedIntoGEOAddressCorrection=_userOptedIntoGEOAddressCorrection;
@property(nonatomic) _Bool currentCountrySupportsCoreRoutine; // @synthesize currentCountrySupportsCoreRoutine=_currentCountrySupportsCoreRoutine;
@property(nonatomic) _Bool leechingLocations; // @synthesize leechingLocations=_leechingLocations;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *persistLocationsTimer; // @synthesize persistLocationsTimer=_persistLocationsTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *stopUpdatingLocationTimer; // @synthesize stopUpdatingLocationTimer=_stopUpdatingLocationTimer;
@property(retain, nonatomic) NSMutableArray *pendingDbInvocations; // @synthesize pendingDbInvocations=_pendingDbInvocations;
@property(copy, nonatomic) NSMutableArray *currentLocationHandlers; // @synthesize currentLocationHandlers=_currentLocationHandlers;
@property(retain, nonatomic) NSMutableArray *persistedLocations; // @synthesize persistedLocations=_persistedLocations;
@property(retain, nonatomic) CLLocation *lastLocation; // @synthesize lastLocation=_lastLocation;
@property(retain, nonatomic) CLLocationManagerRoutine *locationManagerRoutine; // @synthesize locationManagerRoutine=_locationManagerRoutine;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void).cxx_destruct;
- (void)onRoutineEnabled:(id)arg1;
- (void)onPurgeNotification:(id)arg1;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)persistLocations;
- (void)onStopUpdatingLocationTimerExpiry;
- (void)clearStoredLocationsPredating:(id)arg1;
- (void)clear;
- (void)fetchStoredLocationsAveragedAtInterval:(double)arg1 withHandler:(id)arg2;
- (void)fetchStoredLocationsWithinRangeOfStartDate:(id)arg1 andStopDate:(id)arg2 withHandler:(id)arg3;
- (void)fetchStoredLocationsWithHandler:(id)arg1;
- (void)fetchCurrentLocationWithHandler:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)shouldPersistLocations;
- (void)shouldLeechLocations;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (id)averageLocations:(id)arg1 atInterval:(double)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

