/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class CMMotionActivityManager;

@interface RTMotionActivityManager : NSObject
{
    _Bool _motionActivityAvailable;
    CMMotionActivityManager *_motionActivityManager;
}

+ (id)motionActivityTypeToString:(unsigned long long)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool motionActivityAvailable; // @synthesize motionActivityAvailable=_motionActivityAvailable;
@property(retain, nonatomic) CMMotionActivityManager *motionActivityManager; // @synthesize motionActivityManager=_motionActivityManager;
- (void).cxx_destruct;
- (void)fetchMotionActivitiesFromStartDate:(id)arg1 toEndDate:(id)arg2 withHandler:(id)arg3;
- (id)init;

@end

