/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTPredictedLocationOfInterest.h"

@interface RTPredictedLocationOfInterest (RTStateModel)
- (id)initWithLocationOfInterest:(id)arg1 confidence:(double)arg2 nextEntryTime:(id)arg3 routeUUID:(id)arg4 motionActivityType:(unsigned long long)arg5;
@end

