/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class GEOMapMatchRequest, GEOMapMatchResponse;

@interface RTRouteRequest : NSObject
{
    GEOMapMatchRequest *_mapMatchRequest;
    GEOMapMatchResponse *_mapMatchResponse;
    double _lastAttempt;
    long long _failedAttempts;
    id _completionHandler;
}

@property(copy, nonatomic) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) long long failedAttempts; // @synthesize failedAttempts=_failedAttempts;
@property(nonatomic) double lastAttempt; // @synthesize lastAttempt=_lastAttempt;
@property(retain, nonatomic) GEOMapMatchResponse *mapMatchResponse; // @synthesize mapMatchResponse=_mapMatchResponse;
@property(readonly, retain, nonatomic) GEOMapMatchRequest *mapMatchRequest; // @synthesize mapMatchRequest=_mapMatchRequest;
- (void).cxx_destruct;
- (id)initWithBreadcrumbs:(id)arg1;

@end

