/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface RTRouteManager : NSObject
{
    _Bool _usualRoutesEnabled;
    _Bool _bypassMapMatching;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_routes;
    NSMutableDictionary *_zilch;
    NSMutableArray *_pendingRouteRequests;
    NSMutableArray *_activeRouteRequests;
    long long _maxRouteRequestRetries;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool bypassMapMatching; // @synthesize bypassMapMatching=_bypassMapMatching;
@property(nonatomic) long long maxRouteRequestRetries; // @synthesize maxRouteRequestRetries=_maxRouteRequestRetries;
@property(nonatomic) _Bool usualRoutesEnabled; // @synthesize usualRoutesEnabled=_usualRoutesEnabled;
@property(retain, nonatomic) NSMutableArray *activeRouteRequests; // @synthesize activeRouteRequests=_activeRouteRequests;
@property(retain, nonatomic) NSMutableArray *pendingRouteRequests; // @synthesize pendingRouteRequests=_pendingRouteRequests;
@property(retain, nonatomic) NSMutableDictionary *zilch; // @synthesize zilch=_zilch;
@property(retain, nonatomic) NSMutableDictionary *routes; // @synthesize routes=_routes;
@property(readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)updateRoutes:(id)arg1;
- (void)fetchRoutesWithCompletion:(id)arg1;
- (id)decompressZilchForRoute:(id)arg1;
- (_Bool)matches:(id)arg1 to:(id)arg2;
- (id)findMatchingRouteTo:(id)arg1;
- (void)ingestNewRoute:(id)arg1;
- (void)processBreadcrumbs;
- (void)processRequest:(id)arg1;
- (void)createFakeMapMatch:(id)arg1;
- (void)submitBreadcrumbs:(id)arg1 withCompletion:(id)arg2;
- (void)lookupRouteById:(id)arg1 withCompletion:(id)arg2;
- (void)releaseCaches;
- (id)init;

@end

