/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class RTSqliteDatabase;

@interface RTSqliteTable : NSObject
{
    RTSqliteDatabase *_database;
}

+ (id)TableColumnTimestamp;
@property(readonly, nonatomic) RTSqliteDatabase *database; // @synthesize database=_database;
- (void).cxx_destruct;
- (id)selectAllColumnsFromTable;
- (void)clearEntriesPredating:(id)arg1;
- (void)_clearEntriesPredating:(id)arg1;
- (void)clearEntries;
- (void)_clearEntries;
- (void)fetchEarliestEntryDateWithHandler:(id)arg1;
- (void)_fetchEarliestEntryDateWithHandler:(id)arg1;
- (void)fetchNumberOfEntriesWithHandler:(id)arg1;
- (void)_fetchNumberOfEntriesWithHandler:(id)arg1;
- (id)init;
- (unsigned long long)encryptionClass;
- (id)tableColumns;
- (id)tableName;

@end

