/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface RTSqliteDatabaseManager : NSObject
{
    NSMutableDictionary *_databases;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *databases; // @synthesize databases=_databases;
- (void).cxx_destruct;
- (void)fetchDatabaseForEncryptionClass:(unsigned long long)arg1 withHandler:(id)arg2;
- (id)init;

@end

