/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface RTSqliteTableColumn : NSObject
{
    _Bool _primary;
    NSString *_name;
    long long _type;
}

@property(nonatomic) _Bool primary; // @synthesize primary=_primary;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)typeToString;
- (id)initWithName:(id)arg1 sqliteType:(long long)arg2 isPrimary:(_Bool)arg3;

@end

