/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTSqliteTable.h"

@interface RTSqliteTableHint : RTSqliteTable
{
}

+ (id)sharedInstance;
- (void)fetchHintsNearLocation:(id)arg1 withHandler:(id)arg2;
- (void)_fetchHintsNearLocation:(id)arg1 withHandler:(id)arg2;
- (void)fetchHintsWithHandler:(id)arg1;
- (void)_fetchHintsWithHandler:(id)arg1;
- (id)getHintsWithStatementString:(id)arg1;
- (void)setHint:(id)arg1;
- (void)_setHint:(id)arg1;
- (id)init;
- (unsigned long long)encryptionClass;
- (id)tableColumns;
- (id)tableName;

@end

