/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface RTStateTransitionMotionActivityTypeHistogram : NSObject
{
    NSMutableDictionary *_motionActivityTypeBins;
}

@property(retain, nonatomic) NSMutableDictionary *motionActivityTypeBins; // @synthesize motionActivityTypeBins=_motionActivityTypeBins;
- (void).cxx_destruct;
- (void)show;
- (unsigned long long)getDominantMotionActivityType;
- (void)addMotionActivityType:(unsigned long long)arg1;
- (id)init;

@end

