/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "RTNotifier.h"

@class RTTransaction;

@interface RTStarkManager : RTNotifier
{
    long long _connectionState;
    RTTransaction *_dirty;
}

+ (id)sharedInstance;
@property(retain, nonatomic) RTTransaction *dirty; // @synthesize dirty=_dirty;
@property(nonatomic) long long connectionState; // @synthesize connectionState=_connectionState;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)internalRemoveObserver:(id)arg1 name:(id)arg2;
- (void)internalAddObserver:(id)arg1 name:(id)arg2;
- (void)postConnectionStateNotification;
- (_Bool)updateConnectionState;
- (void)dealloc;
- (id)init;

@end

