/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSUUID;

@interface RTStateTransitionOneTimeTrans : NSObject <NSSecureCoding>
{
    double _start_s;
    double _stop_s;
    NSUUID *_routeUUID;
    unsigned long long _motionActivityType;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long motionActivityType; // @synthesize motionActivityType=_motionActivityType;
@property(retain, nonatomic) NSUUID *routeUUID; // @synthesize routeUUID=_routeUUID;
@property(nonatomic) double stop_s; // @synthesize stop_s=_stop_s;
@property(nonatomic) double start_s; // @synthesize start_s=_start_s;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithStart:(double)arg1 stop:(double)arg2 routeUUID:(id)arg3 motionActivityType:(unsigned long long)arg4;

@end

