/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSDate, NSMutableArray, RTStateModelLocation;

@interface RTStateDepictionOneState : NSObject <NSSecureCoding>
{
    RTStateModelLocation *_location;
    NSMutableArray *_histEntryExit_s;
    id <GEOMapItem> _mapItem;
    NSDate *_geocodeDate;
    long long _type;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSDate *geocodeDate; // @synthesize geocodeDate=_geocodeDate;
@property(retain, nonatomic) id <GEOMapItem> mapItem; // @synthesize mapItem=_mapItem;
@property(retain, nonatomic) NSMutableArray *histEntryExit_s; // @synthesize histEntryExit_s=_histEntryExit_s;
@property(retain, nonatomic) RTStateModelLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

