/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSUUID;

@interface RTStateTransitionOnePredEl : NSObject
{
    int _numOfTrans;
    double _yield;
    double _predResidualStart_s;
    double _resUncStart_s;
    double _predResidualStop_s;
    double _resUncStop_s;
    double _latestTransTimeStart_s;
    double _earliestTransTimeStart_s;
    double _density;
    NSUUID *_routeUUID;
    unsigned long long _motionActivityType;
}

@property(nonatomic) unsigned long long motionActivityType; // @synthesize motionActivityType=_motionActivityType;
@property(retain, nonatomic) NSUUID *routeUUID; // @synthesize routeUUID=_routeUUID;
@property(nonatomic) double density; // @synthesize density=_density;
@property(nonatomic) double earliestTransTimeStart_s; // @synthesize earliestTransTimeStart_s=_earliestTransTimeStart_s;
@property(nonatomic) double latestTransTimeStart_s; // @synthesize latestTransTimeStart_s=_latestTransTimeStart_s;
@property(nonatomic) double resUncStop_s; // @synthesize resUncStop_s=_resUncStop_s;
@property(nonatomic) double predResidualStop_s; // @synthesize predResidualStop_s=_predResidualStop_s;
@property(nonatomic) double resUncStart_s; // @synthesize resUncStart_s=_resUncStart_s;
@property(nonatomic) double predResidualStart_s; // @synthesize predResidualStart_s=_predResidualStart_s;
@property(nonatomic) double yield; // @synthesize yield=_yield;
@property(nonatomic) int numOfTrans; // @synthesize numOfTrans=_numOfTrans;
- (void).cxx_destruct;
- (id)init;

@end

