/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSUUID;

@interface RTStateWeeklyStatisticsEl : NSObject
{
    double _numOfClustEntPerWeek;
    double _avgAggTime_s;
    double _stdAggTime_s;
    double _daysPerWeek;
    NSUUID *_stateUUID;
}

@property(nonatomic) NSUUID *stateUUID; // @synthesize stateUUID=_stateUUID;
@property(nonatomic) double daysPerWeek; // @synthesize daysPerWeek=_daysPerWeek;
@property(nonatomic) double stdAggTime_s; // @synthesize stdAggTime_s=_stdAggTime_s;
@property(nonatomic) double avgAggTime_s; // @synthesize avgAggTime_s=_avgAggTime_s;
@property(nonatomic) double numOfClustEntPerWeek; // @synthesize numOfClustEntPerWeek=_numOfClustEntPerWeek;
- (id)init;

@end

