/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSDate, RTStateDepictionOneState;

@interface RTStateDepiction : NSObject <NSSecureCoding>
{
    long long _numOfDataPts;
    RTStateDepictionOneState *_clusterState;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) RTStateDepictionOneState *clusterState; // @synthesize clusterState=_clusterState;
@property(nonatomic) long long numOfDataPts; // @synthesize numOfDataPts=_numOfDataPts;
- (void).cxx_destruct;
- (void)removeAllVisitsExceptMostRecent;
- (id)getPredState:(double)arg1 predictionWindow:(double)arg2 numOfWeeks:(int)arg3 uniqueID:(id)arg4;
- (id)getGetWeeklyStats:(double)arg1 numOfWeeks:(int)arg2 uniqueID:(id)arg3;
- (id)getEarliestLatestEntry;
- (void)showState;
- (id)getAggStateStat;
- (unsigned long long)getNumOfVisitsOverall;
- (id)getRecentVisits:(double)arg1;
- (_Bool)cleanState:(double)arg1;
- (double)getLastVisit;
- (double)getAggTimeScaleFactor:(double)arg1 predictionWindow:(double)arg2;
@property(retain, nonatomic) NSDate *geocodeDate;
@property(nonatomic) long long type;
@property(retain, nonatomic) id <GEOMapItem> mapItem;
- (id)getLocation;
- (void)setLocation:(id)arg1;
- (void)removeEntry:(double)arg1 exit:(double)arg2;
- (void)submitEntry:(double)arg1 exit:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

