/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface RTUtility : NSObject
{
}

+ (id)mobileCrashReporterPath;
+ (long long)getLevenshteinDistanceBetweenString:(id)arg1 andString:(id)arg2 withMaxCutOffDistance:(unsigned long long)arg3;
+ (void)mobileOwnFileAtPath:(id)arg1;
+ (void)toggleRoutined;
+ (void)unloadRoutined;
+ (void)loadRoutined;
+ (id)routinedLaunchdPlist;
+ (id)launchchtlFullPath;
+ (id)sqlite3FullPath;
+ (void)invokeCommandWithArguments:(id)arg1 suppressStdout:(_Bool)arg2;
+ (id)dateFormatter;
+ (id)stringFromDate:(id)arg1;
+ (id)stringFromTimestamp:(double)arg1;
+ (_Bool)isIntegrityOfFileCompromised:(id)arg1 afterSuccessfulOpen:(_Bool)arg2;
+ (id)getConsecutiveOpenFailuresKeyForPath:(id)arg1;
+ (id)getFirstOpenFailureTimestampKeyForPath:(id)arg1;
+ (unsigned long long)crcFromData:(id)arg1;
+ (_Bool)isInternalInstall;
+ (id)getBundleVersionFromPath:(id)arg1;
+ (id)getSystemInfoByName:(id)arg1;
+ (id)getSystemModel;
+ (id)getSerialNumber;
+ (id)getSystemVersion;
+ (int)pidFromAuditToken:(CDStruct_6ad76789)arg1;
+ (id)executablePathFromPid:(int)arg1;
+ (id)frameworkBundlePath;
+ (id)managedPreferencesPath;
+ (id)preferencesPath;
+ (id)logDirectoryPath;
+ (id)cacheDirectoryPath;
+ (id)defaultsDomain;

@end

