/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, RTStateModelOneVisit;

@interface RTVisitMonitor : NSObject <NSSecureCoding>
{
    _Bool _insideAnLoi;
    _Bool _insideAnLoiButStatTimeNotMet;
    _Bool _checkedForHintNearEntryLocation;
    _Bool _entryEdgeDetected;
    id <RTVisitMonitorDelegate> _delegate;
    double _lastProcessedSample_s;
    double _potentialEntry_s;
    double _potentialExit_s;
    double _sumLat_deg;
    double _sumLon_deg;
    double _sumLat2_deg;
    double _sumLon2_deg;
    double _entrySampleLat_deg;
    double _entrySampleLon_deg;
    long long _dataPointCnt;
    long long _adaptionSampleCnt;
    double _lastProcessedSampleForAdaption_s;
    long long _outlierCnt;
    NSMutableArray *_tempOutliers;
    long long _visitCallCnt;
    NSObject<OS_dispatch_queue> *_queue;
    RTStateModelOneVisit *_lastVisit;
    long long _pendingReprocessRequestCount;
}

+ (double)evalMaxUncFromMotionDevMotionInducedDev:(double)arg1 andMeasInducedDev:(double)arg2;
+ (double)evaluateMotionInducedDeviationFromDataPtCnt:(long long)arg1 sumLat_deg:(double)arg2 sumLat2_deg:(double)arg3 sumLon_deg:(double)arg4 sumLon2_deg:(double)arg5;
+ (double)evaluateClustThresFromClustThresSlv:(double)arg1 motionInducedDev:(double)arg2 adaptionBasis:(double)arg3 adaptionSampleCnt:(long long)arg4 adaptionRate:(double)arg5;
+ (double)convertLongitudeInto180Format:(double)arg1;
+ (double)convertLongitudeAtDateLineFromSum:(double)arg1 fromLongitude:(double)arg2;
+ (double)MinStaticIntervalForSLVArrivalWithHint;
+ (double)MinStaticIntervalForSLVArrival;
+ (_Bool)supportsSecureCoding;
@property(nonatomic) long long pendingReprocessRequestCount; // @synthesize pendingReprocessRequestCount=_pendingReprocessRequestCount;
@property(retain, nonatomic) RTStateModelOneVisit *lastVisit; // @synthesize lastVisit=_lastVisit;
@property(nonatomic) _Bool entryEdgeDetected; // @synthesize entryEdgeDetected=_entryEdgeDetected;
@property(nonatomic) _Bool checkedForHintNearEntryLocation; // @synthesize checkedForHintNearEntryLocation=_checkedForHintNearEntryLocation;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) long long visitCallCnt; // @synthesize visitCallCnt=_visitCallCnt;
@property(retain, nonatomic) NSMutableArray *tempOutliers; // @synthesize tempOutliers=_tempOutliers;
@property(nonatomic) long long outlierCnt; // @synthesize outlierCnt=_outlierCnt;
@property(nonatomic) double lastProcessedSampleForAdaption_s; // @synthesize lastProcessedSampleForAdaption_s=_lastProcessedSampleForAdaption_s;
@property(nonatomic) long long adaptionSampleCnt; // @synthesize adaptionSampleCnt=_adaptionSampleCnt;
@property(nonatomic) long long dataPointCnt; // @synthesize dataPointCnt=_dataPointCnt;
@property(nonatomic) double entrySampleLon_deg; // @synthesize entrySampleLon_deg=_entrySampleLon_deg;
@property(nonatomic) double entrySampleLat_deg; // @synthesize entrySampleLat_deg=_entrySampleLat_deg;
@property(nonatomic) double sumLon2_deg; // @synthesize sumLon2_deg=_sumLon2_deg;
@property(nonatomic) double sumLat2_deg; // @synthesize sumLat2_deg=_sumLat2_deg;
@property(nonatomic) double sumLon_deg; // @synthesize sumLon_deg=_sumLon_deg;
@property(nonatomic) double sumLat_deg; // @synthesize sumLat_deg=_sumLat_deg;
@property(nonatomic) double potentialExit_s; // @synthesize potentialExit_s=_potentialExit_s;
@property(nonatomic) double potentialEntry_s; // @synthesize potentialEntry_s=_potentialEntry_s;
@property(nonatomic) double lastProcessedSample_s; // @synthesize lastProcessedSample_s=_lastProcessedSample_s;
@property(nonatomic) _Bool insideAnLoiButStatTimeNotMet; // @synthesize insideAnLoiButStatTimeNotMet=_insideAnLoiButStatTimeNotMet;
@property(nonatomic) _Bool insideAnLoi; // @synthesize insideAnLoi=_insideAnLoi;
@property(nonatomic) __weak id <RTVisitMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)processLeechedLocations:(id)arg1;
- (void)onLeechedLocationsNotification:(id)arg1;
- (void)stopMonitoringVisits;
- (void)startMonitoringVisits;
- (void)fetchNumberOfSamplesForAdaptationWithHandler:(id)arg1;
- (void)showData;
- (void)_showData;
- (id)recursiveCheckForOneVisitAtLocation:(id)arg1;
- (id)checkForOneVisitAtLocation:(id)arg1;
- (void)checkForOneVisitsAtLocations:(id)arg1 withHandler:(id)arg2;
- (void)resetWithTempBufferAsHypothesis;
- (void)resetForCurrentSampleAsHypothesis:(id)arg1;
- (void)shutdown;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

