/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSMutableDictionary.h"

@interface _ContextDictionary : NSMutableDictionary
{
    NSMutableDictionary *_storage;
}

+ (id)_sharedKeySet;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)removeObjectsForKeys:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)removeAllObjects;
- (_Bool)isEqualToDictionary:(id)arg1;
- (id)description;
- (id)allValues;
- (id)allKeysForObject:(id)arg1;
- (id)allKeys;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)getObjects:(id *)arg1 andKeys:(id *)arg2;
- (id)objectEnumerator;
- (id)keyEnumerator;
- (unsigned long long)count;
- (void)dealloc;
- (void)_setup;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

@end

