/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIFont, _MessageHeaderLayoutToolbox;

@interface _FontBasedSpec : NSObject
{
    _FontBasedSpec *_shortVariant;
    UIFont *_font;
    _MessageHeaderLayoutToolbox *_toolbox;
}

+ (id)fontSpecWithFont:(id)arg1;
@property _MessageHeaderLayoutToolbox *toolbox; // @synthesize toolbox=_toolbox;
@property UIFont *font; // @synthesize font=_font;
@property(readonly) _FontBasedSpec *shortVariant; // @synthesize shortVariant=_shortVariant;
- (double)leadingValue;
- (double)leadingValueWithCoefficient:(double)arg1;

@end

