/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIFont;

@interface _MailboxContentViewCellLayoutValues : NSObject
{
    UIFont *_addressFont;
    UIFont *_dateFont;
    UIFont *_subjectFont;
    UIFont *_summaryFont;
    UIFont *_mailboxFont;
    double _rowHeight;
    double _topPadding;
    double _leading;
    double _addressCapHeight;
    double _dateCapHeight;
    double _subjectCapHeight;
    double _summaryCapHeight;
    double _bottomPadding;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) UIFont *mailboxFont;
@property(readonly, nonatomic) UIFont *summaryFont;
@property(readonly, nonatomic) UIFont *dateFont;
@property(readonly, nonatomic) UIFont *subjectFont;
@property(readonly, nonatomic) UIFont *addressFont;
@property(readonly, nonatomic) double summaryCapHeight;
@property(readonly, nonatomic) double subjectCapHeight;
@property(readonly, nonatomic) double dateCapHeight;
@property(readonly, nonatomic) double addressCapHeight;
@property(readonly, nonatomic) double leading;
@property(readonly, nonatomic) double bottomPadding;
@property(readonly, nonatomic) double topPadding;
- (double)heightWithNumberOfSummaryLines:(int)arg1;
@property(readonly, nonatomic) double defaultRowHeight;
@property(readonly, nonatomic) double compactRowHeight;
- (void)invalidate;
- (void)dealloc;

@end

