/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSMutableIndexSet, NSMutableSet;

@interface _MCVCMallContext : NSObject
{
    _Bool _showingSearchProgress;
    _Bool _showingNoMessages;
    _Bool _delayingReloadingMessages;
    NSMutableSet *_messagesPendingReload;
    NSMutableDictionary *_bannerViews;
    NSMutableIndexSet *_sectionsShowingSpinner;
    NSMutableIndexSet *_expandedSections;
}

@property(retain, nonatomic) NSMutableIndexSet *expandedSections; // @synthesize expandedSections=_expandedSections;
@property(retain, nonatomic) NSMutableIndexSet *sectionsShowingSpinner; // @synthesize sectionsShowingSpinner=_sectionsShowingSpinner;
@property(retain, nonatomic) NSMutableDictionary *bannerViews; // @synthesize bannerViews=_bannerViews;
@property(retain, nonatomic) NSMutableSet *messagesPendingReload; // @synthesize messagesPendingReload=_messagesPendingReload;
@property(nonatomic, getter=isDelayingReloadingMessages) _Bool delayingReloadingMessages; // @synthesize delayingReloadingMessages=_delayingReloadingMessages;
@property(nonatomic, getter=isShowingNoMessages) _Bool showingNoMessages; // @synthesize showingNoMessages=_showingNoMessages;
@property(nonatomic, getter=isShowingSearchProgress) _Bool showingSearchProgress; // @synthesize showingSearchProgress=_showingSearchProgress;
- (void)dealloc;

@end

