/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCache;

@interface _MessageHeaderLayoutToolbox : NSObject
{
    NSCache *_fontCache;
}

+ (id)sharedToolbox;
- (id)fontSpecForStyle:(id)arg1 shortVariant:(_Bool)arg2;
- (id)init;
- (void)dealloc;

@end

