/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class _MFActorSnapshotView;

@interface _MFActorItemView : UIView
{
    UIView *_dimmingView;
    UIView *_backgroundBorderView;
    _MFActorSnapshotView *_snapshotView;
    UIView *_viewControllerContentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_viewControllerContentView;
@property(retain, nonatomic) _MFActorSnapshotView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(readonly, nonatomic) UIView *backgroundBorderView; // @synthesize backgroundBorderView=_backgroundBorderView;
@property(readonly, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

