/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UISnapshotView.h"

@class UIImage, UIImageView;

@interface _MFActorSnapshotView : UISnapshotView
{
    UIImageView *_serializedImageView;
    struct UIEdgeInsets _snapshotInsets;
}

@property(nonatomic) struct UIEdgeInsets snapshotInsets; // @synthesize snapshotInsets=_snapshotInsets;
@property(readonly, nonatomic) UIImageView *serializedImageView; // @synthesize serializedImageView=_serializedImageView;
- (void)captureSnapshotOfView:(id)arg1 withSnapshotType:(int)arg2;
@property(retain, nonatomic) UIImage *serializedImage; // @dynamic serializedImage;
- (void)dealloc;

@end

