/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface _MFDelayedMessage : NSObject
{
    id _message;
    NSString *_identifier;
    double _fireDate;
    id _fireBlock;
}

@property(copy, nonatomic) id fireBlock; // @synthesize fireBlock=_fireBlock;
@property(nonatomic) double fireDate; // @synthesize fireDate=_fireDate;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) id message; // @synthesize message=_message;
- (void)dealloc;
- (id)initWithMessage:(id)arg1 identifier:(id)arg2 fireDate:(double)arg3 fireBlock:(id)arg4;
- (id)init;

@end

