/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDateFormatter;

@interface _SearchTimePeriodDateFormatter : NSObject
{
    unsigned long long _deltaUnit;
    long long _delta;
    NSDateFormatter *_dateFormatter;
    unsigned long long _units;
}

@property(nonatomic) unsigned long long units; // @synthesize units=_units;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void)useDelta:(long long)arg1 forUnit:(unsigned long long)arg2;
- (id)alternativeFromPhrase:(id)arg1;
- (void)dealloc;

@end

