/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class CAGradientLayer;

@interface _TabGradientView : UIView
{
}

+ (Class)layerClass;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
@property(readonly, nonatomic) CAGradientLayer *gradientLayer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

