/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "ABPersonViewControllerDelegate.h"

@protocol ABPersonViewControllerPrivateDelegate <ABPersonViewControllerDelegate>

@optional
- (void)personViewController:(id)arg1 didReloadDataInScrollView:(id)arg2;
- (void)personViewController:(id)arg1 didLoadScrollView:(id)arg2;
- (void)personViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
- (_Bool)personViewController:(id)arg1 shouldPresentMessageCompositionWithVCard:(id)arg2 filename:(id)arg3;
- (void)personViewController:(id)arg1 willSetEditing:(_Bool)arg2 animated:(_Bool)arg3;
- (_Bool)isPersonViewControllerInCustomPopover:(id)arg1;
- (void *)personForVCardRepresentation;
@end

