/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "ABPeoplePickerNavigationControllerDelegate.h"

@protocol ABPeoplePickerNavigationControllerPrivateDelegate <ABPeoplePickerNavigationControllerDelegate>

@optional
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldAllowSelectingPersonWithRecordID:(int)arg2;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 withLinkedPeople:(struct __CFArray *)arg3;
- (_Bool)peoplePickerNavigationControllerAllowsShowingPersonsCards:(id)arg1;
@end

