/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol AccountListControllerDelegate <NSObject>
- (void)accountList:(id)arg1 didCancel:(_Bool)arg2;
- (void)accountList:(id)arg1 didSelectFavorites:(_Bool)arg2;
- (void)accountList:(id)arg1 didSelectAccount:(id)arg2;
@end

