/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol AFCVisibleMailboxFetch <NSObject>
- (void)setDisplayErrors:(_Bool)arg1;
- (void)setRemoteIDToPreserve:(id)arg1;
- (void)setShouldCompact:(_Bool)arg1;
- (_Bool)willGrowFetchWindow;
- (id)mailbox;
- (id)monitor;
@end

