/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol AutoFetchController
- (oneway void)networkConfigurationChanged;
- (oneway void)stopAutoFetch;
- (oneway void)fetchNow:(int)arg1 withSources:(id)arg2;
- (oneway void)fetchNow:(int)arg1 withAccounts:(id)arg2;
- (oneway void)fetchNow:(int)arg1;
- (oneway void)startAutoFetch;
- (oneway void)setDataSource:(id)arg1;
@end

