/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CAAnimation.h"

@interface CAAnimation (MobileMail)
+ (id)shortDescriptionWithAnimationType:(unsigned long long)arg1;
+ (id)mf_animationWithKeyPath:(id)arg1 type:(unsigned long long)arg2;
- (void)mf_executeAnimationCompletionFinished:(_Bool)arg1;
- (void)mf_setAnimationCompletion:(id)arg1;
@end

