/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol DDDetectionControllerDelegate

@optional
- (id)detectionController:(id)arg1 coreRecentsWeightForResult:(struct __DDResult *)arg2 fromScanQuery:(struct __DDScanQuery *)arg3 inContainer:(id)arg4 partOfSignature:(_Bool)arg5;
@end

