/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIScrollView.h"

@interface DelayedScroller : UIScrollView
{
    id <DelayedScrollerDelegate> _delayedScrollerDelegate;
    struct CGRect _newFrame;
    struct CGRect _newBounds;
    struct CGRect _oldScrollerBounds;
    struct CGRect _rotationRect;
    unsigned int _rotationEdgePin;
    float _oldWidth;
    unsigned int _isRotating:1;
}

- (void)_setIsRotating:(_Bool)arg1;
@property(readonly, nonatomic, getter=isRotating) _Bool rotating;
- (void)setDelayedScrollerDelegate:(id)arg1;
- (void)layoutSubviews;
- (void)didRotateToInterfaceOrientation:(long long)arg1;
- (void)_redrawWebView:(id)arg1 withOldWidth:(float)arg2 andNewSize:(struct CGSize)arg3;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)_centerRotationRectWithWebViewToScale:(id)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

@end

