/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MFFreezableContent.h"
#import "UIToolbarDelegate.h"

@class NSString, UIToolbar, UIView, UIWindow;

@interface DetailViewController : UIViewController <UIToolbarDelegate, MFFreezableContent>
{
    UIViewController *_contentViewController;
    UIView *_contentContainerView;
    UIToolbar *_toolbar;
    UIView *_frozenContentSnapshotView;
    UIWindow *_snapshotWindow;
}

@property(readonly, retain, nonatomic) UIView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
@property(readonly, retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void)bringFrozenViewToFront;
- (void)unfreezeContent;
- (void)freezeContent;
- (id)rasterizableContentSubviews;
@property(nonatomic) _Bool contentScrollEnabled;
- (id)contentScrollView;
- (void)_updateToolbarItemsFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)_getFrameForToolbar:(struct CGRect *)arg1 contentView:(struct CGRect *)arg2;
- (long long)positionForBar:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
@property(retain, nonatomic) UIViewController *contentViewController;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

