/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol FavoriteItemSelectionTarget <NSObject>
- (void)setSelectedSourceType:(unsigned long long)arg1;
- (void)showVIPSettingsAnimated:(_Bool)arg1;
- (void)selectCombinedInboxWithSourceType:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)selectCombinedMailboxWithType:(int)arg1 animated:(_Bool)arg2;
- (void)selectMailbox:(id)arg1 animated:(_Bool)arg2;
- (void)selectAccount:(id)arg1 animated:(_Bool)arg2;
@end

