/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CriterionSource.h"

@interface FlaggedCriterionSource : CriterionSource
{
}

- (id)bulletinsContext;
- (id)noMessagesLabelText;
- (_Bool)shouldIncludeWholeThreads;
- (unsigned long long)type;
- (id)initWithSource:(id)arg1;

@end

