/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SharedMailboxController.h"

@interface HasAttachmentsMailboxController : SharedMailboxController
{
}

- (void)messageFlagsChanged:(id)arg1;
- (Class)criterionSourceClass;
- (struct CGPoint)iconOffset;
- (id)iconImageName;
- (id)iconTintColor;
- (id)navigationTitle;
- (id)mailboxTitle;
- (_Bool)shouldBeDisplayed;
- (id)unreadCriterion;
- (id)criterion;
- (void)dealloc;
- (id)init;

@end

