/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SharedMailboxController.h"

@interface IncludesMeMailboxController : SharedMailboxController
{
}

- (Class)criterionSourceClass;
- (struct CGPoint)iconOffset;
- (id)iconImage;
- (id)navigationTitle;
- (id)mailboxTitle;
- (_Bool)shouldBeDisplayed;
- (id)unreadCriterion;
- (id)criterion;

@end

