/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFTableViewCell.h"

#import "MailChangeManagerUnreadListener.h"

@class NSSet, UIButton, UIColor, UIImageView, UILabel;

@interface MailboxTableCell : MFTableViewCell <MailChangeManagerUnreadListener>
{
    NSSet *_mailboxes;
    struct CGPoint _iconOffset;
    UIImageView *_iconImageView;
    UIImageView *_leftAccessoryImageView;
    UILabel *_unreadCountLabel;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIColor *_titleColor;
    UIButton *_detailsDisclosureButton;
    unsigned int _level;
    unsigned int _flattenHierarchy;
    unsigned int _disabled:1;
    unsigned int _disabledForEditing:1;
    _Bool _adjustOffsetsForMarginWidth;
    _Bool _hasLeftAccessory;
    _Bool _hideUnreadCountForEditing;
    id _userInfo;
    long long _leftAccessoryType;
}

+ (id)subtitleFont;
+ (id)titleFont;
+ (double)twoLineTopBottomPadding;
+ (double)defaultRowHeight;
+ (void)invalidateCachedLayoutInformation;
@property(nonatomic) long long leftAccessoryType; // @synthesize leftAccessoryType=_leftAccessoryType;
@property(nonatomic) _Bool hideUnreadCountForEditing; // @synthesize hideUnreadCountForEditing=_hideUnreadCountForEditing;
@property(nonatomic) _Bool hasLeftAccessory; // @synthesize hasLeftAccessory=_hasLeftAccessory;
@property(nonatomic) _Bool adjustOffsetsForMarginWidth; // @synthesize adjustOffsetsForMarginWidth=_adjustOffsetsForMarginWidth;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) unsigned int flattenHierarchy; // @synthesize flattenHierarchy=_flattenHierarchy;
- (id)_scriptingInfo;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (struct CGPoint)destinationPointForAnimation;
- (void)layoutSubviews;
- (id)_multiselectBackgroundColor;
- (void)prepareForReuse;
- (id)_leftAccessoryImageView;
- (void)_updateMailboxName;
- (void)_setUnreadCount:(unsigned long long)arg1;
- (void)_removeUnreadCount;
- (void)_updateUnreadCount;
- (void)mailbox:(id)arg1 hasUnreadCount:(unsigned long long)arg2;
- (void)setCellEnabled:(_Bool)arg1;
- (void)setDetailsDisclosureButton:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setIconOffset:(struct CGPoint)arg1;
- (void)setIcon:(id)arg1 withOffset:(struct CGPoint)arg2;
- (void)setIcon:(id)arg1;
- (_Bool)isUserInteractionEnabled;
- (_Bool)isCellEnabled;
- (void)setDisabledForEditing:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setBadgeCount:(long long)arg1;
- (void)setMailboxes:(id)arg1 showUnreadCount:(_Bool)arg2;
- (void)setMailboxes:(id)arg1;
- (void)_invalidateLayout;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

