/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MailboxContentSelectionModelDataSource <NSObject>
- (void)selectionModel:(id)arg1 getSourceStateHasUnread:(_Bool *)arg2 hasUnflagged:(_Bool *)arg3;
- (void)selectionModel:(id)arg1 getConversationStateAtTableIndexPath:(id)arg2 hasUnread:(_Bool *)arg3 hasUnflagged:(_Bool *)arg4;
- (_Bool)selectionModel:(id)arg1 shouldArchiveByDefaultForTableIndexPath:(id)arg2;
- (_Bool)selectionModel:(id)arg1 supportsArchivingForTableIndexPath:(id)arg2;
- (_Bool)selectionModel:(id)arg1 deleteMovesToTrashForTableIndexPath:(id)arg2;
- (id)selectionModel:(id)arg1 messageInfosAtTableIndexPath:(id)arg2;
- (id)selectionModel:(id)arg1 messagesForMessageInfos:(id)arg2;
- (id)selectionModel:(id)arg1 indexPathForMessageInfo:(id)arg2;
- (id)selectionModel:(id)arg1 sourceForMessageInfo:(id)arg2;
- (id)sourcesForSelectionModel:(id)arg1;
@end

