/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MailComposeDeliveryControllerDelegate <NSObject>
- (void)mailComposeDeliveryControllerDidAttemptToSaveDraft:(id)arg1 account:(id)arg2 result:(unsigned long long)arg3;
- (void)mailComposeDeliveryControllerDidAttemptToSend:(id)arg1 outgoingMessageDelivery:(id)arg2;
- (void)mailComposeDeliveryControllerWillAttemptToSend:(id)arg1;
@end

