/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableOrderedSet;

@interface MailboxContentSelectionModel : NSObject
{
    id <MailboxContentSelectionModelDataSource> _dataSource;
    NSMutableOrderedSet *_selectedMessageInfos;
    NSArray *_orderedSelectedMessages;
}

- (void)updateSelectionWithAddedMessageInfos:(id)arg1 removedMessageInfos:(id)arg2 mergedConversations:(id)arg3;
- (_Bool)allSourcesThreadConversations;
- (id)firstSelectedMessage;
- (id)orderedSelectedMessages;
- (void)reselectIndexPathsWithTableView:(id)arg1;
- (void)deselectAllIndexPathsInTableView:(id)arg1;
- (void)getSelectionStateWillMoveToTrash:(_Bool *)arg1 archiveByDefault:(_Bool *)arg2 supportsArchive:(_Bool *)arg3;
- (void)getSelectionStateHasUnread:(_Bool *)arg1 hasUnflagged:(_Bool *)arg2 hasNonJunk:(_Bool *)arg3 supportsFlagging:(_Bool *)arg4;
- (void)_getSelectionStateForSources:(id)arg1 hasNonJunk:(_Bool *)arg2 supportsFlagging:(_Bool *)arg3;
- (id)sourcesForSelectedMessages;
- (id)flaggableMessages;
- (id)selectedMessages;
- (void)deselectIndexPath:(id)arg1;
- (void)selectIndexPath:(id)arg1;
- (_Bool)isPathSelected:(id)arg1;
- (_Bool)_hasSelectedMessageInfos:(id)arg1;
- (void)_enumerateSelectedIndexPaths:(id)arg1;
- (unsigned long long)messageCount;
- (void)clear;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1;
- (id)init;

@end

