/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MasterDetailViewController.h"

#import "TransferMailboxPickerDelegate.h"

@class NSString, TransferNavigationController;

@interface MailMasterDetailViewController : MasterDetailViewController <TransferMailboxPickerDelegate>
{
    TransferNavigationController *_transferNavigationController;
    _Bool _transferNavigationControllerShownInMasterView;
    _Bool _isRotating;
    _Bool _portraitToPortraitRotation;
}

@property(readonly) _Bool isRotating; // @synthesize isRotating=_isRotating;
@property(retain, nonatomic) TransferNavigationController *transferNavigationController; // @synthesize transferNavigationController=_transferNavigationController;
- (void)_selectMessageInCurrentMessageListIfNecessary;
- (void)_selectMessageListOfCurrentMessageIfNecessary;
- (void)_getRotationContentSettings:(CDStruct_e950349b *)arg1;
- (_Bool)masterViewCanSlideOut;
- (void)masterViewWillSlideIn:(_Bool)arg1;
- (void)transferMailboxPickerController:(id)arg1 animateMessageToPoint:(struct CGPoint)arg2 inView:(id)arg3 didFinishDelegate:(id)arg4 selector:(SEL)arg5 context:(id)arg6;
- (void)transferMailboxPickerControllerDidFinish:(id)arg1 animated:(_Bool)arg2;
- (void)transferMailboxPickerController:(id)arg1 didSelectMailbox:(id)arg2 withMessages:(id)arg3;
- (void)setTransferNavigationController:(id)arg1 animated:(_Bool)arg2;
- (void)cancelTransferOfMessagesFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 fromViewController:(id)arg3 animated:(_Bool)arg4;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)popoverControllerSupportsRotation:(id)arg1;
- (id)messageViewController;
- (id)mailDetailViewController;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

