/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MailStatusBarViewDelegate
- (void)statusBarView:(id)arg1 stateDidChange:(unsigned long long)arg2;
- (long long)interfaceOrientation;
- (id)updatedSubtitleString;
- (id)lastUpdated;
- (id)statusWithCount:(int *)arg1 total:(int *)arg2 progress:(float *)arg3 state:(unsigned long long *)arg4;
@end

