/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UILabel;

@interface MailStatusLabelView : UIView
{
    id <MailStatusBarViewDelegate> _delegate;
    UILabel *_primaryLabel;
    UILabel *_secondaryLabel;
}

@property(nonatomic) id <MailStatusBarViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)update;
- (void)_setText:(id)arg1 forLabel:(id *)arg2;
@property(copy, nonatomic) NSString *secondaryLabelText;
@property(copy, nonatomic) NSString *primaryLabelText;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

