/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MailboxContentTableEntry <NSObject>
- (void)updateFlagsFromMessage:(id)arg1;
- (void)setThreadMessageCount:(unsigned long long)arg1 hasUnreadMessages:(_Bool)arg2 hasAttachments:(_Bool)arg3 hasFlagged:(_Bool)arg4 hasVIP:(_Bool)arg5 hasNotify:(_Bool)arg6 receivedInterval:(double)arg7;
- (void)setMessage:(id)arg1 threaded:(_Bool)arg2;
- (void)setMailboxName:(id)arg1;
- (void)setShowsBestMatchedAddress:(_Bool)arg1;
- (void)setHighlightedTerms:(id)arg1;
@end

