/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UISplitViewController.h"

#import "TransferMailboxPickerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISplitViewControllerDelegate.h"

@class MailDetailNavigationController, MailNavigationController, NSString, TransferNavigationController, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface MailSplitViewController : UISplitViewController <UISplitViewControllerDelegate, TransferMailboxPickerDelegate, UIGestureRecognizerDelegate>
{
    _Bool _transferNavigationControllerShownInMasterView;
    UIPanGestureRecognizer *_overlaySwipeRecognizer;
    UITapGestureRecognizer *_overlayTapRecognizer;
    unsigned long long _lastGestureRecognized;
    double _panHysteresisHorizontalLocation;
    UIView *_detailDimmingView;
    _Bool _detailDimmed;
    _Bool _overlayGesturesEnabled;
    MailNavigationController *_messageListNavController;
    MailDetailNavigationController *_messageDetailNavController;
    TransferNavigationController *_transferNavigationController;
}

@property(retain, nonatomic) TransferNavigationController *transferNavigationController; // @synthesize transferNavigationController=_transferNavigationController;
@property(nonatomic) _Bool overlayGesturesEnabled; // @synthesize overlayGesturesEnabled=_overlayGesturesEnabled;
@property(readonly, nonatomic) MailDetailNavigationController *messageDetailNavController; // @synthesize messageDetailNavController=_messageDetailNavController;
@property(readonly, nonatomic) MailNavigationController *messageListNavController; // @synthesize messageListNavController=_messageListNavController;
- (void)unfocusViewController:(id)arg1 animated:(_Bool)arg2;
- (void)focusViewController:(id)arg1 animated:(_Bool)arg2;
- (void)transferMailboxPickerController:(id)arg1 animateMessageToPoint:(struct CGPoint)arg2 inView:(id)arg3 didFinishDelegate:(id)arg4 selector:(SEL)arg5 context:(id)arg6;
- (void)transferMailboxPickerControllerDidFinish:(id)arg1 animated:(_Bool)arg2;
- (void)transferMailboxPickerController:(id)arg1 didSelectMailbox:(id)arg2 withMessages:(id)arg3;
- (void)cancelTransferOfMessagesFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)setTransferNavigationController:(id)arg1 animated:(_Bool)arg2;
- (void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 fromViewController:(id)arg3 animated:(_Bool)arg4;
- (_Bool)usePadTransferStyle;
- (_Bool)_gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)_tapRecognizerShouldBegin:(id)arg1;
- (_Bool)_swipeRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_slideInOrNavigateBack:(_Bool)arg1;
- (void)_swipedBack:(id)arg1;
- (void)_tappedDimmingView:(id)arg1;
- (void)_createAndAttachOverlayGestures;
- (_Bool)shouldAutorotate;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (void)setDetailDimmed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setPrimaryVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (_Bool)_isPortrait;
- (_Bool)isCollapsed;
- (void)dealloc;
- (id)initWithMasterController:(id)arg1 detailController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

