/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MailboxGroupedPickerTableCell.h"

@interface MailMailboxGroupedPickerTableCell : MailboxGroupedPickerTableCell
{
    unsigned int _alwaysDisplayAsTopLevel:1;
}

- (void)setAlwaysDisplayAsTopLevel:(_Bool)arg1;
- (double)horizontalContentOffset;
- (id)nameForMailbox:(id)arg1;
- (int)levelForMailbox:(id)arg1;
- (double)fontSize;

@end

