/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UINavigationController.h"

@class NSArray;

@interface MailNavigationController : UINavigationController
{
    NSArray *_previousViewControllers;
    _Bool _hasAppeared;
    _Bool _poppingFromLeft;
    _Bool _transferNavigationControllerShown;
}

- (_Bool)_viewControllerUnderlapsStatusBar;
- (unsigned long long)mf_unreadCountForDisplay;
- (id)mf_statusBarSubtitleString;
- (void)resignPreparedForTransferOfMessages:(_Bool)arg1;
- (void)becomePreparedForTransferOfMessages:(id)arg1 options:(int)arg2 animated:(_Bool)arg3;
- (void)removeChildViewController:(id)arg1;
- (void)removeChildViewController:(id)arg1 notifyDidMove:(_Bool)arg2;
- (void)removeViewController:(id)arg1;
- (_Bool)isPopping;
- (void)didShowViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (id)popViewControllersPushedFromLeftAnimated:(_Bool)arg1;
- (void)_didPopFromLeft;
- (void)pushViewControllersFromLeft:(id)arg1 animated:(_Bool)arg2;
- (void)hideTransferNavigationControllerFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)showTransferNavigationController:(id)arg1 fromViewController:(id)arg2 animated:(_Bool)arg3;
- (_Bool)canShowTransferNavigationController;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldAutorotate;
- (void)dealloc;

@end

