/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SlidableMasterSplitViewController.h"

#import "MFMailPopoverManagerDelegate.h"

@class DimmingView, NSString, UIViewController;

@interface MasterDetailViewController : SlidableMasterSplitViewController <MFMailPopoverManagerDelegate>
{
    DimmingView *_detailDimmingView;
    long long _dimmedInterfaceOrientation;
    _Bool _dimmingDetailView;
    _Bool _dismissingModalViewController;
}

- (void)setUserInteractionAllowed:(_Bool)arg1 withChildViewController:(id)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1 isUserAction:(_Bool)arg2;
- (void)showPopoverViewController:(id)arg1 fromBarButtonItem:(id)arg2 animated:(_Bool)arg3;
- (void)_animationDidStop:(id)arg1 animated:(_Bool)arg2;
- (void)_animationWillStart:(id)arg1 animated:(_Bool)arg2;
- (_Bool)shouldAutorotate;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_didUndimDetailView:(_Bool)arg1;
- (void)_willUndimDetailView:(_Bool)arg1;
- (void)_didDimDetailView:(_Bool)arg1;
- (void)_willDimDetailView:(_Bool)arg1;
- (void)_setDimDetailView:(_Bool)arg1 transparently:(_Bool)arg2 animated:(_Bool)arg3;
@property(readonly, retain, nonatomic) DimmingView *detailDimmingView;
- (void)setDimDetailView:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool dimDetailView;
@property(readonly, nonatomic) UIViewController *detailViewController;
@property(readonly, nonatomic) UIViewController *masterViewController;
- (void)viewDidUnload;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

