/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MBLSingleMessageClient <NSObject>
- (void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2;
- (void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2;
- (_Bool)wantsContentsOfType:(int)arg1;
- (id)message;
- (double)ordering;
- (unsigned long long)priority;

@optional
- (void)notifyFullMessageContentsUnavailableForMessage:(id)arg1 error:(id)arg2;
@end

