/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MCSAllMessagesOperation <NSObject>
- (_Bool)isRevertibleForAllMessagesInStore:(id)arg1;
- (_Bool)revertForAllMessagesInStore:(id)arg1;
- (_Bool)commitToAllMessagesInStore:(id)arg1;
@end

