/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface MCSChangeUtilities : NSObject
{
}

+ (id)mergeMessageChanges:(id)arg1 withChanges:(id)arg2;
+ (id)allMessagesInChanges:(id)arg1;
+ (id)flagChangesForKey:(id)arg1;

@end

