/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_MCSJunk.h"

@interface MCSNotJunk : _MCSJunk
{
}

- (id)localizedShortOperationDescription;
- (id)localizedErrorTitleForMessageCount:(unsigned long long)arg1;
- (id)localizedErrorDescriptionForMessageCount:(unsigned long long)arg1;
- (id)initWithSpecialDestination:(int)arg1;
- (id)init;

@end

