/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_ContextDictionary.h"

@class MFActivityMonitor;

@interface MegaMStartFetchContext : _ContextDictionary
{
}

+ (id)_sharedKeySet;
@property(retain, nonatomic) MFActivityMonitor *monitor;

@end

