/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MessageFoldSource
- (unsigned long long)lastQuoteLevelForMessageFoldManager:(id)arg1;
- (double)messageFoldManager:(id)arg1 topOfSubjectInView:(id)arg2;
- (double)messageFoldManager:(id)arg1 topOfOriginalTextInView:(id)arg2;
- (double)messageFoldManager:(id)arg1 bottomOfFoldInView:(id)arg2;
- (id)headerViewForMessageFoldManager:(id)arg1;
- (id)foldedViewForMessageFoldManager:(id)arg1;
- (struct UIEdgeInsets)originalScrollViewContentInsetForFoldManager:(id)arg1;
- (id)scrollViewForMessageFoldManager:(id)arg1;
@end

