/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MessageMegaMallObserver <NSObject>
- (void)megaMallDidFinishSearch:(id)arg1;
- (void)megaMallGrowingMailboxesChanged:(id)arg1;
- (void)megaMallDidLoadMessages:(id)arg1;
- (void)megaMallCurrentMessageRemoved:(id)arg1;
- (void)megaMallFinishedFetch:(id)arg1;
- (void)megaMallStartFetch:(id)arg1;
- (void)megaMallMessagesAtIndexesChanged:(id)arg1;
- (void)megaMallMessageCountChanged:(id)arg1;
@end

