/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewController.h"

#import "ABUnknownPersonViewControllerDelegate.h"
#import "EKEventEditViewDelegate.h"
#import "EKEventViewDelegate.h"
#import "MFSuggestionHandlingDelegate.h"

@class MessageCallToAction, NSArray, NSMutableArray, NSString;

@interface MessageCallsToActionController : UITableViewController <ABUnknownPersonViewControllerDelegate, EKEventEditViewDelegate, EKEventViewDelegate, MFSuggestionHandlingDelegate>
{
    NSMutableArray *_groupTitles;
    NSMutableArray *_groupedCallsToAction;
    struct __CFDictionary *_eventsForCallsToAction;
    NSArray *_callsToAction;
    MessageCallToAction *_inProgressAction;
}

@property(retain, nonatomic) MessageCallToAction *inProgressAction; // @synthesize inProgressAction=_inProgressAction;
@property(copy, nonatomic) NSArray *callsToAction; // @synthesize callsToAction=_callsToAction;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)eventViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (_Bool)unknownPersonViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)showActionSheetForCanceledEventAction:(id)arg1;
- (void)presentEventEditViewForAction:(id)arg1;
- (void)presentEventViewForAction:(id)arg1;
- (void)displayMultipleCallsToAction:(id)arg1 sender:(id)arg2;
- (void)ignoredAction:(id)arg1 sender:(id)arg2;
- (id)indexPathForAction:(id)arg1 containingGroup:(id *)arg2;
- (void)confirmedAction:(id)arg1 sender:(id)arg2;
- (void)displayEventSuggestion:(id)arg1;
- (void)displayContactSuggestion:(id)arg1;
- (struct CGSize)preferredContentSize;
- (void)recalculateCellGroups;
- (id)_titleForCategory:(long long)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

