/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UISaveToCameraRollActivity.h"

@interface MessageSaveToCameraRollActivity : UISaveToCameraRollActivity
{
    int _context;
    id <MFAttachmentHandlingDelegate> _attachmentHandlingDelegate;
}

@property(nonatomic) int context; // @synthesize context=_context;
@property(nonatomic) id <MFAttachmentHandlingDelegate> attachmentHandlingDelegate; // @synthesize attachmentHandlingDelegate=_attachmentHandlingDelegate;
- (id)_beforeActivity;
- (id)_activityImage;
- (id)activityType;
- (id)initWithAttachmentHandlingDelegate:(id)arg1 context:(int)arg2;
- (id)init;

@end

