/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "MFAddressBookClient.h"
#import "MessageSuggestionBannerDelegate.h"

@class MFCaptionLabel, MFMessageViewingContext, MFModernLabelledAtomList, MailAccount, MessageHeaderHeader, MessageSuggestionBanner, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSSet, NSString, SeparatorLayer, UIImageView, WorkingPushButton;

@interface MessageHeaderLayer : UIView <MFAddressBookClient, MessageSuggestionBannerDelegate>
{
    MFMessageViewingContext *_context;
    MailAccount *_account;
    struct CGSize _oldSize;
    NSArray *_cachedToRecipients;
    NSArray *_cachedCcRecipients;
    NSArray *_cachedBccRecipients;
    NSArray *_cachedSenders;
    NSSet *_cachedReceivingEmailAddresses;
    NSMutableSet *_callsToAction;
    NSMutableArray *_layersToRemoveWhenSmall;
    NSMutableDictionary *_atomListDictionary;
    WorkingPushButton *_infoButton;
    WorkingPushButton *_oldInfoButton;
    MessageHeaderHeader *_header;
    MFModernLabelledAtomList *_primaryField;
    MessageSuggestionBanner *_suggestionBanner;
    SeparatorLayer *_bannerSeparator;
    double _horizontalInset;
    int _displayStyle;
    MFCaptionLabel *_captionLabel;
    void *_displayedPerson;
    UIImageView *_personIconImageView;
    unsigned int _showDetails:1;
    unsigned int _enabled:1;
    unsigned int _selected:1;
    unsigned int _isOutgoing:1;
    unsigned int _suggestionBannerVisible:1;
    _Bool _preventLayout;
    id <MFMessageContentDisplayDelegate> _displayDelegate;
    id <MFSuggestionHandlingDelegate> _suggestionDelegate;
}

+ (void)initialize;
@property(nonatomic) _Bool preventLayout; // @synthesize preventLayout=_preventLayout;
@property(nonatomic) id <MFSuggestionHandlingDelegate> suggestionDelegate; // @synthesize suggestionDelegate=_suggestionDelegate;
@property(nonatomic) id <MFMessageContentDisplayDelegate> displayDelegate; // @synthesize displayDelegate=_displayDelegate;
@property(nonatomic) double horizontalInset; // @synthesize horizontalInset=_horizontalInset;
@property(retain, nonatomic) MailAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) MFMessageViewingContext *viewingContext; // @synthesize viewingContext=_context;
- (_Bool)_atomContainsVIPSender:(id)arg1;
- (void)_updateVIPStatus;
- (void)_vipSendersDidChange:(id)arg1;
- (void)_accountsDidChange:(id)arg1;
- (void)_trustDidChange:(id)arg1;
- (void)_updateAtomStyles;
- (void)didSelectMessageSuggestionBanner:(id)arg1 sender:(id)arg2;
- (void)clearSuggestionsBanners;
- (void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 ignoredAction:(id)arg3;
- (void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 confirmedAction:(id)arg3;
- (id)callsToAction;
- (void)addBannersForCallsToAction:(id)arg1 animated:(_Bool)arg2;
- (void)_updateSuggestionBannerHidden;
- (void)_setSuggestionBannerVisible:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=_suggestionBannerVisible, setter=_setSuggestionBannerVisible:) _Bool suggestionBannerVisible;
- (void)_buttonAnimationDidFinish;
- (void)_updatePrimaryFieldUI;
- (void)_updatePrimaryFieldCaption;
- (_Bool)_captionLabelIsVisible;
- (void)_removeDetailLayers;
- (void)_addDetailLayers;
- (void)_headerHeightDidChangeAfterAnimation:(_Bool)arg1;
- (void)_headerAnimationDidStop;
- (void)_setShowDetails:(_Bool)arg1 animate:(_Bool)arg2 force:(_Bool)arg3;
- (void)infoButtonClicked:(id)arg1;
- (id)_addAddressListWithAddresses:(id)arg1 label:(id)arg2 title:(id)arg3 maxWidth:(double)arg4 action:(SEL)arg5;
- (id)_arrangedRecipients:(id)arg1 withReceivingEmailAddresses:(id)arg2;
- (void)_updateContactPhotoViewAlpha;
- (void)_cacheContactPhoto;
@property(nonatomic) _Bool bottomSeparatorDrawsFlushWithLeadingEdge;
- (void)_sendAction:(SEL)arg1 forAddressAtom:(id)arg2;
- (void)senderAtomPressed:(id)arg1;
- (void)recipientAtomPressed:(id)arg1;
- (id)bottomSeparator;
- (struct CGRect)subjectFrame;
- (id)personIconImageView;
- (void *)displayedPerson;
- (id)htmlRepresentationLeavingSpaceForPhoto:(_Bool)arg1;
- (void)updateDateAndTime;
- (void)updateForRedisplay;
- (void)layoutSubviews;
- (void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (void)viewingContextFinishedLoading:(id)arg1;
- (double)atomListLineSpacing;
- (void)displayMessage:(id)arg1 withStyle:(int)arg2;
- (void)tintColorDidChange;
- (void)updateInfoButton;
- (void)createInfoButtonWithTitle:(id)arg1;
- (void)clearMessage;
@property(nonatomic) _Bool enabled;
- (void)addressBookManager:(id)arg1 addressBookDidChange:(void *)arg2;
- (void)addressBookPreferencesChangedForAddressBookManager:(id)arg1;
- (void)_invalidateAtomsAndContactPhoto;
- (void)dealloc;
- (_Bool)canShowMarkButton;
- (_Bool)usePadDisplayStyle;
- (id)initWithFrame:(struct CGRect)arg1 displayStyle:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

