/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MessageBodyLoader
- (oneway void)resume;
- (oneway void)pause;
- (oneway void)disableNetworkFetching;
- (oneway void)enableNetworkFetching;
- (oneway void)userStoppedViewingMessages;
- (oneway void)userViewingMessages:(id)arg1;
- (oneway void)stopAddingNewMessagesForStore:(id)arg1;
- (oneway void)beginAddingNewMessagesForStore:(id)arg1;
- (oneway void)addMessages:(id)arg1;
- (oneway void)addMessage:(id)arg1;
- (oneway void)removeSingleMessageClient:(id)arg1;
- (oneway void)addSingleMessageClient:(id)arg1;
@end

