/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class DOMHTMLElement, MFMailMessage, MFSubjectWebBrowserView, MessageViewStatusIndicatorManager, SeparatorLayer, UILabel;

@interface MessageHeaderHeader : UIView
{
    MFMailMessage *_lastMessage;
    MFSubjectWebBrowserView *_subjectWebView;
    DOMHTMLElement *_subjectTextElement;
    UILabel *_dateLabel;
    UILabel *_mailboxLabel;
    UIView *_statusIndicatorView;
    MessageViewStatusIndicatorManager *_statusIndicatorManager;
    SeparatorLayer *_bottomSeparator;
    SeparatorLayer *_topSeparator;
    double _horizontalInset;
    int _displayStyle;
    _Bool _markedAsUnread;
    _Bool _markedAsFlagged;
    _Bool _senderIsVIP;
    _Bool _isOutgoing;
    _Bool _showMailboxName;
    _Bool _isNotifyThread;
    _Bool _bottomSeparatorDrawsFlushWithLeadingEdge;
}

@property(nonatomic) _Bool bottomSeparatorDrawsFlushWithLeadingEdge; // @synthesize bottomSeparatorDrawsFlushWithLeadingEdge=_bottomSeparatorDrawsFlushWithLeadingEdge;
@property(nonatomic) double horizontalInset; // @synthesize horizontalInset=_horizontalInset;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5;
- (id)_addSeparatorAtPosition:(double)arg1;
- (id)bottomSeparator;
- (struct CGRect)subjectFrame;
- (void)addSubview:(id)arg1;
- (void)layoutSubviews;
- (double)contentHeightWithDateRect:(struct CGRect)arg1 subjectRect:(struct CGRect)arg2 mailboxRect:(struct CGRect)arg3;
- (struct CGRect)layoutDate:(id)arg1 withStatusRect:(struct CGRect)arg2 subjectRect:(struct CGRect)arg3;
- (struct CGRect)rectForStatusIndicator;
- (struct CGRect)rectForMailboxNameWithDateRect:(struct CGRect)arg1;
- (struct CGRect)layoutSubjectWithMailboxRect:(struct CGRect)arg1 statusRect:(struct CGRect)arg2;
- (_Bool)shouldDisplay;
- (void)displayMessage:(id)arg1 withStyle:(int)arg2;
- (id)mailboxName;
- (void)clearMessage;
- (void)_setSubjectText:(id)arg1;
- (id)contextForDDDetectionController;
- (void)_significantTimeChange:(id)arg1;
- (void)updateDateAndTime;
- (void)updateForRedisplayWithStatusIndicatorsVisible:(_Bool)arg1;
- (void)setMailboxNameVisible:(_Bool)arg1;
- (void)_flagStyleDidChange:(id)arg1;
- (void)_clearStatusIndicators;
- (void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (void)allowUnreadStateToBeShown;
- (id)dateSent;
- (id)subject;
- (void)_reloadFontSizes;
- (void)_updateVeryLargeSubjectAllowed;
- (id)_subjectLineHTML:(_Bool)arg1;
- (_Bool)usePadDisplayStyle;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 displayStyle:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

