/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIActivityViewController.h"

@interface MessageActivityViewController : UIActivityViewController
{
    _Bool _sourceIsManaged;
}

@property(nonatomic) _Bool sourceIsManaged; // @synthesize sourceIsManaged=_sourceIsManaged;
- (id)initWithActivityItems:(id)arg1 applicationActivities:(id)arg2;

@end

