/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class MessageSuggestionTitleControl, NSArray, NSLayoutConstraint, SeparatorLayer, UIButton;

@interface MessageSuggestionBanner : UIView
{
    NSLayoutConstraint *_buttonHeightConstraint;
    NSArray *_buttonConstraints;
    NSArray *_noButtonConstraints;
    NSArray *_twoLineConstraints;
    NSArray *_bothSingleLineConstraints;
    NSArray *_narrowSingleLineConstraints;
    NSArray *_wideSingleLineConstraints;
    MessageSuggestionTitleControl *_titleView;
    UIButton *_primaryButton;
    UIButton *_secondaryButton;
    SeparatorLayer *_buttonSeparator;
    SeparatorLayer *_titleViewSeparator;
    SeparatorLayer *_bottomSeparator;
    SeparatorLayer *_singleLineSeparator;
    id <MessageSuggestionBannerDelegate> _delegate;
    NSArray *_callsToAction;
}

+ (double)buttonHeight;
+ (id)buttonLabelFont;
+ (_Bool)requiresConstraintBasedLayout;
@property(readonly, nonatomic) NSArray *callsToAction; // @synthesize callsToAction=_callsToAction;
@property(nonatomic) id <MessageSuggestionBannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_secondaryButtonTapped:(id)arg1;
- (void)_primaryButtonTapped:(id)arg1;
- (void)_titleTapped:(id)arg1;
- (void)_updateBanner;
- (void)getTitle:(id *)arg1 subtitle:(id *)arg2 forCallsToAction:(id)arg3;
- (id)_ordinalForCategory:(long long)arg1 count:(long long)arg2;
- (id)_titleForCategory:(long long)arg1;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (void)reloadData;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateConstraintsForSize:(struct CGSize)arg1;
- (void)_addConstraintsIfNecessary:(id)arg1;
- (void)updateConstraints;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

