/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MessageCallToAction.h"

@class NSString, SGRealtimeContact;

@interface MessageCallToActionRealtimeContact : MessageCallToAction
{
    NSString *_title;
    NSString *_subtitle;
}

+ (id)callToActionForRealtimeContact:(id)arg1;
- (id)secondaryActionTitle;
- (id)primaryActionTitle;
- (id)subtitle;
- (id)title;
@property(readonly, retain, nonatomic) SGRealtimeContact *realtimeContact;
- (id)bundleIdentifier;
- (long long)compare:(id)arg1;
- (void)dealloc;

@end

