/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageConsumer.h"

@class NSMutableArray, SearchOperation;

@interface MessageSearchResultsConsumer : NSObject <MessageConsumer>
{
    SearchOperation *_operation;
    unsigned long long _sentBatchCount;
    unsigned long long _nextBatchSize;
    NSMutableArray *_pendingMessages;
}

- (void)_sendForcibly:(_Bool)arg1;
- (void)done;
- (void)newMessagesAvailable:(id)arg1;
- (_Bool)shouldCancel;
- (void)dealloc;
- (id)initWithOperation:(id)arg1;

@end

