/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageSelectionDataSource.h"
#import "MiniMallSourceBulkOperationsDelegate.h"
#import "SearchOrderCacheDelegate.h"

@class MFActivityMonitor, MFMailMessage, MessageSelectionStrategy, NSCache, NSMutableArray, NSMutableIndexSet, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, SearchOrderCache, SourceSearchContext;

@interface MessageMiniMall : NSObject <MessageSelectionDataSource, SearchOrderCacheDelegate, MiniMallSourceBulkOperationsDelegate>
{
    int _suspendCount;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableSet *_sources;
    NSMutableSet *_emptiedSources;
    NSMutableArray *_messageInfos;
    struct __CFDictionary *_conversations;
    NSCache *_sendersByConversation;
    unsigned long long _threadedMessageCount;
    NSMutableIndexSet *_sectionOffsets;
    NSMutableArray *_sectionTitles;
    MFActivityMonitor *_fetchActivity;
    _Bool _userRefresh;
    MessageSelectionStrategy *_selectionStrategy;
    MFMailMessage *_currentMessage;
    int _lastChangeDirection;
    SourceSearchContext *_searchContext;
    SearchOrderCache *_orderValueCache;
    id _comparator;
}

- (id)_orderValueCache;
- (void)_dumpDiagnosticInformation:(id)arg1;
- (_Bool)_hasOnlyThreadedSources;
- (_Bool)allSourcesThreadMessages;
- (unsigned long long)sourceType;
- (_Bool)isInCombinedMailboxOfType:(int)arg1;
- (_Bool)isInCombinedInbox;
- (_Bool)shouldPopOnZeroMessages;
- (_Bool)shouldArchiveByDefaultForTableIndexPath:(id)arg1;
- (_Bool)supportsArchivingForTableIndexPath:(id)arg1;
- (_Bool)deleteMovesToTrashForTableIndexPath:(id)arg1;
- (struct __CFDictionary *)_copyMessageInfosBySourceForTableIndexPath:(id)arg1;
- (_Bool)archiveByDefaultForMessage:(id)arg1;
- (_Bool)archivesByDefault;
- (_Bool)supportsArchivingForMessage:(id)arg1;
- (_Bool)supportsArchiving;
- (_Bool)deleteMovesToTrashForMessage:(id)arg1;
- (_Bool)deleteMovesToTrash;
- (id)_copySources;
- (void)_filterTaskCompletedWithContext:(id)arg1;
- (id)_removeMessages:(id)arg1;
- (id)_indexPathsFromIndexes:(id)arg1;
- (void)_synchronouslyFilterOutMessages:(id)arg1 fromSource:(id)arg2;
- (void)_synchronouslyFilterInMessages:(id)arg1 fromSource:(id)arg2;
- (_Bool)ensureWeHaveLoadedMessages;
- (void)_scheduleEnsureWeHaveLoadedMessages;
- (void)_recalculateSectionOffsets;
- (void)_protectedDataWasReconciled:(id)arg1;
- (void)_protectedDataWillBecomeUnavailable:(id)arg1;
- (void)_sourceDidFinishSearch:(id)arg1;
- (void)_sourceDidReload:(id)arg1;
- (void)_conversationHasMerged:(id)arg1;
- (void)_messageFlagsChanged:(id)arg1;
- (void)_messagesCompacted:(id)arg1;
- (void)_messagesAdded:(id)arg1;
- (void)_checkServerCount:(id)arg1;
- (void)flushCaches;
- (void)applicationDidResume;
- (void)applicationWillSuspend;
- (id)_searchOrderComparator;
- (_Bool)areAnySourcesSearching;
- (void)setSearchContext:(id)arg1 options:(unsigned long long)arg2;
- (unsigned long long)searchOrderCache:(id)arg1 rankValueForMessage:(id)arg2 context:(id)arg3;
- (id)searchOrderCache:(id)arg1 sectionDescriptionForRankValue:(unsigned long long)arg2 context:(id)arg3;
- (void)_addChangeSetToManager:(id)arg1;
- (void)markAllMessagesAsNotViewed;
- (void)markAllMessagesAsViewed;
- (void)markAllMessagesAsNotFlagged;
- (void)markAllMessagesAsFlagged;
- (void)moveAllMessagesToMailbox:(id)arg1;
- (void)markAllMessagesAsDeletedOrArchived:(unsigned long long)arg1;
- (void)didDeleteAllMessagesInSource:(id)arg1;
- (void)markMessages:(id)arg1 asDeletedOrArchived:(unsigned long long)arg2;
- (void)transferMessages:(id)arg1 toMailbox:(id)arg2;
- (id)junkMailboxMessagesInMessages:(id)arg1;
- (id)titleWithUnreadCount:(unsigned long long)arg1 options:(unsigned long long)arg2;
- (unsigned long long)unreadCountForDisplay;
- (_Bool)shouldShowUnreadCount;
- (unsigned long long)serverUnreadCount;
- (unsigned long long)serverMessageCount;
- (unsigned long long)localMessageCount;
- (unsigned long long)_messageCount;
- (unsigned long long)messageCountInSection:(long long)arg1;
- (id)messageForMessageID:(id)arg1;
- (void)setLastViewedMessage:(id)arg1;
- (id)lastViewedMessage;
- (void)getLastViewedMessage:(id *)arg1 date:(id *)arg2;
- (id)defaultMessageIncludingUnread:(_Bool)arg1;
- (id)messageToSelectFromMessage:(id)arg1 withDirection:(int)arg2;
- (id)messageToSelectAfterDeletedMessages:(id)arg1;
- (id)messageToSelectAfterDeletedMessage:(id)arg1;
- (void)_currentMessageRemovedWithMessageToSelect:(id)arg1;
- (int)lastChangeDirection;
- (void)setLastChangeDirection:(int)arg1;
- (void)setCurrentMessage:(id)arg1;
- (id)currentMessage;
- (id)messageAtFlattenedIndex:(unsigned long long)arg1;
- (id)tableIndexPathOfConversationContainingMessageInfo:(id)arg1;
- (id)tableIndexPathOfConversationContainingMessage:(id)arg1;
- (id)tableIndexPathOfMessageOrConversation:(id)arg1;
- (id)_tableIndexPathOfMessageOrConversationForInfo:(id)arg1 conversationMustContainMessage:(_Bool)arg2;
- (unsigned long long)flattenedIndexOfWhereMessageShouldGo:(id)arg1;
- (unsigned long long)flattenedIndexOfMessage:(id)arg1;
- (id)bulletinsContexts;
- (struct __CFDictionary *)copySendersByLibraryIDForConversation:(long long)arg1;
- (id)_sourceForMessageInfo:(id)arg1;
- (id)_cachedMessageForMessageInfo:(id)arg1;
- (id)_messageForMessageInfo:(id)arg1 cache:(_Bool)arg2;
- (id)messageForMessageInfo:(id)arg1;
- (id)_copyAllMessageInfos;
- (id)copyAllMessages;
- (id)conversationContainingMessage:(id)arg1;
- (id)tableIndexPathOfOldestMessageInSource:(id)arg1;
- (id)tableIndexPathOfConversationWithID:(long long)arg1;
- (id)tableIndexPathOfMessageInfo:(id)arg1;
- (id)tableIndexPathOfMessage:(id)arg1;
- (void)getIndex:(unsigned long long *)arg1 andCount:(unsigned long long *)arg2 ofMessageInConversation:(id)arg3;
- (unsigned long long)messageCountForConversationWithMessage:(id)arg1;
- (unsigned long long)messageCountAtTableIndexPath:(id)arg1;
- (id)sourcesForMessagesAtTableIndexPath:(id)arg1;
- (id)messageInfosAtTableIndexPath:(id)arg1;
- (id)messagesAtTableIndexPath:(id)arg1;
- (id)messageAtTableIndexPath:(id)arg1;
- (void)getSourceStateHasUnread:(_Bool *)arg1 hasUnflagged:(_Bool *)arg2;
- (void)getConversationStateAtTableIndexPath:(id)arg1 hasUnread:(_Bool *)arg2 hasUnflagged:(_Bool *)arg3;
- (void)_nts_getConversationStateFromNewestMessageInfo:(id)arg1 shouldThread:(_Bool)arg2 hasUnread:(_Bool *)arg3 hasUnflagged:(_Bool *)arg4;
- (void)updateEntry:(id)arg1 atTableIndexPath:(id)arg2 addressList:(id *)arg3 options:(unsigned long long)arg4;
- (id)_indexPathForMessageInfoIndex:(unsigned long long)arg1;
- (unsigned long long)_messageInfoIndexForIndexPath:(id)arg1;
- (unsigned long long)_offsetForSection:(long long)arg1;
- (id)titleForSection:(long long)arg1;
- (unsigned long long)numberOfSections;
@property(copy, nonatomic) id comparator; // @synthesize comparator=_comparator;
- (id)comparatorForMallContainingMessage:(SEL)arg1;
- (void)_purgeCachedMessageInfosWithReason:(id)arg1;
- (void)_handleFetchCompleted:(id)arg1;
- (void)_fetchCompleted:(id)arg1;
- (void)_checkForNewMailAndNotifyOnFailure:(_Bool)arg1;
- (void)_checkForNewMailAndNotifyOnFailureBackground:(_Bool)arg1 userRefresh:(_Bool)arg2 foregroundRequest:(_Bool)arg3 sourcesToCheck:(id)arg4 remoteID:(id)arg5;
- (id)currentRemoteIDForMailbox:(id)arg1;
- (void)checkForNewMailAndNotifyOnFailure:(_Bool)arg1 userRefresh:(_Bool)arg2;
- (void)trackFetchVisibleStoresActivity:(id)arg1;
- (id)sourceForMailbox:(id)arg1;
- (id)sources;
- (void)removeAllSources;
- (void)addSource:(id)arg1;
- (void)enqueueWork:(id)arg1;
- (void)resume;
- (void)suspend;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithObserver:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

