/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MessageSuggestionBannerDelegate <NSObject>
- (void)didSelectMessageSuggestionBanner:(id)arg1 sender:(id)arg2;
- (void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 ignoredAction:(id)arg3;
- (void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 confirmedAction:(id)arg3;
- (id)callsToAction;
@end

