/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABPersonViewControllerPrivateDelegate.h"
#import "ABUnknownPersonViewControllerDelegate.h"
#import "AFContextProvider.h"
#import "DelayedScrollerDelegate.h"
#import "EKEventEditViewDelegate.h"
#import "EKEventViewDelegate.h"
#import "MFArrowControlsViewDelegate.h"
#import "MFAttachmentHandlingDelegate.h"
#import "MFMailPopoverManagerDelegate.h"
#import "MFMessageContentDisplayDelegate.h"
#import "MFMessageViewingContextDelegate.h"
#import "MFPassthroughViewProvider.h"
#import "MFSuggestionHandlingDelegate.h"
#import "MessageMegaMallObserver.h"
#import "TransferMailboxPickerDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIToolbarDelegate.h"

@class ABPersonViewController, ABUnknownPersonViewController, CertificateViewController, ComposeNavigationController, EKICSPreviewController, LongPressableButtonItem, MFArrowControlsView, MFMessageViewingContext, MFModernAddressAtom, MFSecureMIMEPersonHeaderView, MFVIPSender, MailAccount, MessageContentAreaLayer, MessageMegaMall, NSMutableDictionary, NSObject, NSSet, NSString, NSUndoManager, SGRealtimeContact, SGRealtimeEvent, UIBarButtonItem, UIDocumentInteractionController, UIKeyCommand, UITraitCollection, UIView;

@interface MessageViewController : UIViewController <MFSuggestionHandlingDelegate, UIToolbarDelegate, MessageMegaMallObserver, ABPersonViewControllerPrivateDelegate, ABUnknownPersonViewControllerDelegate, DelayedScrollerDelegate, TransferMailboxPickerDelegate, MFMessageViewingContextDelegate, MFPassthroughViewProvider, MFMailPopoverManagerDelegate, EKEventViewDelegate, EKEventEditViewDelegate, UIDocumentInteractionControllerDelegate, AFContextProvider, MFAttachmentHandlingDelegate, MFMessageContentDisplayDelegate, MFArrowControlsViewDelegate>
{
    MFMessageViewingContext *_viewingContext;
    MFMessageViewingContext *_selectedViewingContext;
    MailAccount *_account;
    MessageMegaMall *_mall;
    MessageContentAreaLayer *_storedMessageLayer;
    ComposeNavigationController *_composeViewController;
    CertificateViewController *_certificateViewController;
    UIView *_composeViewContainerView;
    UIBarButtonItem *_transferButtonItem;
    LongPressableButtonItem *_deleteButtonItem;
    UIBarButtonItem *_replyButtonItem;
    UIBarButtonItem *_arrowsButtonItem;
    UIBarButtonItem *_markButtonItem;
    LongPressableButtonItem *_composeButtonItem;
    UITraitCollection *_previousTraitCollection;
    MFArrowControlsView *_arrowControlsView;
    int _lastChangeDirection;
    UIView *_suspensionPlaceholderView;
    UIView *_viewForTrashAnimation;
    NSSet *_trashedMessages;
    unsigned long long _deleteOrArchiveTrashedMessages;
    ABPersonViewController *_personViewController;
    ABUnknownPersonViewController *_unknownPersonViewController;
    MFModernAddressAtom *_atomPresentingPersonView;
    MFVIPSender *_currentVIP;
    NSMutableDictionary *_navigationControllersCache;
    union {
        NSObject *_controller;
        EKICSPreviewController *_icsPreviewController;
        UIDocumentInteractionController *_uidic;
        ABUnknownPersonViewController *_vcardController;
    } _controller;
    long long _uidicState;
    int _displayStyle;
    unsigned int _allowDelete:1;
    unsigned int _searching:1;
    unsigned int _showingAlternateMessageLayer:1;
    unsigned int _crossFadeNextLayer:1;
    unsigned int _blockingNetworkFetching:1;
    unsigned int _blockingInteractionEvents:1;
    unsigned int _isDeleting:1;
    unsigned int _isAboutToAnimateTrashedMessage:1;
    unsigned int _isTrashingMessage:1;
    unsigned int _shouldPopOnDeletion:1;
    unsigned int _dontMarkMessageAsRead:1;
    unsigned int _willBecomeVisible:1;
    unsigned int _shouldShowProgressOnVisible:1;
    unsigned int _needsMessageRedisplayOnAppear:1;
    unsigned int _isShowingMailboxPicker:1;
    unsigned int _isShowingArchiveButton:1;
    unsigned int _needsToSuspendView:1;
    unsigned int _preparedForTransferOfMessages:1;
    unsigned int _deleteButtonArchives:1;
    unsigned int _landscapeThreadNavigationEnabled:1;
    unsigned int _isShowingThreadNavigation:1;
    unsigned int _isInThread:1;
    unsigned int _isInCombinedInbox:1;
    unsigned int _viewDidWillAppear:1;
    unsigned int _contentAreaNeedsRefold:1;
    UIKeyCommand *_replyKeyCommand;
    UIKeyCommand *_replyAllKeyCommand;
    UIKeyCommand *_forwardKeyCommand;
    _Bool _dataDetectorsHadModification;
    unsigned long long _nextMessageLayerState;
    MFSecureMIMEPersonHeaderView *_existingSecureMIMEPersonHeaderView;
    unsigned long long _sourceType;
    UIBarButtonItem *_mailboxButtonItem;
    SGRealtimeContact *_suggestedContact;
    SGRealtimeEvent *_suggestedEvent;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
+ (struct __DDScanner *)subjectScanner;
+ (id)sharedController;
@property(retain, nonatomic) SGRealtimeEvent *suggestedEvent; // @synthesize suggestedEvent=_suggestedEvent;
@property(retain, nonatomic) SGRealtimeContact *suggestedContact; // @synthesize suggestedContact=_suggestedContact;
@property(readonly, nonatomic) UIBarButtonItem *mailboxButtonItem; // @synthesize mailboxButtonItem=_mailboxButtonItem;
@property(nonatomic) unsigned long long sourceType; // @synthesize sourceType=_sourceType;
@property(retain, nonatomic) MFVIPSender *currentVIP; // @synthesize currentVIP=_currentVIP;
@property(retain, nonatomic) MFModernAddressAtom *atomPresentingPersonView; // @synthesize atomPresentingPersonView=_atomPresentingPersonView;
@property(retain, nonatomic) ABUnknownPersonViewController *unknownPersonViewController; // @synthesize unknownPersonViewController=_unknownPersonViewController;
@property(retain, nonatomic) ABPersonViewController *personViewController; // @synthesize personViewController=_personViewController;
@property(retain, nonatomic) CertificateViewController *certificateViewController; // @synthesize certificateViewController=_certificateViewController;
@property(retain, nonatomic) MailAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) MFMessageViewingContext *selectedViewingContext; // @synthesize selectedViewingContext=_selectedViewingContext;
@property(readonly, nonatomic) UIBarButtonItem *deleteButtonItem; // @synthesize deleteButtonItem=_deleteButtonItem;
@property(retain, nonatomic) MessageMegaMall *mall; // @synthesize mall=_mall;
- (void)previewNewIndicatorAfterSwipeAction:(unsigned long long)arg1;
- (id)getCurrentContext;
- (id)saPersonAttributesFromEmails:(id)arg1 addressBook:(void *)arg2;
- (_Bool)allowContextProvider:(id)arg1;
- (void)_popIfNecessaryAnimated:(_Bool)arg1;
- (void)_removeStringsFromArray:(id)arg1 thatCaseInsensitiveMatchStringsInArray:(id)arg2;
- (void)_accountsDidChange:(id)arg1;
- (void)_fontSizeDidChange:(id)arg1;
- (void)accessibilityLargeTextDidChange;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)messagesWereResurrectedNotification:(id)arg1;
- (void)megaMallDidLoadMessages:(id)arg1;
- (void)megaMallDidFinishSearch:(id)arg1;
- (void)megaMallCurrentMessageRemoved:(id)arg1;
- (void)megaMallGrowingMailboxesChanged:(id)arg1;
- (void)megaMallFinishedFetch:(id)arg1;
- (void)megaMallStartFetch:(id)arg1;
- (void)megaMallMessagesAtIndexesChanged:(id)arg1;
- (void)megaMallMessageCountChanged:(id)arg1;
- (void)_animateView:(id)arg1 toCenterPoint:(struct CGPoint)arg2 size:(struct CGSize)arg3 otherAnimations:(id)arg4 completion:(void)arg5;
- (void)_shrinkMessageToToolbarButton:(id)arg1 completion:(id)arg2;
- (void)transferMailboxPickerController:(id)arg1 animateMessageToThumbnailFrame:(struct CGRect)arg2 inView:(id)arg3 completion:(id)arg4;
- (id)transferMailboxPickerController:(id)arg1 viewForMessage:(id)arg2;
- (void)transferMailboxPickerControllerDidFinish:(id)arg1 animated:(_Bool)arg2;
- (void)transferMailboxPickerController:(id)arg1 didSelectMailbox:(id)arg2 withMessages:(id)arg3;
- (void)transferMessages:(id)arg1 toMailbox:(id)arg2;
- (void)messageViewingContext:(id)arg1 attachmentLoadCompleted:(id)arg2 withData:(id)arg3;
- (void)messageViewingContextFullMessageLoadFailed:(id)arg1;
- (void)messageViewingContextContentLoadCompleted:(id)arg1;
- (void)messageViewingContextContentLoadWillBegin:(id)arg1;
- (void)_updateViewingContextToMessage:(id)arg1;
- (id)messageViewingContext;
@property(nonatomic, getter=isInThread) _Bool inThread;
@property(nonatomic) _Bool searching;
@property(nonatomic) _Bool allowDelete;
- (void)setMessageViewingContext:(id)arg1 options:(unsigned long long)arg2;
- (void)_updateMessageDisplayUserActivity;
- (void)updateUserActivityState:(id)arg1;
- (void)downloadAndSaveAllAttachments;
- (void)saveAllAttachments;
- (id)localizedTitleForSaveAllAttachmentsAction;
- (_Bool)canSaveAllAttachmentsInContext:(int)arg1;
- (void)_getNumberOfImages:(unsigned long long *)arg1 videos:(unsigned long long *)arg2 undownloaded:(unsigned long long *)arg3;
- (void)_promptForLoadingRestOfMessageWithHandler:(id)arg1;
- (void)_promptForIncludingAttachmentsWithResponseAction:(unsigned long long)arg1 handler:(id)arg2;
- (void)_handleResponseAction:(unsigned long long)arg1 forMessage:(id)arg2 options:(unsigned long long)arg3;
- (id)keyCommands;
- (void)_composeViewDidShow:(id)arg1;
- (void)_accessibilityButtonShapesWereEnabled:(id)arg1;
- (void)_updateMailboxButtonWithTitle:(id)arg1;
- (id)_arrowControlsView;
- (void)arrowControlsView:(id)arg1 didTapButtonWithDirection:(int)arg2;
- (void)_selectNextMessageWithDirection:(int)arg1;
- (void)updateTitleAndNavigationArrows;
- (_Bool)_traitCollectionIsShortWideLayout:(id)arg1;
- (_Bool)_hasShortWideLayout;
- (_Bool)_traitCollectionIsLargeLayout:(id)arg1;
- (_Bool)_hasLargeLayout;
- (void)_trashAnimationNextMessageTransitionDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_trashAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_startTrashAnimationWithDuration:(double)arg1;
- (void)_commitTrashAnimation;
- (void)_prepareTrashAnimation;
- (void)_reallyDeleteVisibleMessage;
- (struct UIEdgeInsets)_intendedViewContentInset;
- (id)_snapshotOfCurrentMessageContentAreaLayer:(_Bool)arg1;
- (void)beginReallyDeletingVisibleMessage;
- (void)_endIgnoringInteractionEventsForMessageRemovalAnimation;
- (void)_beginIgnoringInteractionEventsForMessageRemovalAnimation;
@property(readonly) NSUndoManager *undoManager; // @dynamic undoManager;
- (void)saveHTMLString:(id)arg1;
- (void)markConversationContainingMessage:(id)arg1 shouldNotify:(_Bool)arg2;
- (void)_markMessage:(id)arg1 asJunk:(_Bool)arg2;
- (void)markMessageAsUnflagged:(id)arg1;
- (void)markMessageAsFlagged:(id)arg1;
- (void)markMessageAsRead:(id)arg1;
- (void)markMessageAsUnread:(id)arg1;
- (void)replyShortcutInvoked:(id)arg1;
- (void)deleteShortcutInvoked:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)replyButtonClicked:(id)arg1;
- (void)deleteButtonAction:(id)arg1 showChoices:(_Bool)arg2;
- (void)deleteButtonLongPressed:(id)arg1;
- (void)deleteButtonClicked:(id)arg1;
- (void)transferCancelButtonClicked:(id)arg1;
- (void)transferButtonClicked:(id)arg1;
- (id)_selectedMessages;
- (void)markButtonClicked:(id)arg1;
- (long long)positionForBar:(id)arg1;
- (void)_updateToolbarButtonsForTraitCollection:(id)arg1 displayMode:(long long)arg2 animated:(_Bool)arg3 force:(_Bool)arg4;
- (void)_updateToolbarButtonsForTraitCollection:(id)arg1 animated:(_Bool)arg2;
- (id)_separatorWithWidth:(double)arg1;
- (void)splitViewControllerWillChangeToDisplayMode:(long long)arg1;
- (void)updateToolbarButtonsAnimated:(_Bool)arg1;
@property(readonly, nonatomic, getter=isInCombinedInbox) _Bool inCombinedInbox;
- (void)updateMailboxInfo;
- (id)additionalActivitiesForDocumentInteractionController:(id)arg1;
- (id)excludedActivityTypesForDocumentInteractionController:(id)arg1;
- (_Bool)shouldBlockRemoteImagesInPreviewForDocumentInteractionController:(id)arg1;
- (id)documentInteractionControllerTransitionImageForPreview:(id)arg1 contentRect:(struct CGRect *)arg2;
- (id)documentInteractionControllerViewForPreview:(id)arg1;
- (struct CGRect)documentInteractionControllerRectForPreview:(id)arg1;
- (id)documentInteractionControllerURLOfDirectoryForUnzippedDocument:(id)arg1;
- (id)documentInteractionControllerViewControllerForPreview:(id)arg1;
- (void)documentInteractionControllerDidEndPreview:(id)arg1;
- (void)documentInteractionControllerWillBeginPreview:(id)arg1;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)arg1;
- (void)documentInteractionControllerWillPresentOpenInMenu:(id)arg1;
- (void)documentInteractionControllerDidDismissOptionsMenu:(id)arg1;
- (void)documentInteractionControllerWillPresentOptionsMenu:(id)arg1;
- (void)promptToReplaceCurrentCertificateWithBlock:(id)arg1;
- (void)promptOrInstallCertificationWithBlock:(id)arg1;
- (void)refreshCertificateViewControllerStatus;
- (void)installCertificateWithTrustException:(_Bool)arg1;
- (void)performCertificateActionInstall;
- (void)performCertificateActionTrustAndInstall;
- (void)performCertificateActionRemove;
- (void)updateCertificateAction;
- (_Bool)_certificateIsStoredInKeychain;
- (void)_certificateControllerDidFinish;
- (void)_showCertificate:(id)arg1;
- (void)_addVIPButtonToController:(id)arg1;
- (void)_addVIP:(id)arg1;
- (void)_removeVIP:(id)arg1;
- (void)_preferredContentSizeDidChange:(id)arg1;
- (void)_relayoutHeaderView;
- (void)_updatePersonCard;
- (void)_trustDidChange;
- (void)_removeTrustException:(id)arg1;
- (void)_addTrustException:(id)arg1;
- (void)_configureSecureMIMEPersonHeaderView:(id)arg1 withButtonFactory:(id)arg2;
- (void)_setupHeaderForContactCardViewController:(id)arg1;
- (_Bool)_shouldShowContactHeaderForCurrentMessageViewingContext;
- (id)_newPersonViewControllerForPerson:(void *)arg1 emailIdentifier:(int)arg2;
- (void)displayViewController:(id)arg1 fromAtom:(id)arg2 allowsEditing:(_Bool)arg3;
- (void)_showContactCardForAddressAtom:(id)arg1 sender:(_Bool)arg2;
- (void)showCardForRecipientAtom:(id)arg1;
- (void)showCardForSenderAtom:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1 isUserAction:(_Bool)arg2;
- (_Bool)unknownPersonViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)personViewController:(id)arg1 willSetEditing:(_Bool)arg2 animated:(_Bool)arg3;
- (_Bool)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (void)eventViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (void)displayMultipleCallsToAction:(id)arg1 sender:(id)arg2;
- (void)ignoredAction:(id)arg1 sender:(id)arg2;
- (void)confirmedAction:(id)arg1 sender:(id)arg2;
- (void)displayEventSuggestion:(id)arg1 sender:(id)arg2;
- (void)showActionSheetForCanceledEvent:(id)arg1 sender:(id)arg2;
- (void)presentEventEditViewForEvent:(id)arg1 sender:(id)arg2;
- (void)displayContactSuggestion:(id)arg1 sender:(id)arg2;
- (void)clearSuggestionsBanners;
- (void)showMenuForSelectedAttachment:(id)arg1;
- (id)_createDocumentInteractionControllerForAttachment:(id)arg1 withData:(id)arg2;
- (void)showSelectedAttachment:(id)arg1;
- (id)topMessageViewController;
- (void)unloadViewIfReloadable;
- (void)didReceiveMemoryWarning;
- (void)_purgeMessageLayer;
- (void)_meetingInformationInvalidNote:(id)arg1;
- (void)hideModalViewController:(id)arg1;
- (void)showModalViewController:(id)arg1 fromView:(id)arg2 allowsEdit:(_Bool)arg3;
- (id)composeView;
- (id)messageContentAreaLayer;
- (id)currentMessage;
- (void)displayMessage:(id)arg1 immediately:(_Bool)arg2;
- (void)_displayMessageWithViewingContext:(id)arg1 options:(unsigned long long)arg2;
- (void)_messageDisplayDidFinish;
- (void)messageViewingContextMessageAnalysisCompleted:(id)arg1;
- (void)_addBannersForMessage:(id)arg1 animated:(_Bool)arg2;
- (_Bool)isSuggestionsLoggingEnabled;
- (void)dataDetectorsDidFinishURLification:(id)arg1;
- (void)_contentAnalysisDidTimeout;
- (void)messageContentAreaLayerDidDraw:(id)arg1;
- (void)_flushMessageLayerBuffer;
- (void)_prepareMessageLayerBuffer;
- (id)_hostingViewController;
- (struct CGSize)minimumSizeOfWebLayerControlledByScroller:(id)arg1;
- (id)webLayerControlledByScroller:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)applicationSceneController:(id)arg1 willTransitionToTraitCollection:(id)arg2 withTransitionCoordinator:(id)arg3;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)mailboxContentViewController;
@property(readonly, nonatomic, getter=isDisplayingDraft) _Bool displayingDraft;
- (id)passthroughViews;
- (void)unreadCountChanged:(id)arg1;
- (void)_applicationSuspended:(id)arg1;
- (void)applicationDidResume;
- (void)applicationWillSuspend;
- (void)setContentAreaNeedsRefold;
- (void)setLandscapeThreadNavigationEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_suspendView;
- (void)suspendViewAfterDelay;
- (void)resumeView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)_suspend;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)loadView;
- (_Bool)canBecomeFirstResponder;
- (_Bool)usePadDisplayStyle;
- (void)_clearController;
- (void)dealloc;
- (id)initWithDisplayStyle:(int)arg1;
- (id)init;
- (_Bool)_isSharedController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

