/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageMiniMallObserver.h"
#import "MessageSelectionDataSource.h"

@class MFActivityMonitor, MFMailMessage, MessageSelectionStrategy, NSDictionary, NSIndexSet, NSMutableArray, NSString, SourceSearchContext;

@interface MessageMegaMall : NSObject <MessageMiniMallObserver, MessageSelectionDataSource>
{
    int _lock;
    NSMutableArray *_malls;
    NSIndexSet *_sectionsNeedingVisibleMailboxNames;
    NSDictionary *_maximumIndexPathsBySource;
    struct __CFDictionary *_sourceShouldGrowCache;
    MessageSelectionStrategy *_selectionStrategy;
    id _comparator;
    SourceSearchContext *_searchContext;
    unsigned long long _searchOptions;
    MFActivityMonitor *_fetchActivity;
    struct __CFDictionary *_growingMailboxesByActivity;
    int _lastChangeDirection;
    MFMailMessage *_currentMessage;
    id _context;
}

+ (id)messageInfosTransformForConversationID:(SEL)arg1;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(nonatomic) int lastChangeDirection; // @synthesize lastChangeDirection=_lastChangeDirection;
@property(retain, nonatomic) MFMailMessage *currentMessage; // @synthesize currentMessage=_currentMessage;
- (void)_dumpDiagnosticInformation:(id)arg1;
- (void)miniMallDidFinishSearch:(id)arg1;
- (void)miniMallDidLoadMessages:(id)arg1;
- (void)miniMallCurrentMessageRemoved:(id)arg1;
- (void)miniMallStartFetch:(id)arg1;
- (void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
- (void)miniMallMessageCountChanged:(id)arg1;
- (id)noMessagesTextForSection:(long long)arg1;
- (id)titleWithUnreadCount:(unsigned long long)arg1 options:(unsigned long long)arg2;
- (_Bool)shouldShowMailboxNameForMessage:(id)arg1;
- (void)setSectionsNeedingVisibleMailboxNames:(id)arg1;
- (_Bool)allSourcesThreadMessages;
- (unsigned long long)sourceType;
- (_Bool)isInCombinedInbox;
- (_Bool)shouldPopOnZeroMessages;
- (_Bool)shouldArchiveByDefaultForTableIndexPath:(id)arg1;
- (_Bool)supportsArchivingForTableIndexPath:(id)arg1;
- (_Bool)deleteMovesToTrashForTableIndexPath:(id)arg1;
- (_Bool)archiveByDefaultForMessage:(id)arg1;
- (_Bool)archivesByDefault;
- (_Bool)supportsArchivingForMessage:(id)arg1;
- (_Bool)supportsArchiving;
- (_Bool)deleteMovesToTrashForMessage:(id)arg1;
- (_Bool)deleteMovesToTrash;
- (id)_copyMalls;
- (void)cancelSearchInMallAtIndex:(unsigned long long)arg1;
- (void)performSearchInMallAtIndex:(unsigned long long)arg1;
- (void)cancelSearch;
- (_Bool)prepareSearchUsingContext:(id)arg1 options:(unsigned long long)arg2;
- (_Bool)hasSearchCriterion;
- (void)moveAllMessagesToMailbox:(id)arg1;
- (void)transferMessages:(id)arg1 toMailbox:(id)arg2;
- (void)markMessagesAsViewed:(id)arg1;
- (void)markMessagesAsNotViewed:(id)arg1;
- (void)markMessagesAsFlagged:(id)arg1;
- (void)markMessagesAsNotFlagged:(id)arg1;
- (void)markMessagesAsJunk:(id)arg1;
- (void)markMessagesAsNotJunk:(id)arg1;
- (void)markAllMessagesAsViewed;
- (void)markAllMessagesAsNotViewed;
- (void)markAllMessagesAsFlagged;
- (void)markAllMessagesAsNotFlagged;
- (void)markAllMessagesAsDeletedOrArchived:(unsigned long long)arg1;
- (void)markMessages:(id)arg1 inSection:(unsigned long long)arg2 asDeletedOrArchived:(unsigned long long)arg3;
- (void)markMessages:(id)arg1 asDeletedOrArchived:(unsigned long long)arg2;
- (void)_enumerateMessagesBySection:(id)arg1 enumerator:(id)arg2;
- (void)_filterTaskCompleted;
- (void)_addChangeSetToManager:(id)arg1;
- (unsigned long long)unreadCountForDisplay;
- (_Bool)shouldShowUnreadCount;
- (unsigned long long)localMessageCount;
- (unsigned long long)messageCount;
- (unsigned long long)messageCountForSection:(unsigned long long)arg1;
- (unsigned long long)sectionCount;
- (unsigned long long)mallCount;
- (id)titleForHeaderInSection:(long long)arg1;
- (void)_currentMessageRemovedWithMessageToSelect:(id)arg1;
- (id)messageToSelectAfterDeletedMessages:(id)arg1;
- (id)messageToSelectAfterDeletedMessage:(id)arg1;
- (id)messageToSelectFromMessage:(id)arg1 withDirection:(int)arg2;
- (id)defaultMessageIncludingUnread:(_Bool)arg1;
- (id)messageForMessageID:(id)arg1;
@property(retain, nonatomic) MFMailMessage *lastViewedMessage;
- (id)tableIndexPathOfFlattenedCurrentMessage;
- (id)tableIndexPathOfConversationContainingMessageInfo:(id)arg1;
- (id)tableIndexPathOfConversationContainingMessage:(id)arg1;
- (id)tableIndexPathOfMessageOrConversation:(id)arg1;
- (id)flattenedIndexPathOfMessage:(id)arg1;
- (id)messageAtFlattenedIndex:(unsigned long long)arg1;
- (unsigned long long)flattenedIndexOfWhereMessageShouldGo:(id)arg1;
- (unsigned long long)flattenedIndexOfMessage:(id)arg1;
- (id)messageInfosForConversationID:(long long)arg1;
- (id)allMessagesForConversation:(long long)arg1;
- (id)bulletinsContexts;
- (id)messageForMessageInfo:(id)arg1;
- (id)copyAllMessages;
- (id)conversationContainingMessage:(id)arg1;
- (id)tableIndexPathOfConversationWithID:(long long)arg1 preferredSection:(unsigned long long)arg2;
- (id)tableIndexPathOfMessage:(id)arg1;
- (void)getIndex:(unsigned long long *)arg1 andCount:(unsigned long long *)arg2 ofMessageInConversation:(id)arg3;
- (unsigned long long)messageCountForConversationWithMessage:(id)arg1;
- (unsigned long long)messageCountAtTableIndexPath:(id)arg1;
- (id)supplementaryRelatedSourcesForMessage:(id)arg1;
- (id)sourcesForMessagesAtTableIndexPath:(id)arg1;
- (id)messageInfosAtTableIndexPath:(id)arg1;
- (id)messagesAtTableIndexPath:(id)arg1;
- (id)messageAtTableIndexPath:(id)arg1;
- (void)getSourceStateHasUnread:(_Bool *)arg1 hasUnflagged:(_Bool *)arg2;
- (void)getConversationStateAtTableIndexPath:(id)arg1 hasUnread:(_Bool *)arg2 hasUnflagged:(_Bool *)arg3;
- (void)updateEntry:(id)arg1 atTableIndexPath:(id)arg2 addressList:(id *)arg3 options:(unsigned long long)arg4;
- (id)_megaMallIndexPathsFromIndexPaths:(id)arg1 baseSection:(unsigned long long)arg2;
- (id)_megaMallIndexPathFromIndexPath:(id)arg1 baseSection:(long long)arg2;
- (id)_miniMallIndexPathFromIndexPath:(id)arg1 baseSection:(long long)arg2;
- (id)_nts_mallForSection:(long long)arg1 baseSection:(long long *)arg2;
- (id)_mallForSection:(long long)arg1 baseSection:(long long *)arg2;
@property(copy, nonatomic) id comparator;
- (id)comparatorForMallContainingMessage:(SEL)arg1;
- (id)_nts_comparator;
- (unsigned long long)_indexOfMiniMall:(id)arg1;
- (unsigned long long)_baseSectionForMiniMall:(id)arg1;
- (id)_mallForMessageInfo:(id)arg1;
- (void)loadMoreMessagesWithMaxVisibleIndexPath:(id)arg1;
- (void)_loadMoreMessagesWithMaxVisibleIndexPath:(id)arg1 maximumIndexPathsBySource:(id)arg2;
- (void)loadOlderMessages;
- (void)growFetchWindowForSources:(id)arg1;
- (_Bool)shouldGrowFetchWindowForSource:(id)arg1;
- (id)maximumIndexPathsBySource;
- (void)_invalidateMaximumIndexPathsBySource;
- (_Bool)isGrowingFetchWindowForSource:(id)arg1;
- (_Bool)isGrowingFetchWindowForAnySourceInSection:(long long)arg1;
- (_Bool)_nts_isGrowingFetchWindowForAnySourceInSection:(long long)arg1;
- (id)_nts_growingMailboxActivityMonitorForSource:(id)arg1;
- (void)_cancelGrowingMailboxes;
- (void)_notifyGrowingMailboxesChanged;
- (id)currentRemoteIDForMailbox:(id)arg1;
- (void)_fetchCompleted:(id)arg1;
- (void)_clearFetchActivity;
- (void)trackFetchVisibleMailbox:(id)arg1 activity:(id)arg2 options:(unsigned long long)arg3;
- (id)sourceForMailbox:(id)arg1;
- (id)sourcesBySection;
- (id)sourcesForSection:(unsigned long long)arg1;
- (id)sources;
- (void)removeAllSources;
- (void)addSource:(id)arg1 toSection:(unsigned long long)arg2;
- (void)flushCaches;
- (void)applicationDidResume;
- (void)applicationWillSuspend;
- (void)resume;
- (void)suspend;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithObserver:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

