/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MessageFoldViewDelegate <NSObject>

@optional
- (void)messageFoldView:(id)arg1 didUpdateFoldWithProgress:(double)arg2 fadeInAlpha:(double)arg3;
@end

