/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MessageCallToAction.h"

@class NSError, NSString;

@interface MessageCallToActionError : MessageCallToAction
{
    NSString *_title;
    NSError *_error;
}

+ (id)callToActionWithTitle:(id)arg1 forError:(id)arg2;
@property(readonly, retain, nonatomic) NSError *error; // @synthesize error=_error;
- (id)secondaryActionTitle;
- (id)primaryActionTitle;
- (id)subtitle;
- (id)title;
- (id)bundleIdentifier;
- (long long)compare:(id)arg1;
- (void)dealloc;

@end

