/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MessageFoldDelegate <NSObject>

@optional
- (void)messageFoldManagerDidUnfoldMessage:(id)arg1;
- (void)messageFoldManager:(id)arg1 didUpdateFoldWithProgress:(double)arg2 fadeInAlpha:(double)arg3;
- (void)messageFoldManager:(id)arg1 willFoldMessageWithContentOffset:(struct CGPoint)arg2;
@end

