/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageSelectionStrategy : NSObject
{
    id <MessageSelectionDataSource> _dataSource;
}

- (id)messageToSelectFromMessage:(id)arg1 withDirection:(int)arg2;
- (id)messageToSelectAfterDeletedMessages:(id)arg1;
- (id)initWithDataSource:(id)arg1;
- (id)init;

@end

