/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UINavigationController.h"

@class MessageViewController;

@interface MessageAttachmentNavigationController : UINavigationController
{
    MessageViewController *_parentMessageViewController;
}

@property(nonatomic) MessageViewController *parentMessageViewController; // @synthesize parentMessageViewController=_parentMessageViewController;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentModalViewController:(id)arg1 animated:(_Bool)arg2;

@end

