/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageToMailboxUidCache : NSObject
{
    struct __CFDictionary *_mailboxCache;
}

- (unsigned long long)count;
- (void)removeAllObjects;
- (id)mailboxForMessage:(id)arg1;
- (void)dealloc;
- (id)init;

@end

