/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIActivity.h"

@class MFAttachment, MessageContentLayer;

@interface MessageQuicklookImageAttachmentsActivity : UIActivity
{
    MessageContentLayer *_contentLayer;
    MFAttachment *_attachment;
    unsigned long long _index;
}

- (void)_cleanup;
- (void)performActivity;
- (id)_beforeActivity;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;
- (id)initWithContentLayer:(id)arg1 attachment:(id)arg2 index:(unsigned long long)arg3;

@end

