/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIPrintPageRenderer.h"

#import "MFMessageViewingContextDelegate.h"
#import "UIPrintInteractionControllerDelegate.h"

@class MFMailMessage, MFMessageViewingContext, MFMessageWebLayer, MessageContentLayer, NSString, UIImage, UIViewPrintFormatter, UIWebDocumentView;

@interface MessagePrinter : UIPrintPageRenderer <UIPrintInteractionControllerDelegate, MFMessageViewingContextDelegate>
{
    MFMailMessage *_message;
    MFMessageWebLayer *_messageBodyView;
    UIWebDocumentView *_messageHeaderView;
    MessageContentLayer *_messageContentLayer;
    MFMessageViewingContext *_viewingContext;
    UIViewPrintFormatter *_headerFormatter;
    UIViewPrintFormatter *_bodyFormatter;
    UIImage *_contactPhoto;
    double _headerLastPageHeight;
    _Bool _headerLoaded;
    _Bool _viewingContextLoaded;
    _Bool _printableContentLoaded;
}

- (void)drawPageAtIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (void)drawContentForPageAtIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (long long)numberOfPages;
- (void)_initializePrintableContent;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)messageViewingContextContentLoadCompleted:(id)arg1;
- (struct CGRect)_printingRectForImageableRect:(struct CGRect)arg1;
- (void)printInteractionControllerDidDismissPrinterOptions:(id)arg1;
- (void)printInteractionControllerWillPresentPrinterOptions:(id)arg1;
- (void)presentPrintSheet;
- (void)presentPrintPopoverFromBarButtonItem:(id)arg1;
- (id)initWithMailMessage:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

