/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MessageMiniMallObserver
- (void)miniMallDidFinishSearch:(id)arg1;
- (void)miniMallDidLoadMessages:(id)arg1;
- (void)miniMallCurrentMessageRemoved:(id)arg1;
- (void)miniMallStartFetch:(id)arg1;
- (void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
- (void)miniMallMessageCountChanged:(id)arg1;
@end

