/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFApplicationSceneDelegate <NSObject>

@optional
- (id)dummyViewWithFrame:(struct CGRect)arg1 forResurrectionIdentifier:(id)arg2;
- (struct UIViewController *)actorViewControllerForResurrectionIdentifier:(id)arg1;
- (id)resurrectionIdentifierForPurgingActorViewController:(struct UIViewController *)arg1;
- (_Bool)shouldPurgeActorViewController:(struct UIViewController *)arg1;
- (void)applicationSceneController:(id)arg1 didClosePurgedViewControllerWithResurrectionIdentifier:(id)arg2;
- (void)applicationSceneController:(id)arg1 didCloseViewController:(struct UIViewController *)arg2;
- (void)applicationSceneController:(id)arg1 didWithdrawActiveViewController:(struct UIViewController *)arg2;
- (void)applicationSceneController:(id)arg1 didMakeViewControllerActive:(struct UIViewController *)arg2;
@end

