/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFApplicationSceneActor <NSObject>

@optional
- (id)withdrawlGestureExclusionRects;
- (id)localizedIdentificationString;
- (void)didResurrectWithResurrectionIdentifier:(id)arg1;
- (void)prepareToBePurged;
- (void)didBecomeActiveSceneActor;
- (void)willBecomeActiveSceneActor;
- (void)wasWithdrawnAsActiveSceneActor;
- (void)prepareToBeWithdrawnAsActiveSceneActor;
@end

