/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface MFDelayedMessagesPresenter : NSObject
{
    NSObject<OS_dispatch_queue> *_fireQueue;
    NSObject<OS_dispatch_source> *_fireSource;
    NSMutableArray *_pendingMessages;
    double _postingDelay;
}

@property(nonatomic) double postingDelay; // @synthesize postingDelay=_postingDelay;
- (void)postMessage:(id)arg1 identifier:(id)arg2 immediately:(_Bool)arg3 fireBlock:(id)arg4;
- (void)removePendingMessagesWithIdentifiers:(id)arg1;
- (void)clearPendingMessages;
- (void)_nts_scheduleNextFireEvent;
- (void)setTargetQueue:(id)arg1;
- (void)dealloc;
- (id)init;

@end

