/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MSSearch.h"

#import "MFSearchResultHandler.h"
#import "MSDSearchProtocol.h"
#import "QueryProgressMonitor.h"

@class MFActivityMonitor, MFMessageCriterion, MFMessageResultsGenerator, MFWeakReferenceHolder, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSString;

@interface MFDSearch : MSSearch <QueryProgressMonitor, MFSearchResultHandler, MSDSearchProtocol>
{
    NSObject<OS_dispatch_group> *_searchResultsGroup;
    NSObject<OS_dispatch_queue> *_searchResultsQueue;
    MFWeakReferenceHolder *_weakClient;
    MFActivityMonitor *_monitor;
    MFMessageCriterion *_criteria;
    id <MFMessageIterationFilter> _filter;
    unsigned long long _options;
    MFMessageResultsGenerator *_generator;
}

+ (id)endpointInfo;
@property(retain, nonatomic) MFMessageResultsGenerator *generator; // @synthesize generator=_generator;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) id <MFMessageIterationFilter> filter; // @synthesize filter=_filter;
@property(retain, nonatomic) MFMessageCriterion *criteria; // @synthesize criteria=_criteria;
- (unsigned int)_libraryOptions;
- (void)handleMessage:(id)arg1;
- (void)_backgroundSearchWithCriterion:(id)arg1 filter:(id)arg2;
- (void)endResult;
- (void)setResultUnread:(_Bool)arg1;
- (void)setResultDateRecieved:(double)arg1;
- (void)setResultSender:(char *)arg1;
- (void)setResultSubject:(char *)arg1;
- (void)beginResult:(unsigned int)arg1;
- (_Bool)shouldCancel;
- (void)stop;
- (void)start;
- (void)_autoFetchDone:(id)arg1;
- (void)_registerForAutoFetchFinishedNotification;
- (_Bool)_hasSearchableMailAccount;
- (id)generatorWithKeys:(id)arg1;
- (void)findMessageData:(id)arg1 matchingCriterion:(id)arg2 options:(unsigned long long)arg3;
- (id)_searchResultsProxy;
- (id)_remoteObjectProxyWithErrorHandler:(id)arg1;
- (void)dealloc;
- (id)initWithClient:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

