/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MSSuggestionsHints.h"

#import "MSDSuggestionsHintsProtocol.h"

@class NSString;

@interface MFDSuggestionsHints : MSSuggestionsHints <MSDSuggestionsHintsProtocol>
{
}

+ (id)sharedInstance;
+ (id)endpointInfo;
- (void)requestRichDownloadOfMessagesWithReferences:(id)arg1;
- (void)extendLifetimeOfMessagesWithReferences:(id)arg1;
- (id)_remoteObjectProxyWithErrorHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

