/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewDelegate.h"

@protocol MFMailboxTableViewDelegate <UITableViewDelegate>

@optional
- (void)tableView:(id)arg1 tappedSwipeAction:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (void)tableView:(id)arg1 performSwipeAction:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willPerformSwipeAction:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForSwipeAction:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (unsigned long long)tableView:(id)arg1 secondaryActionForCellEdge:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (unsigned long long)tableView:(id)arg1 primaryActionForCellEdge:(unsigned long long)arg2 atIndexPath:(id)arg3;
@end

