/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "BBRemoteDataProvider.h"
#import "MFMessageBulletinsObserverDelegate.h"

@class BBDataProviderConnection, BBDataProviderProxy, MFDelayedMessagesPresenter, MFMailDataProviderAutoFetchData, MFMessageBulletinsObserver, NSArray, NSLock, NSMutableArray, NSMutableSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

@interface MFMailDataProvider : NSObject <MFMessageBulletinsObserverDelegate, BBRemoteDataProvider>
{
    MFMessageBulletinsObserver *_bulletinsObserver;
    BBDataProviderConnection *_connection;
    BBDataProviderProxy *_proxy;
    NSArray *_accounts;
    NSMutableSet *_accountsUsingExternalSync;
    MFDelayedMessagesPresenter *_delayedMessages;
    NSObject<OS_dispatch_queue> *_queue;
    NSLock *_lock;
    NSLock *_accountIDsOfSoundsToPlayLock;
    NSMutableArray *_accountIDsOfSoundsToPlay;
    NSObject<OS_dispatch_semaphore> *_accountIDsOfSoundsToPlayWait;
    NSMutableArray *_pushFetchTimestamps;
    NSLock *_pushFetchTimestampsLock;
    MFMailDataProviderAutoFetchData *_autoFetchData;
    unsigned long long _autoFetchPushCount;
    unsigned long long _accountIDsOfSoundsToPlayWaitTimeoutTS;
}

@property unsigned long long accountIDsOfSoundsToPlayWaitTimeoutTS; // @synthesize accountIDsOfSoundsToPlayWaitTimeoutTS=_accountIDsOfSoundsToPlayWaitTimeoutTS;
@property unsigned long long autoFetchPushCount; // @synthesize autoFetchPushCount=_autoFetchPushCount;
@property(retain) MFMailDataProviderAutoFetchData *autoFetchData; // @synthesize autoFetchData=_autoFetchData;
- (void)notificationService:(id)arg1 didChangeAccounts:(id)arg2 error:(id)arg3;
- (void)messagesInvalidatedForNotificationService:(id)arg1;
- (void)notificationService:(id)arg1 didRemoveMessageIds:(id)arg2;
- (void)notificationService:(id)arg1 didFetchSummaryForMessages:(id)arg2;
- (void)notificationService:(id)arg1 didFetchMessages:(id)arg2;
- (void)addSoundToRequestIfNeeded:(id)arg1;
- (void)protectedDataBecameAvailableForNotificationService:(id)arg1;
- (void)invalidateSectionParametersForNotificationService:(id)arg1;
- (void)_autoFetchPushFinished:(id)arg1;
- (void)_autoFetchPushStarted:(id)arg1;
- (void)_autoFetchFinished:(id)arg1;
- (void)_fetchFinished:(id)arg1 timestamp:(unsigned long long)arg2;
- (void)_autoFetchJobCompleted:(id)arg1;
- (void)_fetchJobCompleted:(id)arg1 autoFetchData:(id)arg2;
- (void)_autoFetchStarted:(id)arg1;
- (_Bool)migrateSectionInfo:(id)arg1 oldSectionInfo:(id)arg2;
- (id)displayNameForSubsectionID:(id)arg1;
- (id)defaultSubsectionInfos;
- (id)defaultSectionInfo;
- (id)sectionParameters;
- (id)universalSectionIdentifier;
- (id)sectionIdentifier;
- (id)sortDescriptors;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned long long)arg1 lastClearedInfo:(id)arg2;
- (id)_mutableMigratedClearedInfoWithClearedInfo:(id)arg1;
- (id)_currentClearedInfoVersion;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (_Bool)syncsBulletinDismissal;
- (void)_swipeActionsChanged:(id)arg1;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)bulletinRequestForMessage:(id)arg1 showsLoading:(_Bool)arg2;
- (void)_nts_setAccounts:(id)arg1 shouldCache:(_Bool)arg2;
@property(retain) NSArray *accounts;
- (_Bool)usingExternalSyncForAccountWithID:(id)arg1;
- (void)_nts_recalculateAccountsUsingExternalSync;
- (id)_copyCachedAccounts;
- (void)_cacheAccounts:(id)arg1;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

