/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMailAttachmentPlugInDelegate <NSObject>

@optional
- (void)attachment:(id)arg1 displayMenuFromRect:(struct CGRect)arg2 iconRect:(struct CGRect)arg3 inView:(id)arg4;
- (void)attachment:(id)arg1 displayViewerFromRect:(struct CGRect)arg2 inView:(id)arg3;
- (void)displayAttachmentTooLargeAlert;
- (_Bool)isAttachmentDownloadable:(id)arg1;
- (void)startDownloadAndSaveToCameraRollForAttachment:(id)arg1 withDownloadProgress:(id)arg2;
- (void)attachment:(id)arg1 didFinishDownloadWithProgress:(id)arg2;
- (void)attachment:(id)arg1 cancelDownloadWithProgress:(id)arg2;
- (void)attachment:(id)arg1 startDownloadWithProgress:(id)arg2 group:(id)arg3 userInitiated:(_Bool)arg4;
- (id)attachment:(id)arg1 iconForSize:(struct CGSize)arg2;
@end

