/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MessageViewController.h"

@interface MFMessageAttachmentViewController : MessageViewController
{
    id <MFAttachmentDataProvider> _provider;
}

@property(retain, nonatomic) id <MFAttachmentDataProvider> provider; // @synthesize provider=_provider;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;

@end

