/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMessageContentDisplayDelegate <NSObject>
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)showCardForSenderAtom:(id)arg1;
- (void)showCardForRecipientAtom:(id)arg1;
@end

