/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMessageBulletinsObserverDelegate <NSObject>
- (void)notificationService:(id)arg1 didRemoveMessageIds:(id)arg2;
- (void)notificationService:(id)arg1 didFetchSummaryForMessages:(id)arg2;
- (void)notificationService:(id)arg1 didFetchMessages:(id)arg2;
- (void)notificationService:(id)arg1 didChangeAccounts:(id)arg2 error:(id)arg3;
- (void)invalidateSectionParametersForNotificationService:(id)arg1;
- (void)messagesInvalidatedForNotificationService:(id)arg1;
- (void)protectedDataBecameAvailableForNotificationService:(id)arg1;
@end

