/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMessageWebLayerDelegate <NSObject>
- (id)messageWebLayer:(id)arg1 attachmentsWithURLs:(id)arg2;
- (void)messageWebLayer:(id)arg1 openURL:(id)arg2;
- (void)messageWebLayer:(id)arg1 didFailToPaintAttachmentURL:(id)arg2;
- (void)messageWebLayerDidFirstVisuallyNonEmptyLayout:(id)arg1;
- (void)messageWebLayerDidFinishTweaking:(id)arg1;
- (void)messageWebLayerDidFinishLoading:(id)arg1;
- (void)messageWebLayer:(id)arg1 didDrawTileAtBounds:(struct CGRect)arg2;
- (struct CGRect)messageWebLayer:(id)arg1 newFrameForRect:(struct CGRect)arg2;
- (void)messageWebLayer:(id)arg1 sizeDidChange:(struct CGSize)arg2;

@optional
- (void)messageWebLayer:(id)arg1 didFindBottomReplyRange:(id)arg2 lastQuoteLevel:(unsigned long long)arg3;
@end

