/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFMessage.h"

@interface MFMessage (NSURL_MobileMail)
- (id)mf_conversationReference;
- (id)mf_externalReference;
@end

