/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFMessageViewingContextDelegate <NSObject>

@optional
- (void)messageViewingContext:(id)arg1 attachmentLoadCompleted:(id)arg2 withData:(id)arg3;
- (void)messageViewingContext:(id)arg1 attachmentLoadCompleted:(id)arg2;
- (void)messageViewingContextMessageAnalysisCompleted:(id)arg1;
- (void)messageViewingContextContentLoadCompleted:(id)arg1;
- (void)messageViewingContextFullMessageLoadFailed:(id)arg1;
- (void)messageViewingContextContentLoadWillBegin:(id)arg1;
@end

