/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFSearchAlternativesGenerator.h"

@interface MFSearchAlternativesAttachmentsGenerator : MFSearchAlternativesGenerator
{
}

- (void)generateAlternativesForPhrase:(id)arg1 withHandler:(id)arg2;

@end

