/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MFSearchResultHandler
- (void)endResult;
- (void)setResultUnread:(_Bool)arg1;
- (void)setResultDateRecieved:(double)arg1;
- (void)setResultSender:(char *)arg1;
- (void)setResultSubject:(char *)arg1;
- (void)beginResult:(unsigned int)arg1;

@optional
- (id)filter;
- (void)handleMessage:(id)arg1;
- (void)setResultSummary:(char *)arg1;
@end

