/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFSearchAlternative.h"

@class NSSet, NSString;

@interface MFSearchAlternativePerson : MFSearchAlternative
{
    NSString *_displayName;
    NSSet *_addresses;
}

+ (id)alternativeWithDisplayName:(id)arg1 addresses:(id)arg2;
- (id)criterion;
- (int)_criterionType;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithDisplayName:(id)arg1 addresses:(id)arg2;

@end

