/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFSearchAlternativesManagerDelegate <NSObject>
- (void)alternativesManager:(id)arg1 finishedWithIdentifier:(id)arg2;
- (void)alternativesManager:(id)arg1 foundAlternatives:(id)arg2 forIdentifier:(id)arg3;
@end

