/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class MFMessageCriterion, NSString;

@interface MFSearchAlternative : NSObject
{
    MFMessageCriterion *_criterion;
    NSString *_identifier;
    struct _NSRange _range;
}

+ (id)alternative;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, retain, nonatomic) MFMessageCriterion *criterion;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)init;

@end

