/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFSearchAlternativesGenerator.h"

@class NSArray, NSRegularExpression;

@interface MFSearchAlternativesTimePeriodGenerator : MFSearchAlternativesGenerator
{
    NSRegularExpression *_relativeDatesRegularExpression;
    NSArray *_dateFormatters;
}

- (void)generateAlternativesForPhrase:(id)arg1 withHandler:(id)arg2;
- (id)_dateFormatterAlternativesForPhrase:(id)arg1;
- (id)_dateFormatters;
- (id)_addLocalizedFormat:(id)arg1 units:(unsigned long long)arg2 to:(id)arg3 usedFormatStrings:(id)arg4;
- (id)_addFormat:(id)arg1 units:(unsigned long long)arg2 to:(id)arg3 usedFormatStrings:(id)arg4;
- (id)_relativeAlternativesForPhrase:(id)arg1;
- (id)_relativeDatesRegularExpression;
- (void)dealloc;

@end

