/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFSearchAlternative.h"

@class NSDate;

@interface MFSearchAlternativeTimePeriod : MFSearchAlternative
{
    NSDate *_begin;
    NSDate *_end;
}

+ (id)alternativeWithBeginDate:(id)arg1 endDate:(id)arg2;
+ (id)todayAlternative;
+ (id)yesterdayAlternative;
+ (id)lastDayAlternative;
+ (id)lastNightAlternative;
+ (id)lastWeekAlternative;
+ (id)lastMonthAlternative;
+ (id)lastYearAlternative;
+ (id)thisMonthAlternative;
- (id)criterion;
- (id)endDate;
- (id)beginDate;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithBeginDate:(id)arg1 endDate:(id)arg2;

@end

