/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSOperationQueue;

@interface MFSearchAlternativesManager : NSObject
{
    NSMutableDictionary *_activeSearches;
    NSOperationQueue *_queue;
    id <MFSearchAlternativesManagerDelegate> _delegate;
    NSArray *_generators;
}

+ (id)defaultAlternativesGenerators;
@property(copy, nonatomic) NSArray *generators; // @synthesize generators=_generators;
@property(nonatomic) id <MFSearchAlternativesManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_notifyDelegateFinishedWithIdentifier:(id)arg1;
- (void)_notifyDelegateFoundAlternatives:(id)arg1 forIdentifier:(id)arg2;
- (void)cancel;
- (void)cancelAlternativesResolutionWithIdentifier:(id)arg1;
- (id)startAlternativesResolutionForPhrase:(id)arg1;
- (void)dealloc;
- (id)init;

@end

