/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSString;

@interface MFSearchTerm : NSObject
{
    NSString *_token;
    NSData *_sortKey;
}

@property(readonly, retain, nonatomic) NSData *sortKey; // @synthesize sortKey=_sortKey;
@property(readonly, retain, nonatomic) NSString *token; // @synthesize token=_token;
- (_Bool)isPrefixOfSortKey:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithToken:(id)arg1 sortKey:(id)arg2;

@end

