/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CASpringAnimation.h"

@class MFSpringAnimationDelegate;

@interface MFSpringAnimation : CASpringAnimation
{
}

+ (id)springAnimationWithKeyPath:(id)arg1 toLayer:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4;
+ (double)defaultAnimationDuration;
- (void)addCompletionBlock:(id)arg1;
- (id)init;

// Remaining properties
@property(retain, nonatomic) MFSpringAnimationDelegate *delegate;

@end

