/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFSuggestionHandlingDelegate <NSObject>
- (void)displayMultipleCallsToAction:(id)arg1 sender:(id)arg2;
- (void)ignoredAction:(id)arg1 sender:(id)arg2;
- (void)confirmedAction:(id)arg1 sender:(id)arg2;
@end

