/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface MFSwipeActionUtilities : NSObject
{
}

+ (_Bool)isActionDestructive:(unsigned long long)arg1;
+ (id)defaultColorForSwipeAction:(unsigned long long)arg1;
+ (unsigned long long)swipeActionForActionKey:(id)arg1;

@end

