/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "_UIBasicAnimationFactory.h"

@class CADisplayLink, NSArray, NSMutableArray, NSMutableSet, NSString, UIImage, UILongPressGestureRecognizer, UIMotionEffectGroup, UIPanGestureRecognizer, UIScrollView, UITapGestureRecognizer, _MFTiltedTabItem, _MFTouchDownTapRecognizer, _TabGradientView;

@interface MFTiltedTabView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate, _UIBasicAnimationFactory>
{
    _Bool _presented;
    _Bool _sentDidDismissToDelegate;
    _Bool _sentDidPresentToDelegate;
    UIPanGestureRecognizer *_tabCloseRecognizer;
    UILongPressGestureRecognizer *_tabReorderRecognizer;
    UITapGestureRecognizer *_tabSelectionRecognizer;
    _Bool _suppressingScrollViewDidScroll;
    UIScrollView *_scrollView;
    NSMutableArray *_visibleItems;
    NSMutableSet *_reusableItems;
    _TabGradientView *_statusBarGradient;
    unsigned long long _activeAnimationCount;
    _MFTiltedTabItem *_interactivelyClosingItem;
    double _interactiveCloseProgress;
    double _interactiveCloseVelocity;
    _MFTiltedTabItem *_onlyHorizontalVelocityItem;
    _Bool _applyVelocityOnlyToHorizontalPosition;
    _MFTiltedTabItem *_pressedItem;
    _MFTouchDownTapRecognizer *_pressRecognizer;
    _MFTiltedTabItem *_selectedItem;
    _MFTiltedTabItem *_interactivelyReorderingItem;
    double _interactiveReorderOffsetDistanceFromTouch;
    double _interactiveReorderOffset;
    _Bool _reorderOffsetNeedsReset;
    CADisplayLink *_reorderScrollDisplayLink;
    double _reorderScrollVelocity;
    double _reorderScrollOffsetError;
    NSArray *_itemsInvolvedInAnimation;
    NSMutableSet *_itemsCurrentlyClosing;
    UIImage *_closeButtonImage;
    UIView *_bottomMaskView;
    UIMotionEffectGroup *_parallaxMotionEffectGroup;
    _Bool _reorderingEnabled;
    id <MFTiltedTabViewDelegate> _delegate;
    struct UIEdgeInsets _tabLayoutInsets;
}

@property(nonatomic, getter=isPresented) _Bool presented; // @synthesize presented=_presented;
@property(nonatomic) struct UIEdgeInsets tabLayoutInsets; // @synthesize tabLayoutInsets=_tabLayoutInsets;
@property(nonatomic) _Bool reorderingEnabled; // @synthesize reorderingEnabled=_reorderingEnabled;
@property(nonatomic) id <MFTiltedTabViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_layoutItemsAnimated:(_Bool)arg1;
- (double)_baseOffsetForItem:(id)arg1 index:(unsigned long long *)arg2 count:(double *)arg3;
- (double)_baseOffsetForItemAtIndex:(unsigned long long)arg1 withItemCountForLayout:(double)arg2;
- (double)_interactiveCloseProgressForLayout;
- (struct CGSize)_contentSizeForItemCount:(double)arg1;
- (double)_spaceBetweenTabsWithCount:(double)arg1;
- (void)_updateReorderAnimationsForItem:(id)arg1 withTimeAdjustment:(double)arg2 tabCount:(double)arg3 createIfNecessary:(_Bool)arg4;
- (void)_updateReorderAnimationBeginTimeForLayer:(id)arg1 withTimeAdjustment:(double)arg2;
- (void)_stopReorderingItem:(id)arg1 withFinalTimeAdjustment:(double)arg2 tabCount:(double)arg3;
- (id)_makeReorderAnimationWithDirection:(long long)arg1 springDuration:(double)arg2 tabCount:(double)arg3;
- (void)_updateSpringAnimationForView:(id)arg1 withBounds:(struct CGRect)arg2 animated:(_Bool)arg3;
- (void)_updateSpringAnimationForView:(id)arg1 withFrame:(struct CGRect)arg2 transform:(struct CATransform3D)arg3 zPosition:(double)arg4 opacity:(double)arg5 verticalScrollAdjustment:(double)arg6 animated:(_Bool)arg7;
- (void)_addSpringAnimationWithKeyPath:(id)arg1 toLayer:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4;
- (id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;
- (void)_configureVelocityForSpringAnimation:(id)arg1 withKeyPath:(id)arg2;
- (double)_velocityForSpringAnimations;
- (void)_updateSpringAnimationForView:(id)arg1 withFrame:(struct CGRect)arg2 verticalScrollAdjustment:(double)arg3 animated:(_Bool)arg4;
- (void)_closeButtonPressed:(id)arg1;
- (void)_updateCloseButtonImageForItem:(id)arg1;
- (void)_updateItemsInvolvedInAnimation;
- (void)_resetItem:(id)arg1;
- (_Bool)_shouldContinueAnimatingItem:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)setPresented:(_Bool)arg1 animated:(_Bool)arg2;
- (id)_reusableTabItem;
- (void)_finishAnimations;
- (void)_relinquishBorrowedViews;
- (void)_sendPresentedStateDidChangeToDelegateIfNeeded;
- (void)_tabSelectionRecognized:(id)arg1;
- (void)_tabReorderRecognized:(id)arg1;
- (void)_resetInteractiveReorderOffsetAtLocation:(struct CGPoint)arg1;
- (void)_updateReorderGesture;
- (void)_reorderScroll:(id)arg1;
- (void)_setReorderScrollVelocity:(double)arg1;
- (void)_tabCloseRecognized:(id)arg1;
- (void)_closeItem:(id)arg1;
- (double)_tabCloseAnimationSlideDistance;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)_gestureRecognizer:(id)arg1 shouldInteractWithItem:(id)arg2;
- (void)_tabPressUpdated:(id)arg1;
- (void)_setPressedItem:(id)arg1 animated:(_Bool)arg2;
- (id)_tiltedTabItemForLocation:(struct CGPoint)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGRect)_hitRectForItem:(id)arg1;
- (double)_topAreaHeightForTabsWithCount:(double)arg1;
- (double)_scrollingEffectFactorForTabsWithCount:(double)arg1;
- (struct CGRect)_tabLayoutBounds;
- (unsigned long long)_indexOfVisibleItem:(id)arg1;
- (unsigned long long)_numberOfItems;
- (void)_uninstallMotionEffectOntoScrollView;
- (void)_installMotionEffectOntoScrollView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

