/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFTiltedTabViewDelegate <NSObject>
- (double)tiltedTabView:(id)arg1 alphaValueForItemAtIndex:(unsigned long long)arg2;
- (struct CATransform3D)tiltedTabView:(id)arg1 layerTransformForItemAtIndex:(unsigned long long)arg2;
- (struct CGRect)tiltedTabView:(id)arg1 frameForItemAtIndex:(unsigned long long)arg2;
- (double)tiltedTabView:(id)arg1 headerHeightForItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 didMoveItemAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)tiltedTabView:(id)arg1 closeItemAtIndex:(unsigned long long)arg2;
- (_Bool)tiltedTabView:(id)arg1 canCloseItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 relinquishSnapshotView:(id)arg2 forItemAtIndex:(unsigned long long)arg3;
- (void)tiltedTabView:(id)arg1 relinquishContentView:(id)arg2 forItemAtIndex:(unsigned long long)arg3;
- (id)tiltedTabView:(id)arg1 snapshotViewForItemAtIndex:(unsigned long long)arg2 withBoundsInsets:(out struct UIEdgeInsets *)arg3;
- (id)tiltedTabView:(id)arg1 contentViewForItemAtIndex:(unsigned long long)arg2;
- (long long)numberOfItemsInTiltedTabView:(id)arg1;
- (void)tiltedTabViewDidDismiss:(id)arg1;
- (void)tiltedTabViewWillDismiss:(id)arg1;
- (void)tiltedTabViewDidPresent:(id)arg1;
- (void)tiltedTabViewWillPresent:(id)arg1;
@end

