/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol MFUserAgent
- (_Bool)canRegisterForAPSPush;
- (_Bool)isAllowedToAccessProtectedData;
- (_Bool)isMobileMail;
- (_Bool)isForeground;
- (void)networkActivityEnded:(id)arg1;
- (void)networkActivityStarted:(id)arg1;
- (void)autofetchAccount:(id)arg1 mailboxUid:(id)arg2;
- (id)focusedMessage;
- (_Bool)promptUserForPasswordWithTitle:(id)arg1 message:(id)arg2 account:(id)arg3 completionHandler:(id)arg4;
@end

