/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MFMailService.h"

@class NSDictionary, NSString;

@interface MFXPCEndpointService : NSObject <MFMailService>
{
    NSDictionary *_endpointInfoByProtocol;
    struct __CFDictionary *_endpoints;
}

+ (_Bool)handleMessage:(id)arg1 connectionState:(id)arg2 replyObject:(id *)arg3 error:(id *)arg4;
+ (id)serviceName;
+ (id)requiredEntitlement;
+ (id)sharedInstance;
- (id)listenerForProtocolNamed:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

