/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"

@class MFXPCEndpointInfo, NSMutableArray, NSString, NSXPCListener;

@interface MFXPCEndpoint : NSObject <NSXPCListenerDelegate>
{
    NSMutableArray *_clients;
    NSXPCListener *_listener;
    MFXPCEndpointInfo *_endpointInfo;
}

@property(retain, nonatomic) MFXPCEndpointInfo *endpointInfo; // @synthesize endpointInfo=_endpointInfo;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)clients;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

