/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSXPCConnection;

@interface MFXPCClient : NSObject
{
    NSXPCConnection *_connection;
    id _invalidationHandler;
    id _interruptionHandler;
}

@property(copy, nonatomic) id interruptionHandler; // @synthesize interruptionHandler=_interruptionHandler;
@property(copy, nonatomic) id invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
@property(readonly, retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (_Bool)hasEntitlement:(id)arg1;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;

@end

