/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MFServiceConnectionState.h"

@class MailXPCServices, NSLock, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface MFXPCConnection : NSObject <MFServiceConnectionState>
{
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_dispatch_queue> *_connectionQueue;
    NSObject<OS_dispatch_queue> *_messageQueue;
    int _cancelFlag;
    NSLock *_errorHandlerLock;
    id _errorHandler;
    MailXPCServices *_serviceManager;
}

@property(nonatomic) MailXPCServices *serviceManager; // @synthesize serviceManager=_serviceManager;
- (void)stop;
- (void)start;
- (void)handleError:(id)arg1;
@property(copy) id errorHandler; // @synthesize errorHandler=_errorHandler;
- (_Bool)shouldCancel;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;

@end

