/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MiniMallSource <NSObject>
@property(getter=isProtectedDataAvailable) _Bool protectedDataAvailable;
- (id)diagnosticDescription;
- (id)copyMessagesWithRemoteIDs:(id)arg1 options:(unsigned int)arg2;
- (long long)fetchMessagesMatchingCriterion:(id)arg1 limit:(unsigned int)arg2;
- (id)remoteIDsUsingSearchContext:(id)arg1 limit:(unsigned long long)arg2 error:(id *)arg3;
- (id)equivalentCriterion;
- (_Bool)canFetchSearchResults;
- (id)accountForAutoFetch;
- (id)mailboxUids;
- (_Bool)isBaseSource;
- (id)noMessagesLabelText;
- (unsigned long long)type;
- (void)reloadPreferences;
- (id)messageForMessageID:(id)arg1;
- (void)setLastViewedMessage:(id)arg1;
- (id)lastViewedMessageDate;
- (id)lastViewedMessage;
- (_Bool)shouldPlayNewMailSound;
- (_Bool)shouldShowUnreadCount;
- (_Bool)shouldIncludeWholeThreads;
- (_Bool)shouldThreadConversations;
- (void)emptyTrashAsNeeded;
- (_Bool)shouldArchiveByDefaultForMessageInfos:(id)arg1;
- (_Bool)supportsArchivingForMessageInfos:(id)arg1;
- (_Bool)deleteMovesToTrashForMessageInfos:(id)arg1;
- (_Bool)supportsThreadNotifications;
- (_Bool)shouldArchiveByDefault;
- (_Bool)supportsArchiving;
- (_Bool)deleteMovesToTrash;
- (_Bool)supportsFlagging;
- (_Bool)supportsSearch;
- (_Bool)supportsMarkAll;
- (_Bool)supportsMoveAll;
- (_Bool)supportsDeleteAll;
- (id)bulletinsContext;
- (id)uniqueIDForStorage;
- (id)uniqueIDForStatus;
- (id)mailboxName;
- (void *)comparator;
- (int)correspondingType;
- (_Bool)representsMailboxID:(unsigned int)arg1;
- (_Bool)representsMailboxUid:(id)arg1;
- (_Bool)canLoadOlderMessages;
- (_Bool)shouldGrowFetchWindow;
- (_Bool)shouldCompactOnFetch;
- (_Bool)needsFetch;
- (unsigned long long)currentFetchWindow;
- (long long)fetchNumOlderMessages:(unsigned long long)arg1 preservingUID:(id)arg2;
- (long long)fetchMobileSynchronously:(unsigned long long)arg1 preservingUID:(id)arg2 options:(unsigned long long)arg3 error:(id *)arg4;
- (void)applyChanges;
- (struct __CFDictionary *)copySendersByLibraryIDForConversation:(long long)arg1;
- (id)oldestKnownMessage;
- (long long)oldestKnownConversation;
- (id)cachedMessageForMessageInfo:(id)arg1;
- (id)messageForMessageInfo:(id)arg1 cacheIfNotAlready:(_Bool)arg2;
- (id)copyMessageInfosForConversationsContainingMessagesMatchingCriterion:(id)arg1;
- (id)copyMessageInfosMatchingCriterion:(id)arg1;
- (id)copyMessageInfos;
- (unsigned long long)onlyRemoteUnreadCount;
- (unsigned long long)remoteAndLocalUnreadCount;
- (unsigned long long)remoteMessageCount;
- (unsigned long long)messageCount;
- (void)flushCaches;
- (void)close;
- (void)open;

@optional
- (void)moveAllMessagesWithObserver:(id)arg1 toMailbox:(id)arg2;
- (void)markAllMessagesAsDeletedOrArchived:(unsigned long long)arg1 withObserver:(id)arg2;
- (void)markAllMessagesAsViewed;
- (void)markAllMessagesAsNotViewed;
- (void)markAllMessagesAsFlagged;
- (void)markAllMessagesAsNotFlagged;
@end

