/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSDictionary.h"

@class MFSparseMutable64IndexSet, NSArray, NSSet;

@interface MMRowsChangedContext : NSDictionary
{
    NSSet *_insertedIndexPaths;
    NSSet *_removedIndexPaths;
    NSSet *_updatedIndexPaths;
    NSSet *_destinationIndexPaths;
    NSSet *_relocatedIndexPaths;
    NSArray *_addedMessageInfos;
    NSArray *_removedMessageInfos;
    MFSparseMutable64IndexSet *_mergedConversations;
}

@property(retain, nonatomic) MFSparseMutable64IndexSet *mergedConversations; // @synthesize mergedConversations=_mergedConversations;
@property(retain, nonatomic) NSArray *removedMessageInfos; // @synthesize removedMessageInfos=_removedMessageInfos;
@property(retain, nonatomic) NSArray *addedMessageInfos; // @synthesize addedMessageInfos=_addedMessageInfos;
@property(retain, nonatomic) NSSet *relocatedIndexPaths; // @synthesize relocatedIndexPaths=_relocatedIndexPaths;
@property(retain, nonatomic) NSSet *destinationIndexPaths; // @synthesize destinationIndexPaths=_destinationIndexPaths;
@property(retain, nonatomic) NSSet *updatedIndexPaths; // @synthesize updatedIndexPaths=_updatedIndexPaths;
@property(retain, nonatomic) NSSet *removedIndexPaths; // @synthesize removedIndexPaths=_removedIndexPaths;
@property(retain, nonatomic) NSSet *insertedIndexPaths; // @synthesize insertedIndexPaths=_insertedIndexPaths;
- (void)dealloc;
- (id)description;
- (_Bool)hasChanges;

@end

