/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SourceSearchContext.h"

@class MFMessageCriterion, NSArray, NSString;

@interface MutableSourceSearchContext : SourceSearchContext
{
}


// Remaining properties
@property(retain, nonatomic) MFMessageCriterion *criterion;
@property(copy, nonatomic) NSArray *searchTerms;
@property(copy, nonatomic) NSString *searchText;
@end

