/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSCalendar.h"

@interface NSCalendar (MailStatusUpdateFormat)
- (unsigned long long)statusUpdateFormatWithDate:(id)arg1 now:(id)arg2 nextTransition:(id *)arg3;
@end

