/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (_CollectingInvocation)
- (id)mf_orOperations:(id)arg1;
- (id)mf_andOperations:(id)arg1;
@end

