/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (UpdateQueueItem)
- (void)cancelUpdate;
- (void)setUpdatePriority:(long long)arg1;
- (long long)updatePriority;
- (void)setNeedsUpdateAfterDelay:(double)arg1 maximumCoalescingDelay:(double)arg2;
- (void)setNeedsUpdateAfterDelay:(double)arg1;
- (void)setIsTopUpdatePriority:(_Bool)arg1;
- (void)updateOnce;
@end

