/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MessageLoadButton.h"

@interface PMIControl : MessageLoadButton
{
    unsigned long long _bytes;
}

- (void)setDownloading:(_Bool)arg1;
- (void)setBytesLeft:(unsigned long long)arg1;
- (id)text;
- (id)initWithBytesLeft:(unsigned long long)arg1;

@end

