/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SearchOperation.h"

@class MFMessageCriterion;

@interface PrimarySearchOperation : SearchOperation
{
    MFMessageCriterion *_sourcesCriterion;
}

+ (id)primarySearchForManager:(id)arg1 usingSearchContext:(id)arg2 withSources:(id)arg3 inLibrary:(id)arg4;
- (void)_performRemoteSearchesWithSources:(id)arg1 accountID:(id)arg2;
- (void)performRemoteSearchesAfterDelay:(double)arg1;
- (void)performLocalSearch;
- (id)_remoteSearchableSourcesByAccount;
- (id)_baseCriterionFromSources:(id)arg1;
- (void)main;
- (void)dealloc;
- (id)initForManager:(id)arg1 usingSearchContext:(id)arg2 withSources:(id)arg3 inLibrary:(id)arg4;

@end

