/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSOperation.h"

@class MFMailMessageLibrary, MFWeakReferenceHolder, NSArray, NSCondition, NSMutableArray, NSNumber, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, SearchManager, SourceSearchContext;

@interface SearchOperation : NSOperation
{
    MFWeakReferenceHolder *_managerHolder;
    NSObject<OS_dispatch_group> *_group;
    NSObject<OS_dispatch_queue> *_queue;
    NSCondition *_condition;
    int _monitorLock;
    NSMutableArray *_monitors;
    NSNumber *_identifier;
    MFMailMessageLibrary *_library;
    SourceSearchContext *_searchContext;
    SourceSearchContext *_serverSearchContext;
    NSArray *_sources;
}

@property(readonly, copy, nonatomic) NSArray *sources; // @synthesize sources=_sources;
@property(readonly, copy, nonatomic) SourceSearchContext *serverSearchContext; // @synthesize serverSearchContext=_serverSearchContext;
@property(readonly, copy, nonatomic) SourceSearchContext *searchContext; // @synthesize searchContext=_searchContext;
@property(readonly, retain, nonatomic) MFMailMessageLibrary *library; // @synthesize library=_library;
@property(retain) NSNumber *identifier; // @synthesize identifier=_identifier;
- (void)_performRemoteSearchWithSource:(id)arg1;
- (void)cancel;
- (void)signal;
- (void)waitForFinishOrCancel;
- (void)afterDelay:(double)arg1 perform:(id)arg2;
- (void)performAsync:(id)arg1;
- (void)_monitorWork:(id)arg1;
- (void)cancelMonitors;
- (void)unregisterMonitor:(id)arg1;
- (void)registerMonitor:(id)arg1;
@property SearchManager *manager;
- (void)dealloc;
- (id)initWithManager:(id)arg1 library:(id)arg2 sources:(id)arg3 searchContext:(id)arg4;

@end

