/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class MFMessageCriterion, NSArray;

@interface SearchOrderCache : NSObject
{
    int _lock;
    int _generation;
    struct __CFDictionary *_cache;
    NSArray *_primaryTerms;
    MFMessageCriterion *_dateCriterion;
    MFMessageCriterion *_unreadCriterion;
    id <SearchOrderCacheDelegate> _delegate;
    MFMessageCriterion *_criterion;
    unsigned long long _options;
}

@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) MFMessageCriterion *criterion; // @synthesize criterion=_criterion;
@property(readonly, nonatomic) id <SearchOrderCacheDelegate> delegate; // @synthesize delegate=_delegate;
- (id)sectionForMessage:(id)arg1;
- (unsigned long long)sortOrderForMessage:(id)arg1;
- (id)sectionForMessageInfo:(id)arg1 messageGenerator:(id)arg2;
- (unsigned long long)sortOrderForMessageInfo:(id)arg1 messageGenerator:(id)arg2;
- (_Bool)_cacheSortOrder:(unsigned long long)arg1 forMessageInfo:(id)arg2 generation:(int)arg3;
- (id)_copySortOrderContextForMessageInfo:(id)arg1 messageGenerator:(id)arg2;
- (id)unreadCriterion;
- (id)dateCriterion;
@property(copy, nonatomic) NSArray *primaryTerms;
- (id)diagnosticDescriptionWithMall:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

