/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UIActivityIndicatorView, UILabel;

@interface SearchProgressCell : UITableViewCell
{
    UILabel *_titleLabel;
    UIActivityIndicatorView *_spinner;
    long long _state;
}

+ (double)defaultRowHeight;
+ (id)_progressFont;
+ (void)invalidateCachedLayoutInformation;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)layoutSubviews;
- (double)_rowHeightForWidth:(double)arg1;
- (void)_getBaseTitleFrame:(struct CGRect *)arg1 baseSpinnerFrame:(struct CGRect *)arg2 withBounds:(struct CGRect)arg3;
- (void)_layoutChanged;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

