/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SearchManagerDelegate <NSObject>
- (void)searchManager:(id)arg1 finishedSearchWithIdentifier:(id)arg2;
- (void)searchManager:(id)arg1 foundMessages:(id)arg2 keepExistingMessages:(_Bool)arg3 forSearchWithIdentifier:(id)arg4 shouldWait:(_Bool)arg5;
@end

