/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SearchOrderCacheDelegate <NSObject>
- (unsigned long long)searchOrderCache:(id)arg1 rankValueForMessage:(id)arg2 context:(id)arg3;
- (id)searchOrderCache:(id)arg1 sectionDescriptionForRankValue:(unsigned long long)arg2 context:(id)arg3;
@end

