/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SearchOperation.h"

@class NSSet;

@interface SecondarySearchOperation : SearchOperation
{
    int _accountsLock;
    NSSet *_accounts;
}

+ (id)secondarySearchForManager:(id)arg1 usingSearchContext:(id)arg2 excludingSources:(id)arg3 inLibrary:(id)arg4;
- (void)performRemoteSearchesForAccount:(id)arg1;
- (void)accountsChanged:(id)arg1;
- (void)updateWithAccounts:(id)arg1;
- (id)accounts;
- (void)main;
- (void)dealloc;
- (id)initForManager:(id)arg1 usingSearchContext:(id)arg2 withSources:(id)arg3 inLibrary:(id)arg4;

@end

