/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "LibrarySearchSource.h"

@interface SecondaryLibrarySearchSource : LibrarySearchSource
{
}

- (id)_performSearchUsingManager:(id)arg1 usingSearchContext:(id)arg2;
- (void)_messagesAdded:(id)arg1;
- (id)mailboxUids;
- (_Bool)representsMailboxID:(unsigned int)arg1;
- (_Bool)representsMailboxUid:(id)arg1;
- (id)_baseCriterionFromSources:(id)arg1;

@end

