/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UISplitViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UISplitViewControllerDelegate.h"

@class NSString, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface SlidableMasterSplitViewController : UISplitViewController <UIGestureRecognizerDelegate, UISplitViewControllerDelegate>
{
    UIView *_tapView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    id _slideOutCompletionBlock;
    double _panHysteresisHorizontalLocation;
    unsigned long long _masterViewState;
    unsigned long long _lastGestureRecognized;
}

- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (id)_primaryViewControllerForCollapsingSplitViewController:(id)arg1;
- (void)_splitViewController:(id)arg1 didUnSlideViewController:(id)arg2;
- (void)tap:(id)arg1;
- (void)removeTapGestureRecognizer;
- (void)addTapGestureRecognizer;
- (void)pan:(id)arg1;
- (_Bool)_gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) _Bool allowUserInteractionWithDetailView;
@property(readonly) _Bool isMasterViewShownOnTop;
- (void)masterViewDidSlideOut:(_Bool)arg1;
- (void)masterViewWillSlideOut:(_Bool)arg1;
- (_Bool)masterViewCanSlideOut;
- (void)masterViewDidSlideIn:(_Bool)arg1;
- (void)masterViewWillSlideIn:(_Bool)arg1;
- (_Bool)masterViewCanSlideIn;
- (void)slideOutMasterViewAnimated:(_Bool)arg1 forcibly:(_Bool)arg2 withCompletionBlock:(id)arg3;
- (void)slideOutMasterViewAnimated:(_Bool)arg1;
- (void)slideInMasterViewAnimated:(_Bool)arg1;
- (void)_slideInOrNavigateBack:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

