/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol StackDataSource
- (void)stackController:(id)arg1 loadDataForItem:(id)arg2 inView:(id)arg3;
- (_Bool)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inView:(id)arg3;
- (id)stackController:(id)arg1 viewForItem:(id)arg2;
- (id)defaultViewForStackController:(id)arg1;
- (id)defaultItemForStackController:(id)arg1;
- (struct UIEdgeInsets)stackContainerViewEdgeInsetsForStackController:(id)arg1;
- (id)stackContainerViewForStackController:(id)arg1;
@end

