/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol StackDelegate <NSObject>

@optional
- (void)stackController:(id)arg1 willRemoveViewForItem:(id)arg2;
- (void)stackController:(id)arg1 willDisplayView:(id)arg2 forItem:(id)arg3;
- (void)stackController:(id)arg1 willStackView:(id)arg2 forItem:(id)arg3;
- (void)stackController:(id)arg1 dataLoadTimedOutInView:(id)arg2 forItem:(id)arg3;
- (void)stackControllerDidStopAnimatingViews:(id)arg1;
- (void)stackControllerWillStartAnimatingViews:(id)arg1;
- (void)stackControllerDidStopStackingViews:(id)arg1;
- (void)stackControllerWillStartStackingViews:(id)arg1;
@end

