/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MFMailboxUid.h"

@class NSString;

@interface StaticMailbox : MFMailboxUid
{
    NSString *_plistPath;
}

- (id)store;
- (unsigned long long)unreadCount;
- (id)name;
- (id)displayName;
- (id)plistPath;
- (void)dealloc;
- (id)initWithMessagePlistAtPath:(id)arg1;

@end

