/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SwipeActionPullViewDelegate <NSObject>
- (unsigned long long)nextStateForPullView:(id)arg1;
- (double)confirmationDistanceForPrimaryActionInSwipeActionPullView:(id)arg1;
- (_Bool)swipeActionPullViewShouldShowMoreButton:(id)arg1;
- (void)swipeActionPullView:(id)arg1 tappedAction:(unsigned long long)arg2;
- (id)swipeActionPullView:(id)arg1 titleForAction:(unsigned long long)arg2;
- (unsigned long long)secondaryActionForSwipeView:(id)arg1;
- (unsigned long long)primaryActionForSwipeView:(id)arg1;
@end

