/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UINavigationController.h"

@interface UINavigationController (Popovers)
- (void)didDismiss:(_Bool)arg1;
- (void)willDismiss:(_Bool)arg1;
- (_Bool)canDismiss;
@end

