/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (Popovers)
- (void)didDismiss:(_Bool)arg1;
- (void)willDismiss:(_Bool)arg1;
- (_Bool)canDismiss;
- (void)showPopoverViewController:(id)arg1 fromBarButtonItem:(id)arg2 animated:(_Bool)arg3;
@end

