/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (MailNavigationController)
- (id)mf_unreadCountForDisplay;
- (id)mf_statusBarSubtitleString;
- (void)mf_updateAlertSuppressionContextsForReason:(id)arg1;
- (id)mf_applicationContexts;
- (void)removedFromMailNavigationController:(id)arg1;
@end

