/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (MobileMail)
- (unsigned long long)supportedInterfaceOrientations;
- (void)preventScrollOnNextAppear;
- (void)preventNextScrollbarFlash;
- (int)propagateChangeDownwards:(id)arg1;
- (id)customDefaultPNGName;
- (_Bool)snapshotOnTermination;
- (_Bool)shouldSnapshot;
- (void)viewWillReappear:(_Bool)arg1;
- (void)viewWillFirstAppear:(_Bool)arg1;
- (_Bool)isReappearing;
@end

