/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (TransferOfMessages)
- (_Bool)usePadTransferStyle;
- (void)hideTransferNavigationControllerFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)showTransferNavigationController:(id)arg1 fromViewController:(id)arg2 animated:(_Bool)arg3;
- (_Bool)canShowTransferNavigationController;
- (void)resignPreparedForTransferOfMessages:(_Bool)arg1;
- (void)becomePreparedForTransferOfMessages:(id)arg1 options:(int)arg2 animated:(_Bool)arg3;
- (void)cancelTransferOfMessagesFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 fromViewController:(id)arg3 animated:(_Bool)arg4;
- (void)cancelTransferOfMessages:(_Bool)arg1;
- (void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 animated:(_Bool)arg3;
@end

