/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SharedMailboxController.h"

@interface VIPMailboxController : SharedMailboxController
{
}

- (void)reloadPreferences;
- (Class)criterionSourceClass;
- (id)iconImageName;
- (id)iconTintColor;
- (id)navigationTitle;
- (id)mailboxTitle;
- (id)unreadCriterion;
- (id)criterion;

@end

