/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIButton.h"

@interface WorkingPushButton : UIButton
{
    unsigned int _needsToSendMouseUpEvents:1;
}

- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)sendAction:(SEL)arg1 to:(id)arg2 forEvent:(id)arg3;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

