/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CALayer.h"

@interface CALayer (WeatherConditionExtensions)

// Remaining properties
@property(nonatomic) struct CGPoint lastPosition; // @dynamic lastPosition;
@property(nonatomic) double lastScale; // @dynamic lastScale;
@property(nonatomic) double originalOpacity; // @dynamic originalOpacity;
@end

