/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "BacksideControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAAssetLoaderDelegate.h"
#import "WACardLayoutDelegate.h"
#import "WACityPickerViewDelegate.h"
#import "WAWeatherCollectionFooterViewCellDelegate.h"
#import "WAWeatherCollectionViewCellDelegate.h"
#import "WAWeatherCollectionViewCellLayoutDelegate.h"

@class CLLocation, City, NSIndexPath, NSMutableArray, NSString, NSTimer, TabScrollIndicatorView, UIActionSheet, UICollectionView, UIImageView, UILabel, UILongPressGestureRecognizer, UINavigationController, UIPanGestureRecognizer, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView, WACityPickerViewController, WACollectionViewTransitionLayout, WAPagedFlowLayout, WAPlaceholderCell, WAReorderableCardLayout, WATouchButton, WATransitionCardLayout, WAWeatherCollectionFooterViewCell, WAWeatherCollectionViewCell, WAWeatherConditionBackgroundView;

@interface TabController : UIViewController <UIActionSheetDelegate, WAWeatherCollectionViewCellLayoutDelegate, WACardLayoutDelegate, UIScrollViewDelegate, BacksideControllerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UIGestureRecognizerDelegate, WAWeatherCollectionViewCellDelegate, WAWeatherCollectionFooterViewCellDelegate, WACityPickerViewDelegate, WAAssetLoaderDelegate>
{
    TabScrollIndicatorView *_tabScrollIndicatorView;
    City *_activeCity;
    City *_nextCity;
    NSMutableArray *_cities;
    id <TabControllerDelegate> _delegate;
    _Bool _pageControlUsed;
    UITapGestureRecognizer *_debugModeRecognizer;
    CLLocation *_debugLocation;
    UIActionSheet *_modalActionSheet;
    unsigned long long _transitionMode;
    NSTimer *_autoscrollTimer;
    double _transitionStartOffset;
    double _transitionEndOffset;
    WAPlaceholderCell *_draggedView;
    UINavigationController *_cityPickerNavigationController;
    _Bool _longPressWasCancelled;
    _Bool _overviewMode;
    _Bool _isRotatingInteraceOrientation;
    UICollectionView *_tabScrollLayer;
    UITapGestureRecognizer *_pageSwitchRecognizer;
    WACityPickerViewController *_cityPickerView;
    NSTimer *_timeHeartbeat;
    UILabel *_conditionLabel;
    UILabel *_descriptionLabel;
    WAPagedFlowLayout *_weatherPagesLayout;
    WAReorderableCardLayout *_cardLayout;
    WATransitionCardLayout *_transitionCardLayout;
    WAWeatherConditionBackgroundView *_conditionBackgroundView;
    WATouchButton *_infoButton;
    WATouchButton *_twcButton;
    UIImageView *_overviewBackground;
    WACollectionViewTransitionLayout *_transitionLayout;
    UIPinchGestureRecognizer *_pinchRecognizer;
    UILongPressGestureRecognizer *_longPressRecognizer;
    UITapGestureRecognizer *_tapRecognizer;
    UIPanGestureRecognizer *_deleteSwipeRecognizer;
    UIPanGestureRecognizer *_cancelDeleteRecognizer;
    WAWeatherCollectionFooterViewCell *_footerCell;
    NSIndexPath *_swipingIndexPath;
    NSIndexPath *_indexPathBeforeRotation;
    NSTimer *_backgroundUpdateTimer;
    double _initialScale;
    id _transitionCompletion;
    UIView *_bottomDivider;
    UIImageView *_statusBarShadow;
    WAWeatherCollectionViewCell *_pivotCell;
    UIImageView *_multiCityIntroductionImageView;
    UIView *_multiCityKeyLine;
    long long _initialDragIndex;
    WAWeatherCollectionViewCell *_transitionCell;
    struct CGPoint _swipePoint;
    struct CGPoint _panPoint;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(retain, nonatomic) WAWeatherCollectionViewCell *transitionCell; // @synthesize transitionCell=_transitionCell;
@property(nonatomic) _Bool isRotatingInteraceOrientation; // @synthesize isRotatingInteraceOrientation=_isRotatingInteraceOrientation;
@property(nonatomic) long long initialDragIndex; // @synthesize initialDragIndex=_initialDragIndex;
@property(retain, nonatomic) UIView *multiCityKeyLine; // @synthesize multiCityKeyLine=_multiCityKeyLine;
@property(retain, nonatomic) UIImageView *multiCityIntroductionImageView; // @synthesize multiCityIntroductionImageView=_multiCityIntroductionImageView;
@property(retain, nonatomic) WAWeatherCollectionViewCell *pivotCell; // @synthesize pivotCell=_pivotCell;
@property(retain, nonatomic) UIImageView *statusBarShadow; // @synthesize statusBarShadow=_statusBarShadow;
@property(retain, nonatomic) UIView *bottomDivider; // @synthesize bottomDivider=_bottomDivider;
@property(copy, nonatomic) id transitionCompletion; // @synthesize transitionCompletion=_transitionCompletion;
@property(nonatomic) double initialScale; // @synthesize initialScale=_initialScale;
@property(retain, nonatomic) NSTimer *backgroundUpdateTimer; // @synthesize backgroundUpdateTimer=_backgroundUpdateTimer;
@property(nonatomic) _Bool overviewMode; // @synthesize overviewMode=_overviewMode;
@property(nonatomic) struct CGPoint panPoint; // @synthesize panPoint=_panPoint;
@property(retain, nonatomic) NSIndexPath *indexPathBeforeRotation; // @synthesize indexPathBeforeRotation=_indexPathBeforeRotation;
@property(retain, nonatomic) NSIndexPath *swipingIndexPath; // @synthesize swipingIndexPath=_swipingIndexPath;
@property(nonatomic) struct CGPoint swipePoint; // @synthesize swipePoint=_swipePoint;
@property(nonatomic) _Bool longPressWasCancelled; // @synthesize longPressWasCancelled=_longPressWasCancelled;
@property(retain, nonatomic) WAWeatherCollectionFooterViewCell *footerCell; // @synthesize footerCell=_footerCell;
@property(retain, nonatomic) UIPanGestureRecognizer *cancelDeleteRecognizer; // @synthesize cancelDeleteRecognizer=_cancelDeleteRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *deleteSwipeRecognizer; // @synthesize deleteSwipeRecognizer=_deleteSwipeRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchRecognizer; // @synthesize pinchRecognizer=_pinchRecognizer;
@property(retain, nonatomic) WACollectionViewTransitionLayout *transitionLayout; // @synthesize transitionLayout=_transitionLayout;
@property(retain, nonatomic) UIImageView *overviewBackground; // @synthesize overviewBackground=_overviewBackground;
@property(retain, nonatomic) WATouchButton *twcButton; // @synthesize twcButton=_twcButton;
@property(retain, nonatomic) WATouchButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) WAWeatherConditionBackgroundView *conditionBackgroundView; // @synthesize conditionBackgroundView=_conditionBackgroundView;
@property(retain, nonatomic) WATransitionCardLayout *transitionCardLayout; // @synthesize transitionCardLayout=_transitionCardLayout;
@property(retain, nonatomic) WAReorderableCardLayout *cardLayout; // @synthesize cardLayout=_cardLayout;
@property(retain, nonatomic) WAPagedFlowLayout *weatherPagesLayout; // @synthesize weatherPagesLayout=_weatherPagesLayout;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *conditionLabel; // @synthesize conditionLabel=_conditionLabel;
@property(retain, nonatomic) NSTimer *timeHeartbeat; // @synthesize timeHeartbeat=_timeHeartbeat;
@property(retain, nonatomic) WACityPickerViewController *cityPickerView; // @synthesize cityPickerView=_cityPickerView;
@property(retain, nonatomic) CLLocation *debugLocation; // @synthesize debugLocation=_debugLocation;
@property(retain, nonatomic) UITapGestureRecognizer *pageSwitchRecognizer; // @synthesize pageSwitchRecognizer=_pageSwitchRecognizer;
@property(readonly, nonatomic) UICollectionView *tabScrollLayer; // @synthesize tabScrollLayer=_tabScrollLayer;
- (void)prepareToResume;
- (void)prepareToSuspend;
- (void)introMultiCityView;
- (void)snapshotMultiCityView;
- (void)_showLocation:(id)arg1;
- (void)_setRestState:(id)arg1;
- (void)_setNetworkState:(id)arg1;
- (void)_setLocationState:(id)arg1;
- (void)_updateDebugDisplay;
- (void)switchPages:(id)arg1;
- (void)updateLocInformation:(id)arg1;
- (id)_debugString;
- (long long)setActiveCityWithCoordinate:(CDStruct_c3b9c2ee)arg1 localCity:(_Bool)arg2;
- (void)hideHourly;
- (void)didTransitionToSize:(struct CGSize)arg1;
- (void)animateTransitionToSize:(struct CGSize)arg1;
- (void)willTransitionToSize:(struct CGSize)arg1;
- (void)discardTransitionCell;
- (void)createTransitionCell;
- (void)switchToBackWithNoCities;
- (void)hideBackside;
- (void)refreshForLocaleChange;
- (void)updateLocalCityWithCompletion:(id)arg1;
- (void)updateUserCitiesWithCompletion:(id)arg1;
- (void)updateAllCities;
- (void)celsiusPressedFromBacksideController:(id)arg1;
- (void)deleteTabScrollLayer;
- (void)reloadData;
- (void)_relayoutIndicatorView;
- (void)reloadIndicatorView:(id)arg1;
- (void)reloadFailedCities;
- (void)reloadLocalCity;
- (id)localCity;
- (void)saveStateToDisk;
- (id)cities;
- (void)redisplayAllUpdateLabels;
- (void)cityViewPressedInfoButton:(id)arg1;
- (void)_resetActiveCityPanOffset;
- (void)prepareToShowCities;
- (void)donePressedFromBacksideController:(id)arg1;
- (void)deleteCityAtIndex:(unsigned long long)arg1;
- (void)updateAddButtonState;
- (void)addCity:(id)arg1;
- (void)reloadAndReflowCities;
- (void)reloadCitiesAfterExternalAddition;
- (void)loadCities;
- (id)_cityOverrides;
- (void)_orderSubviews;
- (void)switchToBack:(id)arg1;
- (void)changeToOverviewModeLayout:(_Bool)arg1 pivotIndexPath:(id)arg2 animated:(_Bool)arg3 completion:(id)arg4;
- (void)changeToOverviewModeLayout:(_Bool)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)didUpdateWeather;
- (void)reflowConditions;
- (void)indicatorSelectionChanged:(id)arg1;
- (void)_animateSlideLeft:(_Bool)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showKeyLine:(_Bool)arg1;
- (void)updateExtendedWeatherOnVisibleCells;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_updateScrollerViewsLater;
- (void)updateBackgroundIfNeeded;
- (void)updateBackground;
- (void)_updateScrollerViews;
- (id)scroller;
- (id)_nextCity;
- (void)_setNextCity:(id)arg1;
- (void)_setScrollPointToActiveCity;
- (float)_offsetForDocument:(unsigned long long)arg1;
- (int)_documentForOffset:(float)arg1;
- (void)_reLayoutBottomToolbar;
- (void)_tileWithFrame:(struct CGRect)arg1;
- (struct CGRect)_backsideViewFrame;
- (void)setDelegate:(id)arg1;
- (unsigned long long)activeCityIndex;
- (void)setActiveCityIndex:(unsigned long long)arg1;
- (void)setActiveCity:(id)arg1;
- (id)activeCity;
- (unsigned long long)cityCount;
- (void)_resetTabScrollIndicator;
- (void)showLocalCity:(_Bool)arg1;
- (void)setupTabScrollIndicatorView;
- (void)_updateLocalWeather;
- (void)animateDeletionOfRowWithCell:(id)arg1;
- (void)hideLocationPickerAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)addLocation:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)_showModalAlertWithString:(id)arg1;
- (void)animateShowingLocationPicker;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)_isEditing;
- (void)cancelDeletion:(id)arg1;
- (void)longTapped:(id)arg1;
- (void)_stopAutoscrollTimer;
- (void)_swapCellsIfNecessary;
- (void)_autoscroll:(id)arg1;
- (void)deleteSwiping:(id)arg1;
- (void)tappedOverviewCell:(id)arg1;
- (void)updateDUETDebugMessage:(unsigned long long)arg1 weatherDetail:(unsigned long long)arg2 andLocalDetail:(unsigned long long)arg3;
- (void)_updateBackgroundForSunHeightChange:(id)arg1;
- (void)_iterateConditions:(_Bool)arg1;
- (void)_setDebugConditionCode:(long long)arg1 isNight:(_Bool)arg2;
- (void)_previousCondition:(id)arg1;
- (void)_nextCondition:(id)arg1;
- (void)toggleOverview:(id)arg1;
- (void)_cleanUpTransition:(_Bool)arg1;
- (unsigned long long)transitionMode;
- (void)_endTransition:(_Bool)arg1 immediately:(_Bool)arg2 completion:(id)arg3;
- (void)_setChromeAlphaWithProgress:(double)arg1;
- (void)_setTansitionProgress:(double)arg1;
- (_Bool)_prepareTransitionAtPivotIndexPath:(id)arg1 forMode:(unsigned long long)arg2;
- (void)_putbackConditionViewFromPivotCell;
- (id)_indexPathOfReferenceItemForLayoutTransitionInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 transitionLayoutForOldLayout:(id)arg2 newLayout:(id)arg3;
- (id)collectionViewForLayout:(id)arg1;
- (void)_cancelDeletion;
- (void)showPageScrollerChrome:(_Bool)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (double)transitionalParallaxOffsetForCellAtItemIndex:(long long)arg1;
- (void)removeExtraViewsFromPivotCell;
- (void)addExtraViewsToCell:(id)arg1 atIndexPath:(id)arg2;
- (long long)weatherModeForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 withLayoutAttributes:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)_configureCell:(id)arg1 atIndexPath:(id)arg2;
- (_Bool)isTransitioning;
- (void)discardOldData;
- (void)updateTimeLabels;
- (void)endClockUpdates;
- (void)beginClockUpdates;
- (void)createTabScrollLayer;
- (long long)preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (id)init;
- (void)twcButtonPressed;
- (void)infoButtonPressed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

