/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "WeatherView.h"

#import "HourlyScrollerBeltDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class HourlyScrollerBeltView, NSDateFormatter, NSMutableArray, NSString, UILabel, UIScrollView, UITapGestureRecognizer, UIView, WACityDetailsView, WAWeatherCardView;

@interface WAWeatherCityView : WeatherView <UIScrollViewDelegate, HourlyScrollerBeltDelegate, UIGestureRecognizerDelegate>
{
    double _panOffset;
    _Bool _isTallCell;
    _Bool _isTallDevice;
    _Bool _hasExtendedWeatherData;
    long long _mode;
    double _transitionProgress;
    UIView *_bottomDivider;
    WAWeatherCardView *_cardView;
    UIView *_cardMaskView;
    UIView *_pageView;
    UIView *_pageUpperView;
    UIView *_pageHeaderView;
    UIScrollView *_pageScrollView;
    UIView *_pinnedContainer;
    UIView *_overDivider;
    UIView *_underDivider;
    UIView *_afterDayForecastsDivider;
    UIView *_verticalDivider;
    UILabel *_pageCityName;
    UILabel *_pageConditionDescription;
    UILabel *_pageTemperature;
    UILabel *_pageDayName;
    UILabel *_pageDayDescription;
    UILabel *_pageHighTemperature;
    UILabel *_pageLowTemperature;
    UILabel *_naturalLanguageDescriptionLabel;
    UIView *_afterNaturalLanguageDivider;
    WACityDetailsView *_detailsView;
    UIView *_pageCityNameSnapshotView;
    UIView *_pageTemperatureSnapshotView;
    UITapGestureRecognizer *_detailedConditionsRecognizer;
    UIView *_textTreatmentView;
    HourlyScrollerBeltView *_hourlyBelt;
    NSMutableArray *_dayForecastViews;
    double _deviceWidth;
    double _deviceHeight;
    NSDateFormatter *_dateFormatter;
}

+ (double)edgePadding;
+ (double)pageScrollViewInset;
+ (double)underDividerY;
+ (double)overDividerY;
@property(nonatomic) _Bool hasExtendedWeatherData; // @synthesize hasExtendedWeatherData=_hasExtendedWeatherData;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) double deviceHeight; // @synthesize deviceHeight=_deviceHeight;
@property(nonatomic) double deviceWidth; // @synthesize deviceWidth=_deviceWidth;
@property(nonatomic) _Bool isTallDevice; // @synthesize isTallDevice=_isTallDevice;
@property(retain, nonatomic) NSMutableArray *dayForecastViews; // @synthesize dayForecastViews=_dayForecastViews;
@property(retain, nonatomic) HourlyScrollerBeltView *hourlyBelt; // @synthesize hourlyBelt=_hourlyBelt;
@property(retain, nonatomic) UIView *textTreatmentView; // @synthesize textTreatmentView=_textTreatmentView;
@property(retain, nonatomic) UITapGestureRecognizer *detailedConditionsRecognizer; // @synthesize detailedConditionsRecognizer=_detailedConditionsRecognizer;
@property(retain, nonatomic) UIView *pageTemperatureSnapshotView; // @synthesize pageTemperatureSnapshotView=_pageTemperatureSnapshotView;
@property(retain, nonatomic) UIView *pageCityNameSnapshotView; // @synthesize pageCityNameSnapshotView=_pageCityNameSnapshotView;
@property(retain, nonatomic) WACityDetailsView *detailsView; // @synthesize detailsView=_detailsView;
@property(retain, nonatomic) UIView *afterNaturalLanguageDivider; // @synthesize afterNaturalLanguageDivider=_afterNaturalLanguageDivider;
@property(retain, nonatomic) UILabel *naturalLanguageDescriptionLabel; // @synthesize naturalLanguageDescriptionLabel=_naturalLanguageDescriptionLabel;
@property(retain, nonatomic) UILabel *pageLowTemperature; // @synthesize pageLowTemperature=_pageLowTemperature;
@property(retain, nonatomic) UILabel *pageHighTemperature; // @synthesize pageHighTemperature=_pageHighTemperature;
@property(retain, nonatomic) UILabel *pageDayDescription; // @synthesize pageDayDescription=_pageDayDescription;
@property(retain, nonatomic) UILabel *pageDayName; // @synthesize pageDayName=_pageDayName;
@property(retain, nonatomic) UILabel *pageTemperature; // @synthesize pageTemperature=_pageTemperature;
@property(retain, nonatomic) UILabel *pageConditionDescription; // @synthesize pageConditionDescription=_pageConditionDescription;
@property(retain, nonatomic) UILabel *pageCityName; // @synthesize pageCityName=_pageCityName;
@property(retain, nonatomic) UIView *verticalDivider; // @synthesize verticalDivider=_verticalDivider;
@property(retain, nonatomic) UIView *afterDayForecastsDivider; // @synthesize afterDayForecastsDivider=_afterDayForecastsDivider;
@property(retain, nonatomic) UIView *underDivider; // @synthesize underDivider=_underDivider;
@property(retain, nonatomic) UIView *overDivider; // @synthesize overDivider=_overDivider;
@property(retain, nonatomic) UIView *pinnedContainer; // @synthesize pinnedContainer=_pinnedContainer;
@property(retain, nonatomic) UIScrollView *pageScrollView; // @synthesize pageScrollView=_pageScrollView;
@property(retain, nonatomic) UIView *pageHeaderView; // @synthesize pageHeaderView=_pageHeaderView;
@property(retain, nonatomic) UIView *pageUpperView; // @synthesize pageUpperView=_pageUpperView;
@property(retain, nonatomic) UIView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) UIView *cardMaskView; // @synthesize cardMaskView=_cardMaskView;
@property(retain, nonatomic) WAWeatherCardView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) UIView *bottomDivider; // @synthesize bottomDivider=_bottomDivider;
@property(nonatomic) _Bool isTallCell; // @synthesize isTallCell=_isTallCell;
@property(nonatomic) double transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (long long)currentCondition;
- (long long)currentHourIndex;
- (id)currentTemperature;
- (void)didEndScrolling;
- (void)didBeginScrolling;
- (_Bool)isDay;
- (_Bool)isCelsius;
- (id)hourlyForecasts;
- (long long)numberOfHours;
- (unsigned long long)observationTime;
- (unsigned long long)sunsetTime;
- (unsigned long long)sunriseTime;
- (void)refreshLocalization;
- (void)cityDidStartWeatherUpdate:(id)arg1;
- (_Bool)updateWeatherDisplayForCity:(id)arg1;
- (void)resetVerticalScrollOffset;
- (void)setPanOffset:(double)arg1;
- (void)setStaggerOffset:(double)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (double)_headerMaximumScrollOffset;
- (double)_pageScrollViewOriginY;
- (void)layoutSubviews;
- (void)prepareForResuse;
- (void)tappedCity:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)setUVIndex:(unsigned long long)arg1;
- (void)setVisibility:(double)arg1 withDataCelsius:(_Bool)arg2;
- (void)setPressure:(double)arg1 withDataCelsius:(_Bool)arg2;
- (void)setPrecipitation:(double)arg1;
- (void)setFeelsLikeWithTemperature:(double)arg1 andDataCelsius:(_Bool)arg2;
- (void)setWindWithSpeed:(double)arg1 andDirection:(double)arg2;
- (void)setHumidity:(double)arg1;
- (void)setPrecipitationsWithPrecipitationForecast:(int)arg1 hourlyForecasts:(id)arg2;
- (void)setSunsetTime:(unsigned long long)arg1;
- (void)setSunriseTime:(unsigned long long)arg1;
- (id)extendedDetailsStringWithName:(id)arg1 content:(id)arg2;
- (id)_percentFormatter;
- (void)didTransitionToSize:(struct CGSize)arg1;
- (void)animateTransitionToSize:(struct CGSize)arg1;
- (void)willTransitionToSize:(struct CGSize)arg1;
- (void)_forceWeatherDescription:(id)arg1;
- (_Bool)_shouldShowExtendedWeather;
- (void)updateExtendedWeather;
- (void)updateUIIncludingExtendedWeather:(_Bool)arg1;
- (void)updateUI;
- (void)updateTimeUI;
- (void)showCity:(id)arg1;
- (void)cleanupTextTreatmentView;
- (id)newTextTreatmentViewForCondition:(long long)arg1;
- (void)_removePageModeViews;
- (void)setContentSizeForExtendedWeatherVisible:(_Bool)arg1;
- (void)_layoutScrollViewContent;
- (void)_layoutPinnedContainer;
- (void)_createContentViewsForPageModeScrollView;
- (void)_createPinnedContainerViews;
- (void)_createPageModeViews;
- (void)_removeCardModeViews;
- (void)_createCardModeViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

