/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol WeatherValidatorDelegate <NSObject>
- (void)didFailWithError:(id)arg1;
- (void)didValidateLocation:(id)arg1;

@optional
- (void)didFailGeocodeWithError:(id)arg1;
- (void)didGeocodeLocation:(id)arg1;
@end

