/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "TabControllerDelegate.h"
#import "WeatherUpdaterDelegate.h"

@class NSString, NSTimer, TabController;

@interface WeatherController : NSObject <TabControllerDelegate, WeatherUpdaterDelegate>
{
    NSTimer *_updateTimer;
    TabController *_tabController;
}

@property(nonatomic) TabController *tabController; // @synthesize tabController=_tabController;
- (void)failedUpdate:(id)arg1;
- (void)refreshForLocaleChange;
- (void)resume;
- (void)suspend;
- (void)didUpdateWeather;
- (void)_startUpdateTimer;
- (void)_updateWeatherData;
- (void)saveStateToDisk;
- (void)tabControllerWillScroll:(id)arg1;
- (void)dealloc;
- (void)_stopUpdateTimer;
- (id)init;
- (void)_reachabilityChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

