/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSTableCell.h"

@class UIImageView;

@interface AllowChangesCell : PSTableCell
{
    UIImageView *_lock;
}

- (void)layoutSubviews;
- (_Bool)canReload;
- (void)setValue:(id)arg1;

@end

