/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@class SuggestedAppsController;

@interface ContinuityController : PSListController
{
    SuggestedAppsController *_suggestedAppsController;
}

- (void)setContinuityEnabled:(id)arg1 specifier:(id)arg2;
- (id)isContinuityEnabled:(id)arg1;
- (id)specifiers;
- (void)profileNotification:(id)arg1;
- (void)updateContinuitySpecifiers;
- (_Bool)isContinuityRestricted;
- (void)dealloc;
- (id)init;

@end

