/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@interface ControlCenterListController : PSListController
{
}

- (void)setAllowedWithinApps:(id)arg1 specifier:(id)arg2;
- (id)allowedWithinApps:(id)arg1;
- (void)profileNotification:(id)arg1;
- (void)setEnabledInLockScreen:(id)arg1 specifier:(id)arg2;
- (id)enabledInLockScreen:(id)arg1;
- (id)specifiers;
- (void)dealloc;
- (id)init;

@end

