/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@interface DeviceNameEditingController : PSListController
{
}

- (id)deviceName:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)canBeShownFromSuspendedState;
- (_Bool)shouldSelectResponderOnAppearance;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)suspend;
- (id)specifiers;

@end

