/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol DevicePINControllerDelegate <NSObject>

@optional
- (void)devicePINControllerDidDismissPINPane:(id)arg1;
- (void)devicePINController:(id)arg1 didAcceptChangedPIN:(id)arg2;
- (void)devicePINController:(id)arg1 didAcceptSetPIN:(id)arg2;
- (void)didAcceptSetPIN;
- (void)didAcceptRemovePIN;
- (void)didAcceptChangedPIN;
- (void)didCancelEnteringPIN;
- (void)willCancelEnteringPIN;
- (void)didAcceptEnteredPIN:(id)arg1;
- (void)didAcceptEnteredPIN;
- (void)willAcceptEnteredPIN;
@end

