/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PSCellularAccountDetailDelegate <NSObject>

@optional
- (void)managePlanPressed:(id)arg1;
- (id)getPlanExpireDate:(id)arg1;
- (id)getPlanPurchaseDate:(id)arg1;
- (id)getPlanStatusDate:(id)arg1;
- (id)getPlanStatus:(id)arg1;
- (id)getCarrierName:(id)arg1;
- (id)getPlanName:(id)arg1;
@end

