/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@interface PSFingerprintController : PSListController
{
}

- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)canBeShownFromSuspendedState;
- (_Bool)shouldSelectResponderOnAppearance;
- (id)specifiers;
- (void)setFingerprintName:(id)arg1;
- (id)fingerprintName;
- (void)deleteFingerprint:(id)arg1;
- (id)representedBiometricIdentity;

@end

