/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSTableCell.h"

@interface PSLeadingCheckmarkCell : PSTableCell
{
}

+ (id)spacerIcon;
+ (id)checkIcon;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (void)setChecked:(_Bool)arg1;
- (_Bool)canBeChecked;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

