/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListItemsController.h"

#import "UIAlertViewDelegate.h"

@class NSString;

@interface PSLTEOptionsController : PSListItemsController <UIAlertViewDelegate>
{
}

+ (_Bool)isOnCallOfSubType:(struct __CFString *)arg1;
+ (void)setVoiceEnabled:(_Bool)arg1;
+ (_Bool)shouldShowVoiceOptions;
+ (_Bool)isProvisioning;
+ (unsigned long long)voiceAvailability;
+ (_Bool)isVoiceEnabled;
+ (void)_executeCTConnectionDependentBlock:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)presentOnCallAlertIfNeededForService:(unsigned long long)arg1 okayCompletion:(id)arg2;
- (void)presentCallCarrierAlert;
- (void)updateProvisioning;
- (void)listItemSelected:(id)arg1;
- (id)specifiers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

