/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PSSearchControllerDelegate <NSObject>
- (id)rootSpecifiersForSearchController:(id)arg1;
- (void)searchController:(id)arg1 openURL:(id)arg2;
@end

