/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DevicePINController.h"

@interface PSTouchIDPINController : DevicePINController
{
}

- (_Bool)_asyncSetPinCompatible;
- (id)stringsBundle;
- (id)pinInstructionsPrompt;
- (void)setPane:(id)arg1;
- (_Bool)showSimplePINCancelButtonOnLeft;

@end

