/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@interface SiriContentRestrictionsController : PSListController
{
}

- (id)featureValue:(id)arg1;
- (void)setFeatureValue:(id)arg1 specifier:(id)arg2;
- (id)reversedBoolFeatureValue:(id)arg1;
- (void)setReversedBoolFeatureValue:(id)arg1 specifier:(id)arg2;
- (id)specifiers;

@end

