/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSListController.h"

@class NSLock, NSMutableDictionary, NSString, NSTimer, PSSpecifier;

@interface AboutController : PSListController
{
    NSMutableDictionary *_mediaDict;
    NSMutableDictionary *_accessorySpecifiers;
    PSSpecifier *_headsetSpecifier;
    PSSpecifier *_accessoryDividerSpecifier;
    NSString *_loading;
    NSTimer *_reloadTimer;
    _Bool _isGeneratingNotifications;
    _Bool _threadRunning;
    _Bool _cancel;
    _Bool _loaded;
    _Bool _accessory;
    _Bool _firstViewDidAppear;
    int _carrierCellState;
    id <NSObject> _photoVideoNotificationToken;
    NSLock *_lock;
    NSString *_serviceProviderNameForSPN;
}

- (void)_availableWirelessAccessoryDidUpdate:(id)arg1;
- (void)_accessoryDidUpdate:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willResignActive;
- (void)willBecomeActive;
- (void)viewDidAppear:(_Bool)arg1;
- (id)init;
- (void)simStatusChangedToReady;
- (void)mediaLibraryDidChange:(id)arg1;
- (void)enableMLUpdates:(_Bool)arg1;
- (void)forceReloadMediaStats:(id)arg1;
- (void)cleanupTimer;
- (void)newCarrierNotification;
- (id)specifiers;
- (id)deviceName:(id)arg1;
- (void)setDeviceName:(id)arg1 specifier:(id)arg2;
- (void)willUnlock;
- (id)_photos:(id)arg1;
- (id)_videos:(id)arg1;
- (id)_songs:(id)arg1;
- (id)countForKey:(id)arg1;
- (void)_loadMediaFinished:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)updateCarrierSpecifier:(id)arg1;
- (id)_MINString:(id)arg1;
- (id)_NAIString:(id)arg1;
- (id)_ERIString:(id)arg1;
- (id)_PRLString:(id)arg1;
- (id)_getCTMobileEquipmentInfo:(struct __CFString *)arg1;
- (id)_carrierVersion:(id)arg1;
- (id)_macAddress;
- (id)_bluetoothMACAddress;
- (id)valueForSpecifier:(id)arg1;
- (id)_myNumber;
- (void)_addKey:(id)arg1 value:(id)arg2 array:(id)arg3 isCopyable:(_Bool)arg4;

@end

