/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class AlertStyleView;

@interface AlertStyleSelectionView : UIView
{
    AlertStyleView *_noneAlertType;
    AlertStyleView *_topAlertType;
    AlertStyleView *_frontAlertType;
    unsigned long long _selectedStyle;
}

@property(nonatomic) unsigned long long selectedStyle; // @synthesize selectedStyle=_selectedStyle;
- (void)layoutSubviews;
- (void)layoutAlertType:(id)arg1 withXPos:(float)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

