/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "LocationServicesListController.h"

@class PSSpecifier;

@interface AllowLocationRestrictionsController : LocationServicesListController
{
    PSSpecifier *_allowedGroup;
}

- (void)dealloc;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)specifiers;

@end

