/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSListController.h"

@class NSMutableArray, NSMutableDictionary, UIActionSheet, UIAlertView;

@interface AutomaticContentDownloadController : PSListController
{
    UIAlertView *_locationConfirmationAlert;
    UIActionSheet *_locationConfirmationSheet;
    _Bool _hasLocationApps;
    NSMutableArray *_applications;
    NSMutableDictionary *_applicationStates;
}

@property(retain, nonatomic) NSMutableDictionary *applicationStates; // @synthesize applicationStates=_applicationStates;
@property(retain, nonatomic) NSMutableArray *applications; // @synthesize applications=_applications;
- (_Bool)_appObjectIsLocApp:(id)arg1;
- (void)confirmationClickedButtonAtIndex:(long long)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)applicationEnabled:(id)arg1;
- (void)setApplicationEnabled:(id)arg1 forSpecifier:(id)arg2;
- (id)backgroundRefreshState:(id)arg1;
- (void)setBackgroundRefreshState:(id)arg1 withSpecifier:(id)arg2;
- (void)_reallySetBackgroundRefreshState:(_Bool)arg1;
- (id)specifiers;
- (void)migrateApplication:(id)arg1;
- (id)whitelist;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

@end

