/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PSTableCell, UIImageView;

@interface LocationUsageMixin : NSObject
{
    PSTableCell *_cell;
    int _usage;
    UIImageView *_usageIndicator;
    _Bool _labelOverlapsIndicator;
    double horizontalOffset;
}

@property(nonatomic) double horizontalOffset; // @synthesize horizontalOffset;
@property(nonatomic) int usage; // @synthesize usage=_usage;
- (void)layoutUsageIndicator;
- (struct CGSize)usageIndicatorSize;
- (id)iconNameForUsage:(int)arg1;
- (void)dealloc;
- (id)initWithTableCell:(id)arg1;

@end

