/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PrefsRootController.h"

@interface PrefsRootController (Private)
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)pushViewController:(id)arg1 transition:(int)arg2;
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;
- (void)setupControllerForToolbar:(id)arg1;
- (void)mediaServerDiedNotification:(id)arg1;
@end

