/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSTableCell.h"

@class UIImageView, UILabel;

@interface PSBadgedTableCell : PSTableCell
{
    UIImageView *_badgeImageView;
    UILabel *_badgeNumberLabel;
    int _badgeInt;
}

+ (id)reuseIdentifierForClassAndType:(long long)arg1;
- (void)badgeWithInteger:(long long)arg1;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)resetLocale;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

