/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSEditableTableCell.h"

@interface PSMesaIdentityTableCell : PSEditableTableCell
{
}

- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)isEditing;

@end

