/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSEditableListController.h"

#import "BiometricKitDelegate-Protocol.h"
#import "BiometricKitUIEnrollResultDelegate-Protocol.h"

@class BiometricKit, NSMutableArray;

@interface PSMesaSettingsController : PSEditableListController <BiometricKitUIEnrollResultDelegate, BiometricKitDelegate>
{
    NSMutableArray *_enrollmentSpecifiers;
    long long _storeState;
    BiometricKit *_highlightMatcher;
}

@property(retain, nonatomic) BiometricKit *highlightMatcher; // @synthesize highlightMatcher=_highlightMatcher;
@property(nonatomic) long long storeState; // @synthesize storeState=_storeState;
@property(retain, nonatomic) NSMutableArray *enrollmentSpecifiers; // @synthesize enrollmentSpecifiers=_enrollmentSpecifiers;
- (void)matchResult:(id)arg1;
- (void)highlightSpecifier:(id)arg1;
- (void)enrollmentCompletedForIdentity:(id)arg1;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)updateAfterEditing;
- (void)setEditable:(_Bool)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_cancelMatching;
- (void)_setupMatching;
- (void)enrollResult:(int)arg1 identity:(id)arg2;
- (void)addEnrollment:(id)arg1;
- (id)enrollmentGroupSpecifiers;
- (void)setName:(id)arg1 forEnrollmentSpecifier:(id)arg2;
- (id)nameForEnrollmentSpecifier:(id)arg1;
- (id)specifiers;
- (void)suspend;
- (_Bool)canBeShownFromSuspendedState;
- (id)_authorizationToken;
- (_Bool)isMesaEditingAllowed;
- (_Bool)isMesaForPurchasesRestricted;
- (void)setMesaForPurchasesEnabled:(id)arg1 specifier:(id)arg2;
- (id)isMesaForPurchasesEnabled:(id)arg1;
- (void)updateStoreBiometricsState;
- (_Bool)isMesaUnlockRestricted;
- (void)setMesaUnlockEnabled:(id)arg1 specifier:(id)arg2;
- (id)isMesaUnlockEnabled:(id)arg1;
- (void)dealloc;

@end

