/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSEditingPane.h"

@class TKTonePicker;

@interface RingtonePane : PSEditingPane
{
    TKTonePicker *_picker;
}

+ (id)tonePickerWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)viewDidBecomeVisible;
- (void)stopPlaying;
- (void)ringtonePicker:(id)arg1 selectedRingtoneWithIdentifier:(id)arg2;
- (id)preferenceValue;
- (void)setPreferenceValue:(id)arg1;
- (void)setPreferenceSpecifier:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

