/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSListController.h"

@interface SpeakersPrefController : PSListController
{
}

+ (_Bool)isVisible;
- (id)eqIndex:(id)arg1;
- (void)setEQIndex:(id)arg1 specifier:(id)arg2;
- (id)specifiers;
- (void)dealloc;
- (id)init;
- (void)update;

@end

