/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSListController.h"

@class NSString;

@interface TCCAccessController : PSListController
{
    struct __CFString *_serviceKey;
    NSString *_footer;
    NSString *_header;
    NSString *_explanation;
}

+ (_Bool)isServiceRestricted:(id)arg1;
@property(copy, nonatomic) NSString *explanation; // @synthesize explanation=_explanation;
@property(copy, nonatomic) NSString *header; // @synthesize header=_header;
@property(copy, nonatomic) NSString *footer; // @synthesize footer=_footer;
- (void)updateSpecifiersForImposedSettings;
- (id)accesssForSpecifier:(id)arg1;
- (void)setAccess:(id)arg1 forSpecifier:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (id)specifiers;
- (void)setSpecifier:(id)arg1;
- (void)dealloc;
- (id)init;

@end

