/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "RingtonePane.h"

@interface TexttonePane : RingtonePane
{
}

+ (id)tonePickerWithFrame:(struct CGRect)arg1;
- (void)setPreferenceSpecifier:(id)arg1;

@end

