/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PSEditingPane.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UISearchBar, UITableView;

@interface TimeZonePane : PSEditingPane <UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_completionTable;
    NSArray *_cities;
    UISearchBar *_searchBar;
}

+ (void)setTimeZone:(id)arg1;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setPreferenceSpecifier:(id)arg1;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)textValueChanged:(id)arg1;
- (void)layoutSubviews;
- (void)updateTableInsets;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

