/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol BulletinBoardAppDetailControllerDelegate <NSObject>
- (void)appDetailController:(id)arg1 moveSpecifier:(id)arg2 toOnPosition:(_Bool)arg3 isSubsection:(_Bool)arg4;
- (void)appDetailControllerWillDisappear:(id)arg1;

@optional
- (void)appDetailController:(id)arg1 allowNotificationsChangedForSpecifier:(id)arg2;
@end

